// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Unleash
{
    /// <summary>
    /// ApiToken schema
    /// </summary>
    [UnleashResourceType("unleash:index/apiToken:ApiToken")]
    public partial class ApiToken : global::Pulumi.CustomResource
    {
        /// <summary>
        /// An environment the token has access to.
        /// </summary>
        [Output("environment")]
        public Output<string> Environment { get; private set; } = null!;

        /// <summary>
        /// When the token expires
        /// </summary>
        [Output("expiresAt")]
        public Output<string?> ExpiresAt { get; private set; } = null!;

        /// <summary>
        /// A project the token belongs to.
        /// </summary>
        [Output("project")]
        public Output<string> Project { get; private set; } = null!;

        /// <summary>
        /// The list of projects this token has access to. If the token has access to specific projects they will be listed here. If the token has access to all projects it will be represented as `[*]`.
        /// </summary>
        [Output("projects")]
        public Output<ImmutableArray<string>> Projects { get; private set; } = null!;

        /// <summary>
        /// Secret token value.
        /// </summary>
        [Output("secret")]
        public Output<string> Secret { get; private set; } = null!;

        /// <summary>
        /// The name of the token.
        /// </summary>
        [Output("tokenName")]
        public Output<string?> TokenName { get; private set; } = null!;

        /// <summary>
        /// The type of the token.
        /// </summary>
        [Output("type")]
        public Output<string?> Type { get; private set; } = null!;


        /// <summary>
        /// Create a ApiToken resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ApiToken(string name, ApiTokenArgs? args = null, CustomResourceOptions? options = null)
            : base("unleash:index/apiToken:ApiToken", name, args ?? new ApiTokenArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ApiToken(string name, Input<string> id, ApiTokenState? state = null, CustomResourceOptions? options = null)
            : base("unleash:index/apiToken:ApiToken", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "secret",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ApiToken resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ApiToken Get(string name, Input<string> id, ApiTokenState? state = null, CustomResourceOptions? options = null)
        {
            return new ApiToken(name, id, state, options);
        }
    }

    public sealed class ApiTokenArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// An environment the token has access to.
        /// </summary>
        [Input("environment")]
        public Input<string>? Environment { get; set; }

        /// <summary>
        /// When the token expires
        /// </summary>
        [Input("expiresAt")]
        public Input<string>? ExpiresAt { get; set; }

        /// <summary>
        /// A project the token belongs to.
        /// </summary>
        [Input("project")]
        public Input<string>? Project { get; set; }

        [Input("projects")]
        private InputList<string>? _projects;

        /// <summary>
        /// The list of projects this token has access to. If the token has access to specific projects they will be listed here. If the token has access to all projects it will be represented as `[*]`.
        /// </summary>
        public InputList<string> Projects
        {
            get => _projects ?? (_projects = new InputList<string>());
            set => _projects = value;
        }

        /// <summary>
        /// The name of the token.
        /// </summary>
        [Input("tokenName")]
        public Input<string>? TokenName { get; set; }

        /// <summary>
        /// The type of the token.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public ApiTokenArgs()
        {
        }
        public static new ApiTokenArgs Empty => new ApiTokenArgs();
    }

    public sealed class ApiTokenState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// An environment the token has access to.
        /// </summary>
        [Input("environment")]
        public Input<string>? Environment { get; set; }

        /// <summary>
        /// When the token expires
        /// </summary>
        [Input("expiresAt")]
        public Input<string>? ExpiresAt { get; set; }

        /// <summary>
        /// A project the token belongs to.
        /// </summary>
        [Input("project")]
        public Input<string>? Project { get; set; }

        [Input("projects")]
        private InputList<string>? _projects;

        /// <summary>
        /// The list of projects this token has access to. If the token has access to specific projects they will be listed here. If the token has access to all projects it will be represented as `[*]`.
        /// </summary>
        public InputList<string> Projects
        {
            get => _projects ?? (_projects = new InputList<string>());
            set => _projects = value;
        }

        [Input("secret")]
        private Input<string>? _secret;

        /// <summary>
        /// Secret token value.
        /// </summary>
        public Input<string>? Secret
        {
            get => _secret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _secret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The name of the token.
        /// </summary>
        [Input("tokenName")]
        public Input<string>? TokenName { get; set; }

        /// <summary>
        /// The type of the token.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public ApiTokenState()
        {
        }
        public static new ApiTokenState Empty => new ApiTokenState();
    }
}
