// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Unleash
{
    public static class GetGroup
    {
        /// <summary>
        /// Fetch a group by id or name. The MappingsSso attribute contains external SSO/IdP group names mapped to this Unleash group.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Unleash = Pulumiverse.Unleash;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var team = Unleash.GetGroup.Invoke(new()
        ///     {
        ///         Name = "Example Team",
        ///     });
        /// 
        ///     var teamById = Unleash.GetGroup.Invoke(new()
        ///     {
        ///         Id = team.Apply(getGroupResult =&gt; getGroupResult.Id),
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetGroupResult> InvokeAsync(GetGroupArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetGroupResult>("unleash:index/getGroup:getGroup", args ?? new GetGroupArgs(), options.WithDefaults());

        /// <summary>
        /// Fetch a group by id or name. The MappingsSso attribute contains external SSO/IdP group names mapped to this Unleash group.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Unleash = Pulumiverse.Unleash;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var team = Unleash.GetGroup.Invoke(new()
        ///     {
        ///         Name = "Example Team",
        ///     });
        /// 
        ///     var teamById = Unleash.GetGroup.Invoke(new()
        ///     {
        ///         Id = team.Apply(getGroupResult =&gt; getGroupResult.Id),
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetGroupResult> Invoke(GetGroupInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetGroupResult>("unleash:index/getGroup:getGroup", args ?? new GetGroupInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Fetch a group by id or name. The MappingsSso attribute contains external SSO/IdP group names mapped to this Unleash group.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Unleash = Pulumiverse.Unleash;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var team = Unleash.GetGroup.Invoke(new()
        ///     {
        ///         Name = "Example Team",
        ///     });
        /// 
        ///     var teamById = Unleash.GetGroup.Invoke(new()
        ///     {
        ///         Id = team.Apply(getGroupResult =&gt; getGroupResult.Id),
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetGroupResult> Invoke(GetGroupInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetGroupResult>("unleash:index/getGroup:getGroup", args ?? new GetGroupInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetGroupArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Group ID to look up. If name is also provided, it must match the returned group name.
        /// </summary>
        [Input("id")]
        public string? Id { get; set; }

        /// <summary>
        /// Group name to look up. If id is also provided, the group returned by that id must have this name.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        public GetGroupArgs()
        {
        }
        public static new GetGroupArgs Empty => new GetGroupArgs();
    }

    public sealed class GetGroupInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Group ID to look up. If name is also provided, it must match the returned group name.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// Group name to look up. If id is also provided, the group returned by that id must have this name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetGroupInvokeArgs()
        {
        }
        public static new GetGroupInvokeArgs Empty => new GetGroupInvokeArgs();
    }


    [OutputType]
    public sealed class GetGroupResult
    {
        /// <summary>
        /// A description of the group's purpose.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Group ID to look up. If name is also provided, it must match the returned group name.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// External SSO/IdP group names mapped to this Unleash group.
        /// </summary>
        public readonly ImmutableArray<string> MappingsSsos;
        /// <summary>
        /// Group name to look up. If id is also provided, the group returned by that id must have this name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The root role ID for this group.
        /// </summary>
        public readonly int RootRole;
        /// <summary>
        /// List of user IDs in this group.
        /// </summary>
        public readonly ImmutableArray<int> Users;

        [OutputConstructor]
        private GetGroupResult(
            string description,

            string id,

            ImmutableArray<string> mappingsSsos,

            string name,

            int rootRole,

            ImmutableArray<int> users)
        {
            Description = description;
            Id = id;
            MappingsSsos = mappingsSsos;
            Name = name;
            RootRole = rootRole;
            Users = users;
        }
    }
}
