// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Unleash
{
    public static class GetRole
    {
        /// <summary>
        /// Fetch a role definition.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Unleash = Pulumiverse.Unleash;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var adminRole = Unleash.GetRole.Invoke(new()
        ///     {
        ///         Name = "Admin",
        ///     });
        /// 
        ///     var editorRole = Unleash.GetRole.Invoke(new()
        ///     {
        ///         Name = "Editor",
        ///     });
        /// 
        ///     var projectMemberRole = Unleash.GetRole.Invoke(new()
        ///     {
        ///         Name = "Member",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetRoleResult> InvokeAsync(GetRoleArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetRoleResult>("unleash:index/getRole:getRole", args ?? new GetRoleArgs(), options.WithDefaults());

        /// <summary>
        /// Fetch a role definition.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Unleash = Pulumiverse.Unleash;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var adminRole = Unleash.GetRole.Invoke(new()
        ///     {
        ///         Name = "Admin",
        ///     });
        /// 
        ///     var editorRole = Unleash.GetRole.Invoke(new()
        ///     {
        ///         Name = "Editor",
        ///     });
        /// 
        ///     var projectMemberRole = Unleash.GetRole.Invoke(new()
        ///     {
        ///         Name = "Member",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetRoleResult> Invoke(GetRoleInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetRoleResult>("unleash:index/getRole:getRole", args ?? new GetRoleInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Fetch a role definition.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Unleash = Pulumiverse.Unleash;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var adminRole = Unleash.GetRole.Invoke(new()
        ///     {
        ///         Name = "Admin",
        ///     });
        /// 
        ///     var editorRole = Unleash.GetRole.Invoke(new()
        ///     {
        ///         Name = "Editor",
        ///     });
        /// 
        ///     var projectMemberRole = Unleash.GetRole.Invoke(new()
        ///     {
        ///         Name = "Member",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetRoleResult> Invoke(GetRoleInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetRoleResult>("unleash:index/getRole:getRole", args ?? new GetRoleInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRoleArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of this role.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetRoleArgs()
        {
        }
        public static new GetRoleArgs Empty => new GetRoleArgs();
    }

    public sealed class GetRoleInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of this role.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetRoleInvokeArgs()
        {
        }
        public static new GetRoleInvokeArgs Empty => new GetRoleInvokeArgs();
    }


    [OutputType]
    public sealed class GetRoleResult
    {
        /// <summary>
        /// A more detailed description of the role and what use it's intended for.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The id of this role.
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// The name of this role.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// A role can either be a global root role (applies to all roles) or a role role.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private GetRoleResult(
            string description,

            int id,

            string name,

            string type)
        {
            Description = description;
            Id = id;
            Name = name;
            Type = type;
        }
    }
}
