// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Unleash
{
    /// <summary>
    /// Manages OIDC configuration.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Unleash = Pulumiverse.Unleash;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var simpleOidcConfig = new Unleash.Oidc("simple_oidc_config", new()
    ///     {
    ///         Enabled = true,
    ///         DiscoverUrl = "http://mock-openid-server:9000/.well-known/openid-configuration",
    ///         Secret = "kinda-sorta-secret",
    ///         ClientId = "client-id",
    ///         AutoCreate = true,
    ///         DefaultRootRole = 1,
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [UnleashResourceType("unleash:index/oidc:Oidc")]
    public partial class Oidc : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether to auto create users when they login to Unleash for the first time.
        /// </summary>
        [Output("autoCreate")]
        public Output<bool> AutoCreate { get; private set; } = null!;

        /// <summary>
        /// The OIDC public identifier.
        /// </summary>
        [Output("clientId")]
        public Output<string> ClientId { get; private set; } = null!;

        /// <summary>
        /// The default root role give to a user when that user is created. Only used if AutoCreate is set to true.
        /// </summary>
        [Output("defaultRootRole")]
        public Output<int> DefaultRootRole { get; private set; } = null!;

        /// <summary>
        /// A URL pointing to the .well-known configuration of the OIDC provider.
        /// </summary>
        [Output("discoverUrl")]
        public Output<string> DiscoverUrl { get; private set; } = null!;

        /// <summary>
        /// Whether or not OIDC is enabled.
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        /// <summary>
        /// The OIDC secret.
        /// </summary>
        [Output("secret")]
        public Output<string> Secret { get; private set; } = null!;


        /// <summary>
        /// Create a Oidc resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Oidc(string name, OidcArgs args, CustomResourceOptions? options = null)
            : base("unleash:index/oidc:Oidc", name, args ?? new OidcArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Oidc(string name, Input<string> id, OidcState? state = null, CustomResourceOptions? options = null)
            : base("unleash:index/oidc:Oidc", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Oidc resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Oidc Get(string name, Input<string> id, OidcState? state = null, CustomResourceOptions? options = null)
        {
            return new Oidc(name, id, state, options);
        }
    }

    public sealed class OidcArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to auto create users when they login to Unleash for the first time.
        /// </summary>
        [Input("autoCreate")]
        public Input<bool>? AutoCreate { get; set; }

        /// <summary>
        /// The OIDC public identifier.
        /// </summary>
        [Input("clientId", required: true)]
        public Input<string> ClientId { get; set; } = null!;

        /// <summary>
        /// The default root role give to a user when that user is created. Only used if AutoCreate is set to true.
        /// </summary>
        [Input("defaultRootRole")]
        public Input<int>? DefaultRootRole { get; set; }

        /// <summary>
        /// A URL pointing to the .well-known configuration of the OIDC provider.
        /// </summary>
        [Input("discoverUrl", required: true)]
        public Input<string> DiscoverUrl { get; set; } = null!;

        /// <summary>
        /// Whether or not OIDC is enabled.
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// The OIDC secret.
        /// </summary>
        [Input("secret", required: true)]
        public Input<string> Secret { get; set; } = null!;

        public OidcArgs()
        {
        }
        public static new OidcArgs Empty => new OidcArgs();
    }

    public sealed class OidcState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to auto create users when they login to Unleash for the first time.
        /// </summary>
        [Input("autoCreate")]
        public Input<bool>? AutoCreate { get; set; }

        /// <summary>
        /// The OIDC public identifier.
        /// </summary>
        [Input("clientId")]
        public Input<string>? ClientId { get; set; }

        /// <summary>
        /// The default root role give to a user when that user is created. Only used if AutoCreate is set to true.
        /// </summary>
        [Input("defaultRootRole")]
        public Input<int>? DefaultRootRole { get; set; }

        /// <summary>
        /// A URL pointing to the .well-known configuration of the OIDC provider.
        /// </summary>
        [Input("discoverUrl")]
        public Input<string>? DiscoverUrl { get; set; }

        /// <summary>
        /// Whether or not OIDC is enabled.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// The OIDC secret.
        /// </summary>
        [Input("secret")]
        public Input<string>? Secret { get; set; }

        public OidcState()
        {
        }
        public static new OidcState Empty => new OidcState();
    }
}
