// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Unleash
{
    /// <summary>
    /// Project schema
    /// </summary>
    [UnleashResourceType("unleash:index/project:Project")]
    public partial class Project : global::Pulumi.CustomResource
    {
        /// <summary>
        /// A description of the project's purpose.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Optional feature naming pattern applied to all features created in this project.
        /// </summary>
        [Output("featureNaming")]
        public Output<Outputs.ProjectFeatureNaming?> FeatureNaming { get; private set; } = null!;

        /// <summary>
        /// Optional list of link templates automatically added to new feature flags.
        /// </summary>
        [Output("linkTemplates")]
        public Output<ImmutableArray<Outputs.ProjectLinkTemplate>> LinkTemplates { get; private set; } = null!;

        /// <summary>
        /// The project's collaboration mode. Determines whether non project members can submit change requests and the projects visibility to non members. Valid values are 'open', 'protected' and 'private'. If a value is not set, the project will default to 'open'
        /// </summary>
        [Output("mode")]
        public Output<string> Mode { get; private set; } = null!;

        /// <summary>
        /// The name of the project.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Identifier for this project.
        /// </summary>
        [Output("projectId")]
        public Output<string> ProjectId { get; private set; } = null!;


        /// <summary>
        /// Create a Project resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Project(string name, ProjectArgs args, CustomResourceOptions? options = null)
            : base("unleash:index/project:Project", name, args ?? new ProjectArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Project(string name, Input<string> id, ProjectState? state = null, CustomResourceOptions? options = null)
            : base("unleash:index/project:Project", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Project resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Project Get(string name, Input<string> id, ProjectState? state = null, CustomResourceOptions? options = null)
        {
            return new Project(name, id, state, options);
        }
    }

    public sealed class ProjectArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A description of the project's purpose.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Optional feature naming pattern applied to all features created in this project.
        /// </summary>
        [Input("featureNaming")]
        public Input<Inputs.ProjectFeatureNamingArgs>? FeatureNaming { get; set; }

        [Input("linkTemplates")]
        private InputList<Inputs.ProjectLinkTemplateArgs>? _linkTemplates;

        /// <summary>
        /// Optional list of link templates automatically added to new feature flags.
        /// </summary>
        public InputList<Inputs.ProjectLinkTemplateArgs> LinkTemplates
        {
            get => _linkTemplates ?? (_linkTemplates = new InputList<Inputs.ProjectLinkTemplateArgs>());
            set => _linkTemplates = value;
        }

        /// <summary>
        /// The project's collaboration mode. Determines whether non project members can submit change requests and the projects visibility to non members. Valid values are 'open', 'protected' and 'private'. If a value is not set, the project will default to 'open'
        /// </summary>
        [Input("mode")]
        public Input<string>? Mode { get; set; }

        /// <summary>
        /// The name of the project.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Identifier for this project.
        /// </summary>
        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        public ProjectArgs()
        {
        }
        public static new ProjectArgs Empty => new ProjectArgs();
    }

    public sealed class ProjectState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A description of the project's purpose.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Optional feature naming pattern applied to all features created in this project.
        /// </summary>
        [Input("featureNaming")]
        public Input<Inputs.ProjectFeatureNamingGetArgs>? FeatureNaming { get; set; }

        [Input("linkTemplates")]
        private InputList<Inputs.ProjectLinkTemplateGetArgs>? _linkTemplates;

        /// <summary>
        /// Optional list of link templates automatically added to new feature flags.
        /// </summary>
        public InputList<Inputs.ProjectLinkTemplateGetArgs> LinkTemplates
        {
            get => _linkTemplates ?? (_linkTemplates = new InputList<Inputs.ProjectLinkTemplateGetArgs>());
            set => _linkTemplates = value;
        }

        /// <summary>
        /// The project's collaboration mode. Determines whether non project members can submit change requests and the projects visibility to non members. Valid values are 'open', 'protected' and 'private'. If a value is not set, the project will default to 'open'
        /// </summary>
        [Input("mode")]
        public Input<string>? Mode { get; set; }

        /// <summary>
        /// The name of the project.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Identifier for this project.
        /// </summary>
        [Input("projectId")]
        public Input<string>? ProjectId { get; set; }

        public ProjectState()
        {
        }
        public static new ProjectState Empty => new ProjectState();
    }
}
