// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Unleash
{
    /// <summary>
    /// ProjectAccess schema
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Unleash = Pulumiverse.Unleash;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var sampleProject = new Unleash.Project("sample_project", new()
    ///     {
    ///         ProjectId = "sample",
    ///         Name = "sample-project",
    ///     });
    /// 
    ///     var projectOwnerRole = Unleash.GetRole.Invoke(new()
    ///     {
    ///         Name = "Owner",
    ///     });
    /// 
    ///     var projectMemberRole = Unleash.GetRole.Invoke(new()
    ///     {
    ///         Name = "Member",
    ///     });
    /// 
    ///     var testUser = new Unleash.User("test_user", new()
    ///     {
    ///         Name = "tester",
    ///         Email = "test-password@getunleash.io",
    ///         Password = "you-will-never-guess",
    ///         RootRole = 3,
    ///         SendEmail = false,
    ///     });
    /// 
    ///     var testUser2 = new Unleash.User("test_user_2", new()
    ///     {
    ///         Name = "tester-2",
    ///         Email = "test-2-password@getunleash.io",
    ///         Password = "you-will-never-guess",
    ///         RootRole = 3,
    ///         SendEmail = false,
    ///     });
    /// 
    ///     var sampleProjectAccess = new Unleash.ProjectAccess("sample_project_access", new()
    ///     {
    ///         Project = sampleProject.ProjectId,
    ///         Roles = new[]
    ///         {
    ///             new Unleash.Inputs.ProjectAccessRoleArgs
    ///             {
    ///                 Role = projectOwnerRole.Apply(getRoleResult =&gt; getRoleResult.Id),
    ///                 Users = new[]
    ///                 {
    ///                     testUser.Id,
    ///                 },
    ///                 Groups = new() { },
    ///             },
    ///             new Unleash.Inputs.ProjectAccessRoleArgs
    ///             {
    ///                 Role = projectMemberRole.Apply(getRoleResult =&gt; getRoleResult.Id),
    ///                 Users = new[]
    ///                 {
    ///                     testUser2.Id,
    ///                 },
    ///                 Groups = new() { },
    ///             },
    ///         },
    ///     });
    /// 
    ///     var defaultProjectAccess = new Unleash.ProjectAccess("default_project_access", new()
    ///     {
    ///         Project = "default",
    ///         Roles = new[]
    ///         {
    ///             new Unleash.Inputs.ProjectAccessRoleArgs
    ///             {
    ///                 Role = projectOwnerRole.Apply(getRoleResult =&gt; getRoleResult.Id),
    ///                 Users = new[]
    ///                 {
    ///                     testUser.Id,
    ///                 },
    ///                 Groups = new() { },
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [UnleashResourceType("unleash:index/projectAccess:ProjectAccess")]
    public partial class ProjectAccess : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Project identifier.
        /// </summary>
        [Output("project")]
        public Output<string> Project { get; private set; } = null!;

        /// <summary>
        /// Roles available in this project with their members.
        /// </summary>
        [Output("roles")]
        public Output<ImmutableArray<Outputs.ProjectAccessRole>> Roles { get; private set; } = null!;


        /// <summary>
        /// Create a ProjectAccess resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ProjectAccess(string name, ProjectAccessArgs args, CustomResourceOptions? options = null)
            : base("unleash:index/projectAccess:ProjectAccess", name, args ?? new ProjectAccessArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ProjectAccess(string name, Input<string> id, ProjectAccessState? state = null, CustomResourceOptions? options = null)
            : base("unleash:index/projectAccess:ProjectAccess", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ProjectAccess resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ProjectAccess Get(string name, Input<string> id, ProjectAccessState? state = null, CustomResourceOptions? options = null)
        {
            return new ProjectAccess(name, id, state, options);
        }
    }

    public sealed class ProjectAccessArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Project identifier.
        /// </summary>
        [Input("project", required: true)]
        public Input<string> Project { get; set; } = null!;

        [Input("roles", required: true)]
        private InputList<Inputs.ProjectAccessRoleArgs>? _roles;

        /// <summary>
        /// Roles available in this project with their members.
        /// </summary>
        public InputList<Inputs.ProjectAccessRoleArgs> Roles
        {
            get => _roles ?? (_roles = new InputList<Inputs.ProjectAccessRoleArgs>());
            set => _roles = value;
        }

        public ProjectAccessArgs()
        {
        }
        public static new ProjectAccessArgs Empty => new ProjectAccessArgs();
    }

    public sealed class ProjectAccessState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Project identifier.
        /// </summary>
        [Input("project")]
        public Input<string>? Project { get; set; }

        [Input("roles")]
        private InputList<Inputs.ProjectAccessRoleGetArgs>? _roles;

        /// <summary>
        /// Roles available in this project with their members.
        /// </summary>
        public InputList<Inputs.ProjectAccessRoleGetArgs> Roles
        {
            get => _roles ?? (_roles = new InputList<Inputs.ProjectAccessRoleGetArgs>());
            set => _roles = value;
        }

        public ProjectAccessState()
        {
        }
        public static new ProjectAccessState Empty => new ProjectAccessState();
    }
}
