// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Unleash
{
    /// <summary>
    /// ProjectEnvironment schema
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Unleash = Pulumiverse.Unleash;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var project1 = new Unleash.Project("project_1", new()
    ///     {
    ///         ProjectId = "one",
    ///         Name = "First project",
    ///         Description = "My first project",
    ///     });
    /// 
    ///     var space = new Unleash.Environment("space", new()
    ///     {
    ///         Name = "outerspace",
    ///         Type = "vacuum",
    ///     });
    /// 
    ///     var spaceEnvironment = new Unleash.ProjectEnvironment("space_environment", new()
    ///     {
    ///         ProjectId = project1.ProjectId,
    ///         EnvironmentName = space.Name,
    ///         ChangeRequestsEnabled = true,
    ///         RequiredApprovals = 2,
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [UnleashResourceType("unleash:index/projectEnvironment:ProjectEnvironment")]
    public partial class ProjectEnvironment : global::Pulumi.CustomResource
    {
        /// <summary>
        /// If change requests are required for this environment, the environment must be enabled for this to have effect.
        /// </summary>
        [Output("changeRequestsEnabled")]
        public Output<bool> ChangeRequestsEnabled { get; private set; } = null!;

        /// <summary>
        /// Environment identifier, equivalent to the environment name.
        /// </summary>
        [Output("environmentName")]
        public Output<string> EnvironmentName { get; private set; } = null!;

        /// <summary>
        /// Project identifier.
        /// </summary>
        [Output("projectId")]
        public Output<string> ProjectId { get; private set; } = null!;

        /// <summary>
        /// Number of approvals required for change requests.
        /// </summary>
        [Output("requiredApprovals")]
        public Output<int> RequiredApprovals { get; private set; } = null!;


        /// <summary>
        /// Create a ProjectEnvironment resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ProjectEnvironment(string name, ProjectEnvironmentArgs args, CustomResourceOptions? options = null)
            : base("unleash:index/projectEnvironment:ProjectEnvironment", name, args ?? new ProjectEnvironmentArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ProjectEnvironment(string name, Input<string> id, ProjectEnvironmentState? state = null, CustomResourceOptions? options = null)
            : base("unleash:index/projectEnvironment:ProjectEnvironment", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ProjectEnvironment resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ProjectEnvironment Get(string name, Input<string> id, ProjectEnvironmentState? state = null, CustomResourceOptions? options = null)
        {
            return new ProjectEnvironment(name, id, state, options);
        }
    }

    public sealed class ProjectEnvironmentArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// If change requests are required for this environment, the environment must be enabled for this to have effect.
        /// </summary>
        [Input("changeRequestsEnabled")]
        public Input<bool>? ChangeRequestsEnabled { get; set; }

        /// <summary>
        /// Environment identifier, equivalent to the environment name.
        /// </summary>
        [Input("environmentName", required: true)]
        public Input<string> EnvironmentName { get; set; } = null!;

        /// <summary>
        /// Project identifier.
        /// </summary>
        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        /// <summary>
        /// Number of approvals required for change requests.
        /// </summary>
        [Input("requiredApprovals")]
        public Input<int>? RequiredApprovals { get; set; }

        public ProjectEnvironmentArgs()
        {
        }
        public static new ProjectEnvironmentArgs Empty => new ProjectEnvironmentArgs();
    }

    public sealed class ProjectEnvironmentState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// If change requests are required for this environment, the environment must be enabled for this to have effect.
        /// </summary>
        [Input("changeRequestsEnabled")]
        public Input<bool>? ChangeRequestsEnabled { get; set; }

        /// <summary>
        /// Environment identifier, equivalent to the environment name.
        /// </summary>
        [Input("environmentName")]
        public Input<string>? EnvironmentName { get; set; }

        /// <summary>
        /// Project identifier.
        /// </summary>
        [Input("projectId")]
        public Input<string>? ProjectId { get; set; }

        /// <summary>
        /// Number of approvals required for change requests.
        /// </summary>
        [Input("requiredApprovals")]
        public Input<int>? RequiredApprovals { get; set; }

        public ProjectEnvironmentState()
        {
        }
        public static new ProjectEnvironmentState Empty => new ProjectEnvironmentState();
    }
}
