// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Unleash
{
    /// <summary>
    /// Allows for managing the tokens bound to a service account. Note that service account tokens in Unleash
    /// 		are both immutable and cannot be recovered once created. This means you must use them immediately when creating them via terraform.
    /// 		Typically by piping them to an external secret manager or binding them to some other external terraform resource that requires Unleash tokens.
    /// 
    ///         Because service account tokens are immutable, any changes to the terraform resource will trigger a deletion and recreation of those tokens,
    ///         meaning that the secrets will be rotated out.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Command = Pulumi.Command;
    /// using External = Pulumi.External;
    /// using Null = Pulumi.Null;
    /// using Unleash = Pulumi.Unleash;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var accountForTokensTest = new Unleash.ServiceAccount("account_for_tokens_test", new()
    ///     {
    ///         Name = "the service account name",
    ///         Username = "some descriptive name",
    ///         RootRole = 1,
    ///     });
    /// 
    ///     var tokenForAccountTest = new Unleash.ServiceAccountToken("token_for_account_test", new()
    ///     {
    ///         ServiceAccountId = accountForTokensTest.Id,
    ///         Description = "a token for the account",
    ///         ExpiresAt = "2048-01-01T00:00:00Z",
    ///     });
    /// 
    ///     //# This is a bare bones example to output the token to a file, this would be better off being sent to
    ///     //# a secret manager rather
    ///     var storeToken = new Null.Resource("store_token", new()
    ///     {
    ///         Triggers = 
    ///         {
    ///             { "tokenCreated", tokenForAccountTest.Secret },
    ///         },
    ///     });
    /// 
    ///     var storeTokenProvisioner0 = new Command.Local.Command("storeTokenProvisioner0", new()
    ///     {
    ///         Create = @$"      #!/bin/bash
    ///       TOKEN_VALUE=\""{tokenForAccountTest.Secret}\""
    ///       echo \""Storing token: $TOKEN_VALUE\""
    ///       echo \""$TOKEN_VALUE\"" &gt; /secure/location/service_account_token.txt
    /// ",
    ///     }, new CustomResourceOptions
    ///     {
    ///         DependsOn =
    ///         {
    ///             storeToken,
    ///         },
    ///     });
    /// 
    ///     //# Some external resource that requires an Unleash token for automation
    ///     var externalUnleashIntegration = new External.Resource("external_unleash_integration", new()
    ///     {
    ///         UnleashApiKey = tokenForAccountTest.Secret,
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [UnleashResourceType("unleash:index/serviceAccountToken:ServiceAccountToken")]
    public partial class ServiceAccountToken : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The description of the service account token.
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// The expiration date of the service account token.
        /// </summary>
        [Output("expiresAt")]
        public Output<string> ExpiresAt { get; private set; } = null!;

        /// <summary>
        /// The secret of the service account token.
        /// </summary>
        [Output("secret")]
        public Output<string> Secret { get; private set; } = null!;

        /// <summary>
        /// The ID of the service account this token is bound to.
        /// </summary>
        [Output("serviceAccountId")]
        public Output<int> ServiceAccountId { get; private set; } = null!;


        /// <summary>
        /// Create a ServiceAccountToken resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ServiceAccountToken(string name, ServiceAccountTokenArgs args, CustomResourceOptions? options = null)
            : base("unleash:index/serviceAccountToken:ServiceAccountToken", name, args ?? new ServiceAccountTokenArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ServiceAccountToken(string name, Input<string> id, ServiceAccountTokenState? state = null, CustomResourceOptions? options = null)
            : base("unleash:index/serviceAccountToken:ServiceAccountToken", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "secret",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ServiceAccountToken resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ServiceAccountToken Get(string name, Input<string> id, ServiceAccountTokenState? state = null, CustomResourceOptions? options = null)
        {
            return new ServiceAccountToken(name, id, state, options);
        }
    }

    public sealed class ServiceAccountTokenArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The description of the service account token.
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        /// <summary>
        /// The expiration date of the service account token.
        /// </summary>
        [Input("expiresAt", required: true)]
        public Input<string> ExpiresAt { get; set; } = null!;

        /// <summary>
        /// The ID of the service account this token is bound to.
        /// </summary>
        [Input("serviceAccountId", required: true)]
        public Input<int> ServiceAccountId { get; set; } = null!;

        public ServiceAccountTokenArgs()
        {
        }
        public static new ServiceAccountTokenArgs Empty => new ServiceAccountTokenArgs();
    }

    public sealed class ServiceAccountTokenState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The description of the service account token.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The expiration date of the service account token.
        /// </summary>
        [Input("expiresAt")]
        public Input<string>? ExpiresAt { get; set; }

        [Input("secret")]
        private Input<string>? _secret;

        /// <summary>
        /// The secret of the service account token.
        /// </summary>
        public Input<string>? Secret
        {
            get => _secret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _secret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The ID of the service account this token is bound to.
        /// </summary>
        [Input("serviceAccountId")]
        public Input<int>? ServiceAccountId { get; set; }

        public ServiceAccountTokenState()
        {
        }
        public static new ServiceAccountTokenState Empty => new ServiceAccountTokenState();
    }
}
