// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Unleash.Outputs
{

    [OutputType]
    public sealed class ProjectAccessRole
    {
        /// <summary>
        /// List of projects with this role assigned.
        /// </summary>
        public readonly ImmutableArray<int> Groups;
        /// <summary>
        /// The role identifier.
        /// </summary>
        public readonly int Role;
        /// <summary>
        /// List of users with this role assigned.
        /// </summary>
        public readonly ImmutableArray<int> Users;

        [OutputConstructor]
        private ProjectAccessRole(
            ImmutableArray<int> groups,

            int role,

            ImmutableArray<int> users)
        {
            Groups = groups;
            Role = role;
            Users = users;
        }
    }
}
