// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Unleash.Outputs
{

    [OutputType]
    public sealed class ProjectLinkTemplate
    {
        /// <summary>
        /// Link title shown in the Unleash UI.
        /// </summary>
        public readonly string? Title;
        /// <summary>
        /// URL template that can contain {{project}} or {{feature}} placeholders.
        /// </summary>
        public readonly string UrlTemplate;

        [OutputConstructor]
        private ProjectLinkTemplate(
            string? title,

            string urlTemplate)
        {
            Title = title;
            UrlTemplate = urlTemplate;
        }
    }
}
