// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Unleash.Outputs
{

    [OutputType]
    public sealed class ProjectFeatureNaming
    {
        /// <summary>
        /// A human-readable description of the pattern.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// An example feature name that matches the pattern.
        /// </summary>
        public readonly string? Example;
        /// <summary>
        /// A JavaScript regular expression pattern, without the start and end delimiters.
        /// </summary>
        public readonly string Pattern;

        [OutputConstructor]
        private ProjectFeatureNaming(
            string? description,

            string? example,

            string pattern)
        {
            Description = description;
            Example = example;
            Pattern = pattern;
        }
    }
}
