# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['EnvironmentArgs', 'Environment']

@pulumi.input_type
class EnvironmentArgs:
    def __init__(__self__, *,
                 type: pulumi.Input[_builtins.str],
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 required_approvals: pulumi.Input[Optional[_builtins.int]] = None):
        """
        The set of arguments for constructing a Environment resource.

        :param pulumi.Input[_builtins.str] type: The type of the environment. Unleash recognizes 'development', 'test', 'preproduction' and 'production'. You can pass other values and Unleash will accept them but they will carry no special semantics.
        :param pulumi.Input[_builtins.str] name: The name of the environment. Must be a URL-friendly string according to RFC 3968. Changing this property will require the resource to be replaced, it's generally safer to remove this resource and create a new one.
        :param pulumi.Input[_builtins.int] required_approvals: The number of approvals a change request must collect before it can be applied in this environment. Setting it turns on environment-level change requests, and every project that uses this environment inherits the value. Projects can still override it unless they have no members allowed to update the project. Leave it unset to not preconfigure change requests for this environment. Requires Unleash Enterprise 6.10 or later.
        """
        pulumi.set(__self__, "type", type)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if required_approvals is not None:
            pulumi.set(__self__, "required_approvals", required_approvals)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[_builtins.str]:
        """
        The type of the environment. Unleash recognizes 'development', 'test', 'preproduction' and 'production'. You can pass other values and Unleash will accept them but they will carry no special semantics.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the environment. Must be a URL-friendly string according to RFC 3968. Changing this property will require the resource to be replaced, it's generally safer to remove this resource and create a new one.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="requiredApprovals")
    def required_approvals(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The number of approvals a change request must collect before it can be applied in this environment. Setting it turns on environment-level change requests, and every project that uses this environment inherits the value. Projects can still override it unless they have no members allowed to update the project. Leave it unset to not preconfigure change requests for this environment. Requires Unleash Enterprise 6.10 or later.
        """
        return pulumi.get(self, "required_approvals")

    @required_approvals.setter
    def required_approvals(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "required_approvals", value)


@pulumi.input_type
class _EnvironmentState:
    def __init__(__self__, *,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 required_approvals: pulumi.Input[Optional[_builtins.int]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Environment resources.

        :param pulumi.Input[_builtins.str] name: The name of the environment. Must be a URL-friendly string according to RFC 3968. Changing this property will require the resource to be replaced, it's generally safer to remove this resource and create a new one.
        :param pulumi.Input[_builtins.int] required_approvals: The number of approvals a change request must collect before it can be applied in this environment. Setting it turns on environment-level change requests, and every project that uses this environment inherits the value. Projects can still override it unless they have no members allowed to update the project. Leave it unset to not preconfigure change requests for this environment. Requires Unleash Enterprise 6.10 or later.
        :param pulumi.Input[_builtins.str] type: The type of the environment. Unleash recognizes 'development', 'test', 'preproduction' and 'production'. You can pass other values and Unleash will accept them but they will carry no special semantics.
        """
        if name is not None:
            pulumi.set(__self__, "name", name)
        if required_approvals is not None:
            pulumi.set(__self__, "required_approvals", required_approvals)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the environment. Must be a URL-friendly string according to RFC 3968. Changing this property will require the resource to be replaced, it's generally safer to remove this resource and create a new one.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="requiredApprovals")
    def required_approvals(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The number of approvals a change request must collect before it can be applied in this environment. Setting it turns on environment-level change requests, and every project that uses this environment inherits the value. Projects can still override it unless they have no members allowed to update the project. Leave it unset to not preconfigure change requests for this environment. Requires Unleash Enterprise 6.10 or later.
        """
        return pulumi.get(self, "required_approvals")

    @required_approvals.setter
    def required_approvals(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "required_approvals", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The type of the environment. Unleash recognizes 'development', 'test', 'preproduction' and 'production'. You can pass other values and Unleash will accept them but they will carry no special semantics.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "type", value)


@pulumi.type_token("unleash:index/environment:Environment")
class Environment(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 required_approvals: pulumi.Input[Optional[_builtins.int]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Manage Unleash environments.

        ## Example Usage

        ```python
        import pulumi
        import pulumiverse_unleash as unleash

        space = unleash.Environment("space",
            name="outerspace",
            type="vacuum")
        # Preconfigure environment level change requests: every project using this
        # environment inherits the requirement of two approvals per change request.
        space_station = unleash.Environment("space_station",
            name="space-station",
            type="production",
            required_approvals=2)
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] name: The name of the environment. Must be a URL-friendly string according to RFC 3968. Changing this property will require the resource to be replaced, it's generally safer to remove this resource and create a new one.
        :param pulumi.Input[_builtins.int] required_approvals: The number of approvals a change request must collect before it can be applied in this environment. Setting it turns on environment-level change requests, and every project that uses this environment inherits the value. Projects can still override it unless they have no members allowed to update the project. Leave it unset to not preconfigure change requests for this environment. Requires Unleash Enterprise 6.10 or later.
        :param pulumi.Input[_builtins.str] type: The type of the environment. Unleash recognizes 'development', 'test', 'preproduction' and 'production'. You can pass other values and Unleash will accept them but they will carry no special semantics.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: EnvironmentArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manage Unleash environments.

        ## Example Usage

        ```python
        import pulumi
        import pulumiverse_unleash as unleash

        space = unleash.Environment("space",
            name="outerspace",
            type="vacuum")
        # Preconfigure environment level change requests: every project using this
        # environment inherits the requirement of two approvals per change request.
        space_station = unleash.Environment("space_station",
            name="space-station",
            type="production",
            required_approvals=2)
        ```


        :param str resource_name: The name of the resource.
        :param EnvironmentArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(EnvironmentArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 required_approvals: pulumi.Input[Optional[_builtins.int]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = EnvironmentArgs.__new__(EnvironmentArgs)

            __props__.__dict__["name"] = name
            __props__.__dict__["required_approvals"] = required_approvals
            if type is None and not opts.urn:
                raise TypeError("Missing required property 'type'")
            __props__.__dict__["type"] = type
        super(Environment, __self__).__init__(
            'unleash:index/environment:Environment',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            required_approvals: pulumi.Input[Optional[_builtins.int]] = None,
            type: pulumi.Input[Optional[_builtins.str]] = None) -> 'Environment':
        """
        Get an existing Environment resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] name: The name of the environment. Must be a URL-friendly string according to RFC 3968. Changing this property will require the resource to be replaced, it's generally safer to remove this resource and create a new one.
        :param pulumi.Input[_builtins.int] required_approvals: The number of approvals a change request must collect before it can be applied in this environment. Setting it turns on environment-level change requests, and every project that uses this environment inherits the value. Projects can still override it unless they have no members allowed to update the project. Leave it unset to not preconfigure change requests for this environment. Requires Unleash Enterprise 6.10 or later.
        :param pulumi.Input[_builtins.str] type: The type of the environment. Unleash recognizes 'development', 'test', 'preproduction' and 'production'. You can pass other values and Unleash will accept them but they will carry no special semantics.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _EnvironmentState.__new__(_EnvironmentState)

        __props__.__dict__["name"] = name
        __props__.__dict__["required_approvals"] = required_approvals
        __props__.__dict__["type"] = type
        return Environment(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the environment. Must be a URL-friendly string according to RFC 3968. Changing this property will require the resource to be replaced, it's generally safer to remove this resource and create a new one.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="requiredApprovals")
    def required_approvals(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        The number of approvals a change request must collect before it can be applied in this environment. Setting it turns on environment-level change requests, and every project that uses this environment inherits the value. Projects can still override it unless they have no members allowed to update the project. Leave it unset to not preconfigure change requests for this environment. Requires Unleash Enterprise 6.10 or later.
        """
        return pulumi.get(self, "required_approvals")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[_builtins.str]:
        """
        The type of the environment. Unleash recognizes 'development', 'test', 'preproduction' and 'production'. You can pass other values and Unleash will accept them but they will carry no special semantics.
        """
        return pulumi.get(self, "type")

