# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetGroupResult',
    'AwaitableGetGroupResult',
    'get_group',
    'get_group_output',
]

@pulumi.output_type
class GetGroupResult:
    """
    A collection of values returned by getGroup.
    """
    def __init__(__self__, description=None, id=None, mappings_ssos=None, name=None, root_role=None, users=None):
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if mappings_ssos and not isinstance(mappings_ssos, list):
            raise TypeError("Expected argument 'mappings_ssos' to be a list")
        pulumi.set(__self__, "mappings_ssos", mappings_ssos)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if root_role and not isinstance(root_role, int):
            raise TypeError("Expected argument 'root_role' to be a int")
        pulumi.set(__self__, "root_role", root_role)
        if users and not isinstance(users, list):
            raise TypeError("Expected argument 'users' to be a list")
        pulumi.set(__self__, "users", users)

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        A description of the group's purpose.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        Group ID to look up. If name is also provided, it must match the returned group name.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="mappingsSsos")
    def mappings_ssos(self) -> Sequence[_builtins.str]:
        """
        External SSO/IdP group names mapped to this Unleash group.
        """
        return pulumi.get(self, "mappings_ssos")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        Group name to look up. If id is also provided, the group returned by that id must have this name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="rootRole")
    def root_role(self) -> _builtins.int:
        """
        The root role ID for this group.
        """
        return pulumi.get(self, "root_role")

    @_builtins.property
    @pulumi.getter
    def users(self) -> Sequence[_builtins.int]:
        """
        List of user IDs in this group.
        """
        return pulumi.get(self, "users")


class AwaitableGetGroupResult(GetGroupResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetGroupResult(
            description=self.description,
            id=self.id,
            mappings_ssos=self.mappings_ssos,
            name=self.name,
            root_role=self.root_role,
            users=self.users)


def get_group(id: Optional[_builtins.str] = None,
              name: Optional[_builtins.str] = None,
              opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetGroupResult:
    """
    Fetch a group by id or name. The mappings_sso attribute contains external SSO/IdP group names mapped to this Unleash group.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_unleash as unleash

    team = unleash.get_group(name="Example Team")
    team_by_id = unleash.get_group(id=team.id)
    ```


    :param _builtins.str id: Group ID to look up. If name is also provided, it must match the returned group name.
    :param _builtins.str name: Group name to look up. If id is also provided, the group returned by that id must have this name.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('unleash:index/getGroup:getGroup', __args__, opts=opts, typ=GetGroupResult).value

    return AwaitableGetGroupResult(
        description=pulumi.get(__ret__, 'description'),
        id=pulumi.get(__ret__, 'id'),
        mappings_ssos=pulumi.get(__ret__, 'mappings_ssos'),
        name=pulumi.get(__ret__, 'name'),
        root_role=pulumi.get(__ret__, 'root_role'),
        users=pulumi.get(__ret__, 'users'))
def get_group_output(id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                     name: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                     opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetGroupResult]:
    """
    Fetch a group by id or name. The mappings_sso attribute contains external SSO/IdP group names mapped to this Unleash group.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_unleash as unleash

    team = unleash.get_group(name="Example Team")
    team_by_id = unleash.get_group(id=team.id)
    ```


    :param _builtins.str id: Group ID to look up. If name is also provided, it must match the returned group name.
    :param _builtins.str name: Group name to look up. If id is also provided, the group returned by that id must have this name.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('unleash:index/getGroup:getGroup', __args__, opts=opts, typ=GetGroupResult)
    return __ret__.apply(lambda __response__: GetGroupResult(
        description=pulumi.get(__response__, 'description'),
        id=pulumi.get(__response__, 'id'),
        mappings_ssos=pulumi.get(__response__, 'mappings_ssos'),
        name=pulumi.get(__response__, 'name'),
        root_role=pulumi.get(__response__, 'root_role'),
        users=pulumi.get(__response__, 'users')))
