# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetUserResult',
    'AwaitableGetUserResult',
    'get_user',
    'get_user_output',
]

@pulumi.output_type
class GetUserResult:
    """
    A collection of values returned by getUser.
    """
    def __init__(__self__, email=None, id=None, name=None, root_role=None, username=None):
        if email and not isinstance(email, str):
            raise TypeError("Expected argument 'email' to be a str")
        pulumi.set(__self__, "email", email)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if root_role and not isinstance(root_role, int):
            raise TypeError("Expected argument 'root_role' to be a int")
        pulumi.set(__self__, "root_role", root_role)
        if username and not isinstance(username, str):
            raise TypeError("Expected argument 'username' to be a str")
        pulumi.set(__self__, "username", username)

    @_builtins.property
    @pulumi.getter
    def email(self) -> _builtins.str:
        """
        The email of the user.
        """
        return pulumi.get(self, "email")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        Identifier for this user.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the user.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="rootRole")
    def root_role(self) -> _builtins.int:
        """
        The role id for the user.
        """
        return pulumi.get(self, "root_role")

    @_builtins.property
    @pulumi.getter
    def username(self) -> _builtins.str:
        """
        The username of the user.
        """
        return pulumi.get(self, "username")


class AwaitableGetUserResult(GetUserResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetUserResult(
            email=self.email,
            id=self.id,
            name=self.name,
            root_role=self.root_role,
            username=self.username)


def get_user(email: Optional[_builtins.str] = None,
             id: Optional[_builtins.str] = None,
             name: Optional[_builtins.str] = None,
             username: Optional[_builtins.str] = None,
             opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetUserResult:
    """
    Fetch a user by id or email.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_unleash as unleash

    admin = unleash.get_user(id="1")
    search_by_email = unleash.get_user(email="byemail@example.com")
    ```


    :param _builtins.str email: The email of the user.
    :param _builtins.str id: Identifier for this user.
    :param _builtins.str name: The name of the user.
    :param _builtins.str username: The username of the user.
    """
    __args__ = dict()
    __args__['email'] = email
    __args__['id'] = id
    __args__['name'] = name
    __args__['username'] = username
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('unleash:index/getUser:getUser', __args__, opts=opts, typ=GetUserResult).value

    return AwaitableGetUserResult(
        email=pulumi.get(__ret__, 'email'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        root_role=pulumi.get(__ret__, 'root_role'),
        username=pulumi.get(__ret__, 'username'))
def get_user_output(email: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                    id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                    name: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                    username: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetUserResult]:
    """
    Fetch a user by id or email.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_unleash as unleash

    admin = unleash.get_user(id="1")
    search_by_email = unleash.get_user(email="byemail@example.com")
    ```


    :param _builtins.str email: The email of the user.
    :param _builtins.str id: Identifier for this user.
    :param _builtins.str name: The name of the user.
    :param _builtins.str username: The username of the user.
    """
    __args__ = dict()
    __args__['email'] = email
    __args__['id'] = id
    __args__['name'] = name
    __args__['username'] = username
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('unleash:index/getUser:getUser', __args__, opts=opts, typ=GetUserResult)
    return __ret__.apply(lambda __response__: GetUserResult(
        email=pulumi.get(__response__, 'email'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        root_role=pulumi.get(__response__, 'root_role'),
        username=pulumi.get(__response__, 'username')))
