# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ProjectArgs', 'Project']

@pulumi.input_type
class ProjectArgs:
    def __init__(__self__, *,
                 project_id: pulumi.Input[_builtins.str],
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 feature_naming: pulumi.Input[Optional['ProjectFeatureNamingArgs']] = None,
                 link_templates: pulumi.Input[Optional[Sequence[pulumi.Input['ProjectLinkTemplateArgs']]]] = None,
                 mode: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Project resource.

        :param pulumi.Input[_builtins.str] project_id: Identifier for this project.
        :param pulumi.Input[_builtins.str] description: A description of the project's purpose.
        :param pulumi.Input['ProjectFeatureNamingArgs'] feature_naming: Optional feature naming pattern applied to all features created in this project.
        :param pulumi.Input[Sequence[pulumi.Input['ProjectLinkTemplateArgs']]] link_templates: Optional list of link templates automatically added to new feature flags.
        :param pulumi.Input[_builtins.str] mode: The project's collaboration mode. Determines whether non project members can submit change requests and the projects visibility to non members. Valid values are 'open', 'protected' and 'private'. If a value is not set, the project will default to 'open'
        :param pulumi.Input[_builtins.str] name: The name of the project.
        """
        pulumi.set(__self__, "project_id", project_id)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if feature_naming is not None:
            pulumi.set(__self__, "feature_naming", feature_naming)
        if link_templates is not None:
            pulumi.set(__self__, "link_templates", link_templates)
        if mode is not None:
            pulumi.set(__self__, "mode", mode)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[_builtins.str]:
        """
        Identifier for this project.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A description of the project's purpose.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="featureNaming")
    def feature_naming(self) -> pulumi.Input[Optional['ProjectFeatureNamingArgs']]:
        """
        Optional feature naming pattern applied to all features created in this project.
        """
        return pulumi.get(self, "feature_naming")

    @feature_naming.setter
    def feature_naming(self, value: pulumi.Input[Optional['ProjectFeatureNamingArgs']]):
        pulumi.set(self, "feature_naming", value)

    @_builtins.property
    @pulumi.getter(name="linkTemplates")
    def link_templates(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['ProjectLinkTemplateArgs']]]]:
        """
        Optional list of link templates automatically added to new feature flags.
        """
        return pulumi.get(self, "link_templates")

    @link_templates.setter
    def link_templates(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['ProjectLinkTemplateArgs']]]]):
        pulumi.set(self, "link_templates", value)

    @_builtins.property
    @pulumi.getter
    def mode(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The project's collaboration mode. Determines whether non project members can submit change requests and the projects visibility to non members. Valid values are 'open', 'protected' and 'private'. If a value is not set, the project will default to 'open'
        """
        return pulumi.get(self, "mode")

    @mode.setter
    def mode(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "mode", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the project.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)


@pulumi.input_type
class _ProjectState:
    def __init__(__self__, *,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 feature_naming: pulumi.Input[Optional['ProjectFeatureNamingArgs']] = None,
                 link_templates: pulumi.Input[Optional[Sequence[pulumi.Input['ProjectLinkTemplateArgs']]]] = None,
                 mode: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Project resources.

        :param pulumi.Input[_builtins.str] description: A description of the project's purpose.
        :param pulumi.Input['ProjectFeatureNamingArgs'] feature_naming: Optional feature naming pattern applied to all features created in this project.
        :param pulumi.Input[Sequence[pulumi.Input['ProjectLinkTemplateArgs']]] link_templates: Optional list of link templates automatically added to new feature flags.
        :param pulumi.Input[_builtins.str] mode: The project's collaboration mode. Determines whether non project members can submit change requests and the projects visibility to non members. Valid values are 'open', 'protected' and 'private'. If a value is not set, the project will default to 'open'
        :param pulumi.Input[_builtins.str] name: The name of the project.
        :param pulumi.Input[_builtins.str] project_id: Identifier for this project.
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if feature_naming is not None:
            pulumi.set(__self__, "feature_naming", feature_naming)
        if link_templates is not None:
            pulumi.set(__self__, "link_templates", link_templates)
        if mode is not None:
            pulumi.set(__self__, "mode", mode)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if project_id is not None:
            pulumi.set(__self__, "project_id", project_id)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A description of the project's purpose.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="featureNaming")
    def feature_naming(self) -> pulumi.Input[Optional['ProjectFeatureNamingArgs']]:
        """
        Optional feature naming pattern applied to all features created in this project.
        """
        return pulumi.get(self, "feature_naming")

    @feature_naming.setter
    def feature_naming(self, value: pulumi.Input[Optional['ProjectFeatureNamingArgs']]):
        pulumi.set(self, "feature_naming", value)

    @_builtins.property
    @pulumi.getter(name="linkTemplates")
    def link_templates(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['ProjectLinkTemplateArgs']]]]:
        """
        Optional list of link templates automatically added to new feature flags.
        """
        return pulumi.get(self, "link_templates")

    @link_templates.setter
    def link_templates(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['ProjectLinkTemplateArgs']]]]):
        pulumi.set(self, "link_templates", value)

    @_builtins.property
    @pulumi.getter
    def mode(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The project's collaboration mode. Determines whether non project members can submit change requests and the projects visibility to non members. Valid values are 'open', 'protected' and 'private'. If a value is not set, the project will default to 'open'
        """
        return pulumi.get(self, "mode")

    @mode.setter
    def mode(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "mode", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the project.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Identifier for this project.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project_id", value)


@pulumi.type_token("unleash:index/project:Project")
class Project(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 feature_naming: pulumi.Input[Optional[Union['ProjectFeatureNamingArgs', 'ProjectFeatureNamingArgsDict']]] = None,
                 link_templates: pulumi.Input[Optional[Sequence[pulumi.Input[Union['ProjectLinkTemplateArgs', 'ProjectLinkTemplateArgsDict']]]]] = None,
                 mode: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Project schema


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: A description of the project's purpose.
        :param pulumi.Input[Union['ProjectFeatureNamingArgs', 'ProjectFeatureNamingArgsDict']] feature_naming: Optional feature naming pattern applied to all features created in this project.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ProjectLinkTemplateArgs', 'ProjectLinkTemplateArgsDict']]]] link_templates: Optional list of link templates automatically added to new feature flags.
        :param pulumi.Input[_builtins.str] mode: The project's collaboration mode. Determines whether non project members can submit change requests and the projects visibility to non members. Valid values are 'open', 'protected' and 'private'. If a value is not set, the project will default to 'open'
        :param pulumi.Input[_builtins.str] name: The name of the project.
        :param pulumi.Input[_builtins.str] project_id: Identifier for this project.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ProjectArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Project schema


        :param str resource_name: The name of the resource.
        :param ProjectArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProjectArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 feature_naming: pulumi.Input[Optional[Union['ProjectFeatureNamingArgs', 'ProjectFeatureNamingArgsDict']]] = None,
                 link_templates: pulumi.Input[Optional[Sequence[pulumi.Input[Union['ProjectLinkTemplateArgs', 'ProjectLinkTemplateArgsDict']]]]] = None,
                 mode: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProjectArgs.__new__(ProjectArgs)

            __props__.__dict__["description"] = description
            __props__.__dict__["feature_naming"] = feature_naming
            __props__.__dict__["link_templates"] = link_templates
            __props__.__dict__["mode"] = mode
            __props__.__dict__["name"] = name
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
        super(Project, __self__).__init__(
            'unleash:index/project:Project',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            feature_naming: pulumi.Input[Optional[Union['ProjectFeatureNamingArgs', 'ProjectFeatureNamingArgsDict']]] = None,
            link_templates: pulumi.Input[Optional[Sequence[pulumi.Input[Union['ProjectLinkTemplateArgs', 'ProjectLinkTemplateArgsDict']]]]] = None,
            mode: pulumi.Input[Optional[_builtins.str]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            project_id: pulumi.Input[Optional[_builtins.str]] = None) -> 'Project':
        """
        Get an existing Project resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: A description of the project's purpose.
        :param pulumi.Input[Union['ProjectFeatureNamingArgs', 'ProjectFeatureNamingArgsDict']] feature_naming: Optional feature naming pattern applied to all features created in this project.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ProjectLinkTemplateArgs', 'ProjectLinkTemplateArgsDict']]]] link_templates: Optional list of link templates automatically added to new feature flags.
        :param pulumi.Input[_builtins.str] mode: The project's collaboration mode. Determines whether non project members can submit change requests and the projects visibility to non members. Valid values are 'open', 'protected' and 'private'. If a value is not set, the project will default to 'open'
        :param pulumi.Input[_builtins.str] name: The name of the project.
        :param pulumi.Input[_builtins.str] project_id: Identifier for this project.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ProjectState.__new__(_ProjectState)

        __props__.__dict__["description"] = description
        __props__.__dict__["feature_naming"] = feature_naming
        __props__.__dict__["link_templates"] = link_templates
        __props__.__dict__["mode"] = mode
        __props__.__dict__["name"] = name
        __props__.__dict__["project_id"] = project_id
        return Project(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        A description of the project's purpose.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="featureNaming")
    def feature_naming(self) -> pulumi.Output[Optional['outputs.ProjectFeatureNaming']]:
        """
        Optional feature naming pattern applied to all features created in this project.
        """
        return pulumi.get(self, "feature_naming")

    @_builtins.property
    @pulumi.getter(name="linkTemplates")
    def link_templates(self) -> pulumi.Output[Optional[Sequence['outputs.ProjectLinkTemplate']]]:
        """
        Optional list of link templates automatically added to new feature flags.
        """
        return pulumi.get(self, "link_templates")

    @_builtins.property
    @pulumi.getter
    def mode(self) -> pulumi.Output[_builtins.str]:
        """
        The project's collaboration mode. Determines whether non project members can submit change requests and the projects visibility to non members. Valid values are 'open', 'protected' and 'private'. If a value is not set, the project will default to 'open'
        """
        return pulumi.get(self, "mode")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the project.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[_builtins.str]:
        """
        Identifier for this project.
        """
        return pulumi.get(self, "project_id")

