# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['SamlArgs', 'Saml']

@pulumi.input_type
class SamlArgs:
    def __init__(__self__, *,
                 certificate: pulumi.Input[_builtins.str],
                 enabled: pulumi.Input[_builtins.bool],
                 entity_id: pulumi.Input[_builtins.str],
                 sign_on_url: pulumi.Input[_builtins.str],
                 auto_create: pulumi.Input[Optional[_builtins.bool]] = None,
                 default_root_role: pulumi.Input[Optional[_builtins.int]] = None):
        """
        The set of arguments for constructing a Saml resource.

        :param pulumi.Input[_builtins.str] certificate: The x509 certificate used by the SAML provider.
        :param pulumi.Input[_builtins.bool] enabled: Whether SAML is enabled.
        :param pulumi.Input[_builtins.str] entity_id: The SAML entity ID.
        :param pulumi.Input[_builtins.str] sign_on_url: The SAML sign-on URL.
        :param pulumi.Input[_builtins.bool] auto_create: Whether to auto create users when they login to Unleash for the first time.
        :param pulumi.Input[_builtins.int] default_root_role: The default root role give to a user when that user is created. Only used if auto_create is set to true.
        """
        pulumi.set(__self__, "certificate", certificate)
        pulumi.set(__self__, "enabled", enabled)
        pulumi.set(__self__, "entity_id", entity_id)
        pulumi.set(__self__, "sign_on_url", sign_on_url)
        if auto_create is not None:
            pulumi.set(__self__, "auto_create", auto_create)
        if default_root_role is not None:
            pulumi.set(__self__, "default_root_role", default_root_role)

    @_builtins.property
    @pulumi.getter
    def certificate(self) -> pulumi.Input[_builtins.str]:
        """
        The x509 certificate used by the SAML provider.
        """
        return pulumi.get(self, "certificate")

    @certificate.setter
    def certificate(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "certificate", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[_builtins.bool]:
        """
        Whether SAML is enabled.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[_builtins.bool]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="entityId")
    def entity_id(self) -> pulumi.Input[_builtins.str]:
        """
        The SAML entity ID.
        """
        return pulumi.get(self, "entity_id")

    @entity_id.setter
    def entity_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "entity_id", value)

    @_builtins.property
    @pulumi.getter(name="signOnUrl")
    def sign_on_url(self) -> pulumi.Input[_builtins.str]:
        """
        The SAML sign-on URL.
        """
        return pulumi.get(self, "sign_on_url")

    @sign_on_url.setter
    def sign_on_url(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "sign_on_url", value)

    @_builtins.property
    @pulumi.getter(name="autoCreate")
    def auto_create(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to auto create users when they login to Unleash for the first time.
        """
        return pulumi.get(self, "auto_create")

    @auto_create.setter
    def auto_create(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "auto_create", value)

    @_builtins.property
    @pulumi.getter(name="defaultRootRole")
    def default_root_role(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The default root role give to a user when that user is created. Only used if auto_create is set to true.
        """
        return pulumi.get(self, "default_root_role")

    @default_root_role.setter
    def default_root_role(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "default_root_role", value)


@pulumi.input_type
class _SamlState:
    def __init__(__self__, *,
                 auto_create: pulumi.Input[Optional[_builtins.bool]] = None,
                 certificate: pulumi.Input[Optional[_builtins.str]] = None,
                 default_root_role: pulumi.Input[Optional[_builtins.int]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 entity_id: pulumi.Input[Optional[_builtins.str]] = None,
                 sign_on_url: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Saml resources.

        :param pulumi.Input[_builtins.bool] auto_create: Whether to auto create users when they login to Unleash for the first time.
        :param pulumi.Input[_builtins.str] certificate: The x509 certificate used by the SAML provider.
        :param pulumi.Input[_builtins.int] default_root_role: The default root role give to a user when that user is created. Only used if auto_create is set to true.
        :param pulumi.Input[_builtins.bool] enabled: Whether SAML is enabled.
        :param pulumi.Input[_builtins.str] entity_id: The SAML entity ID.
        :param pulumi.Input[_builtins.str] sign_on_url: The SAML sign-on URL.
        """
        if auto_create is not None:
            pulumi.set(__self__, "auto_create", auto_create)
        if certificate is not None:
            pulumi.set(__self__, "certificate", certificate)
        if default_root_role is not None:
            pulumi.set(__self__, "default_root_role", default_root_role)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if entity_id is not None:
            pulumi.set(__self__, "entity_id", entity_id)
        if sign_on_url is not None:
            pulumi.set(__self__, "sign_on_url", sign_on_url)

    @_builtins.property
    @pulumi.getter(name="autoCreate")
    def auto_create(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to auto create users when they login to Unleash for the first time.
        """
        return pulumi.get(self, "auto_create")

    @auto_create.setter
    def auto_create(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "auto_create", value)

    @_builtins.property
    @pulumi.getter
    def certificate(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The x509 certificate used by the SAML provider.
        """
        return pulumi.get(self, "certificate")

    @certificate.setter
    def certificate(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "certificate", value)

    @_builtins.property
    @pulumi.getter(name="defaultRootRole")
    def default_root_role(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The default root role give to a user when that user is created. Only used if auto_create is set to true.
        """
        return pulumi.get(self, "default_root_role")

    @default_root_role.setter
    def default_root_role(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "default_root_role", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether SAML is enabled.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="entityId")
    def entity_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The SAML entity ID.
        """
        return pulumi.get(self, "entity_id")

    @entity_id.setter
    def entity_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "entity_id", value)

    @_builtins.property
    @pulumi.getter(name="signOnUrl")
    def sign_on_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The SAML sign-on URL.
        """
        return pulumi.get(self, "sign_on_url")

    @sign_on_url.setter
    def sign_on_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "sign_on_url", value)


@pulumi.type_token("unleash:index/saml:Saml")
class Saml(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auto_create: pulumi.Input[Optional[_builtins.bool]] = None,
                 certificate: pulumi.Input[Optional[_builtins.str]] = None,
                 default_root_role: pulumi.Input[Optional[_builtins.int]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 entity_id: pulumi.Input[Optional[_builtins.str]] = None,
                 sign_on_url: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Manages SAML configuration.

        ## Example Usage

        ```python
        import pulumi
        import pulumiverse_unleash as unleash

        simple_saml_config = unleash.Saml("simple_saml_config",
            enabled=True,
            certificate="test-certificate",
            entity_id="some-entity-id",
            sign_on_url="http://other-places.com",
            auto_create=True,
            default_root_role=1)
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] auto_create: Whether to auto create users when they login to Unleash for the first time.
        :param pulumi.Input[_builtins.str] certificate: The x509 certificate used by the SAML provider.
        :param pulumi.Input[_builtins.int] default_root_role: The default root role give to a user when that user is created. Only used if auto_create is set to true.
        :param pulumi.Input[_builtins.bool] enabled: Whether SAML is enabled.
        :param pulumi.Input[_builtins.str] entity_id: The SAML entity ID.
        :param pulumi.Input[_builtins.str] sign_on_url: The SAML sign-on URL.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SamlArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages SAML configuration.

        ## Example Usage

        ```python
        import pulumi
        import pulumiverse_unleash as unleash

        simple_saml_config = unleash.Saml("simple_saml_config",
            enabled=True,
            certificate="test-certificate",
            entity_id="some-entity-id",
            sign_on_url="http://other-places.com",
            auto_create=True,
            default_root_role=1)
        ```


        :param str resource_name: The name of the resource.
        :param SamlArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SamlArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auto_create: pulumi.Input[Optional[_builtins.bool]] = None,
                 certificate: pulumi.Input[Optional[_builtins.str]] = None,
                 default_root_role: pulumi.Input[Optional[_builtins.int]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 entity_id: pulumi.Input[Optional[_builtins.str]] = None,
                 sign_on_url: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SamlArgs.__new__(SamlArgs)

            __props__.__dict__["auto_create"] = auto_create
            if certificate is None and not opts.urn:
                raise TypeError("Missing required property 'certificate'")
            __props__.__dict__["certificate"] = certificate
            __props__.__dict__["default_root_role"] = default_root_role
            if enabled is None and not opts.urn:
                raise TypeError("Missing required property 'enabled'")
            __props__.__dict__["enabled"] = enabled
            if entity_id is None and not opts.urn:
                raise TypeError("Missing required property 'entity_id'")
            __props__.__dict__["entity_id"] = entity_id
            if sign_on_url is None and not opts.urn:
                raise TypeError("Missing required property 'sign_on_url'")
            __props__.__dict__["sign_on_url"] = sign_on_url
        super(Saml, __self__).__init__(
            'unleash:index/saml:Saml',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            auto_create: pulumi.Input[Optional[_builtins.bool]] = None,
            certificate: pulumi.Input[Optional[_builtins.str]] = None,
            default_root_role: pulumi.Input[Optional[_builtins.int]] = None,
            enabled: pulumi.Input[Optional[_builtins.bool]] = None,
            entity_id: pulumi.Input[Optional[_builtins.str]] = None,
            sign_on_url: pulumi.Input[Optional[_builtins.str]] = None) -> 'Saml':
        """
        Get an existing Saml resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] auto_create: Whether to auto create users when they login to Unleash for the first time.
        :param pulumi.Input[_builtins.str] certificate: The x509 certificate used by the SAML provider.
        :param pulumi.Input[_builtins.int] default_root_role: The default root role give to a user when that user is created. Only used if auto_create is set to true.
        :param pulumi.Input[_builtins.bool] enabled: Whether SAML is enabled.
        :param pulumi.Input[_builtins.str] entity_id: The SAML entity ID.
        :param pulumi.Input[_builtins.str] sign_on_url: The SAML sign-on URL.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SamlState.__new__(_SamlState)

        __props__.__dict__["auto_create"] = auto_create
        __props__.__dict__["certificate"] = certificate
        __props__.__dict__["default_root_role"] = default_root_role
        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["entity_id"] = entity_id
        __props__.__dict__["sign_on_url"] = sign_on_url
        return Saml(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="autoCreate")
    def auto_create(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether to auto create users when they login to Unleash for the first time.
        """
        return pulumi.get(self, "auto_create")

    @_builtins.property
    @pulumi.getter
    def certificate(self) -> pulumi.Output[_builtins.str]:
        """
        The x509 certificate used by the SAML provider.
        """
        return pulumi.get(self, "certificate")

    @_builtins.property
    @pulumi.getter(name="defaultRootRole")
    def default_root_role(self) -> pulumi.Output[_builtins.int]:
        """
        The default root role give to a user when that user is created. Only used if auto_create is set to true.
        """
        return pulumi.get(self, "default_root_role")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether SAML is enabled.
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="entityId")
    def entity_id(self) -> pulumi.Output[_builtins.str]:
        """
        The SAML entity ID.
        """
        return pulumi.get(self, "entity_id")

    @_builtins.property
    @pulumi.getter(name="signOnUrl")
    def sign_on_url(self) -> pulumi.Output[_builtins.str]:
        """
        The SAML sign-on URL.
        """
        return pulumi.get(self, "sign_on_url")

