# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ServiceAccountArgs', 'ServiceAccount']

@pulumi.input_type
class ServiceAccountArgs:
    def __init__(__self__, *,
                 root_role: pulumi.Input[_builtins.int],
                 username: pulumi.Input[_builtins.str],
                 name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a ServiceAccount resource.

        :param pulumi.Input[_builtins.int] root_role: The root role ID for the service account.
        :param pulumi.Input[_builtins.str] username: The username for the service account.
        :param pulumi.Input[_builtins.str] name: The name of the service account.
        """
        pulumi.set(__self__, "root_role", root_role)
        pulumi.set(__self__, "username", username)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter(name="rootRole")
    def root_role(self) -> pulumi.Input[_builtins.int]:
        """
        The root role ID for the service account.
        """
        return pulumi.get(self, "root_role")

    @root_role.setter
    def root_role(self, value: pulumi.Input[_builtins.int]):
        pulumi.set(self, "root_role", value)

    @_builtins.property
    @pulumi.getter
    def username(self) -> pulumi.Input[_builtins.str]:
        """
        The username for the service account.
        """
        return pulumi.get(self, "username")

    @username.setter
    def username(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "username", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the service account.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)


@pulumi.input_type
class _ServiceAccountState:
    def __init__(__self__, *,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 root_role: pulumi.Input[Optional[_builtins.int]] = None,
                 username: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering ServiceAccount resources.

        :param pulumi.Input[_builtins.str] name: The name of the service account.
        :param pulumi.Input[_builtins.int] root_role: The root role ID for the service account.
        :param pulumi.Input[_builtins.str] username: The username for the service account.
        """
        if name is not None:
            pulumi.set(__self__, "name", name)
        if root_role is not None:
            pulumi.set(__self__, "root_role", root_role)
        if username is not None:
            pulumi.set(__self__, "username", username)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the service account.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="rootRole")
    def root_role(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The root role ID for the service account.
        """
        return pulumi.get(self, "root_role")

    @root_role.setter
    def root_role(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "root_role", value)

    @_builtins.property
    @pulumi.getter
    def username(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The username for the service account.
        """
        return pulumi.get(self, "username")

    @username.setter
    def username(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "username", value)


@pulumi.type_token("unleash:index/serviceAccount:ServiceAccount")
class ServiceAccount(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 root_role: pulumi.Input[Optional[_builtins.int]] = None,
                 username: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Service accounts do nothing on their own, they need service account tokens to be created to do anything useful.
        		All tokens bound to a service account will take on the permissions of the root role assigned to the service account. It's strongly
        		recommended to use the Role data source to retrieve one of the built-in roles and use the id from that to set the service account
        		role id.

                See the [Unleash documentation](https://docs.getunleash.io/reference/service-accounts) for more information.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_unleash as unleash
        import pulumiverse_unleash as unleash

        admin_role = unleash.get_role(name="Admin")
        admin_service_account = unleash.ServiceAccount("admin_service_account",
            name="something unique",
            username="something unique",
            root_role=admin_role.id)
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] name: The name of the service account.
        :param pulumi.Input[_builtins.int] root_role: The root role ID for the service account.
        :param pulumi.Input[_builtins.str] username: The username for the service account.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ServiceAccountArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Service accounts do nothing on their own, they need service account tokens to be created to do anything useful.
        		All tokens bound to a service account will take on the permissions of the root role assigned to the service account. It's strongly
        		recommended to use the Role data source to retrieve one of the built-in roles and use the id from that to set the service account
        		role id.

                See the [Unleash documentation](https://docs.getunleash.io/reference/service-accounts) for more information.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_unleash as unleash
        import pulumiverse_unleash as unleash

        admin_role = unleash.get_role(name="Admin")
        admin_service_account = unleash.ServiceAccount("admin_service_account",
            name="something unique",
            username="something unique",
            root_role=admin_role.id)
        ```


        :param str resource_name: The name of the resource.
        :param ServiceAccountArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ServiceAccountArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 root_role: pulumi.Input[Optional[_builtins.int]] = None,
                 username: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ServiceAccountArgs.__new__(ServiceAccountArgs)

            __props__.__dict__["name"] = name
            if root_role is None and not opts.urn:
                raise TypeError("Missing required property 'root_role'")
            __props__.__dict__["root_role"] = root_role
            if username is None and not opts.urn:
                raise TypeError("Missing required property 'username'")
            __props__.__dict__["username"] = username
        super(ServiceAccount, __self__).__init__(
            'unleash:index/serviceAccount:ServiceAccount',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            root_role: pulumi.Input[Optional[_builtins.int]] = None,
            username: pulumi.Input[Optional[_builtins.str]] = None) -> 'ServiceAccount':
        """
        Get an existing ServiceAccount resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] name: The name of the service account.
        :param pulumi.Input[_builtins.int] root_role: The root role ID for the service account.
        :param pulumi.Input[_builtins.str] username: The username for the service account.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ServiceAccountState.__new__(_ServiceAccountState)

        __props__.__dict__["name"] = name
        __props__.__dict__["root_role"] = root_role
        __props__.__dict__["username"] = username
        return ServiceAccount(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the service account.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="rootRole")
    def root_role(self) -> pulumi.Output[_builtins.int]:
        """
        The root role ID for the service account.
        """
        return pulumi.get(self, "root_role")

    @_builtins.property
    @pulumi.getter
    def username(self) -> pulumi.Output[_builtins.str]:
        """
        The username for the service account.
        """
        return pulumi.get(self, "username")

