# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ApiTokenArgs', 'ApiToken']

@pulumi.input_type
class ApiTokenArgs:
    def __init__(__self__, *,
                 environment: pulumi.Input[Optional[_builtins.str]] = None,
                 expires_at: pulumi.Input[Optional[_builtins.str]] = None,
                 project: pulumi.Input[Optional[_builtins.str]] = None,
                 projects: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 token_name: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a ApiToken resource.

        :param pulumi.Input[_builtins.str] environment: An environment the token has access to.
        :param pulumi.Input[_builtins.str] expires_at: When the token expires
        :param pulumi.Input[_builtins.str] project: A project the token belongs to.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] projects: The list of projects this token has access to. If the token has access to specific projects they will be listed here. If the token has access to all projects it will be represented as `[*]`.
        :param pulumi.Input[_builtins.str] token_name: The name of the token.
        :param pulumi.Input[_builtins.str] type: The type of the token.
        """
        if environment is not None:
            pulumi.set(__self__, "environment", environment)
        if expires_at is not None:
            pulumi.set(__self__, "expires_at", expires_at)
        if project is not None:
            warnings.warn("""Don't use. Use projects instead. This attribute will not work against Unleash v7""", DeprecationWarning)
            pulumi.log.warn("""project is deprecated: Don't use. Use projects instead. This attribute will not work against Unleash v7""")
        if project is not None:
            pulumi.set(__self__, "project", project)
        if projects is not None:
            pulumi.set(__self__, "projects", projects)
        if token_name is not None:
            pulumi.set(__self__, "token_name", token_name)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def environment(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        An environment the token has access to.
        """
        return pulumi.get(self, "environment")

    @environment.setter
    def environment(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "environment", value)

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        When the token expires
        """
        return pulumi.get(self, "expires_at")

    @expires_at.setter
    def expires_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "expires_at", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Don't use. Use projects instead. This attribute will not work against Unleash v7""")
    def project(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A project the token belongs to.
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project", value)

    @_builtins.property
    @pulumi.getter
    def projects(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The list of projects this token has access to. If the token has access to specific projects they will be listed here. If the token has access to all projects it will be represented as `[*]`.
        """
        return pulumi.get(self, "projects")

    @projects.setter
    def projects(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "projects", value)

    @_builtins.property
    @pulumi.getter(name="tokenName")
    def token_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the token.
        """
        return pulumi.get(self, "token_name")

    @token_name.setter
    def token_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "token_name", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The type of the token.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "type", value)


@pulumi.input_type
class _ApiTokenState:
    def __init__(__self__, *,
                 environment: pulumi.Input[Optional[_builtins.str]] = None,
                 expires_at: pulumi.Input[Optional[_builtins.str]] = None,
                 project: pulumi.Input[Optional[_builtins.str]] = None,
                 projects: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 secret: pulumi.Input[Optional[_builtins.str]] = None,
                 token_name: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering ApiToken resources.

        :param pulumi.Input[_builtins.str] environment: An environment the token has access to.
        :param pulumi.Input[_builtins.str] expires_at: When the token expires
        :param pulumi.Input[_builtins.str] project: A project the token belongs to.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] projects: The list of projects this token has access to. If the token has access to specific projects they will be listed here. If the token has access to all projects it will be represented as `[*]`.
        :param pulumi.Input[_builtins.str] secret: Secret token value.
        :param pulumi.Input[_builtins.str] token_name: The name of the token.
        :param pulumi.Input[_builtins.str] type: The type of the token.
        """
        if environment is not None:
            pulumi.set(__self__, "environment", environment)
        if expires_at is not None:
            pulumi.set(__self__, "expires_at", expires_at)
        if project is not None:
            warnings.warn("""Don't use. Use projects instead. This attribute will not work against Unleash v7""", DeprecationWarning)
            pulumi.log.warn("""project is deprecated: Don't use. Use projects instead. This attribute will not work against Unleash v7""")
        if project is not None:
            pulumi.set(__self__, "project", project)
        if projects is not None:
            pulumi.set(__self__, "projects", projects)
        if secret is not None:
            pulumi.set(__self__, "secret", secret)
        if token_name is not None:
            pulumi.set(__self__, "token_name", token_name)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def environment(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        An environment the token has access to.
        """
        return pulumi.get(self, "environment")

    @environment.setter
    def environment(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "environment", value)

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        When the token expires
        """
        return pulumi.get(self, "expires_at")

    @expires_at.setter
    def expires_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "expires_at", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Don't use. Use projects instead. This attribute will not work against Unleash v7""")
    def project(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A project the token belongs to.
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project", value)

    @_builtins.property
    @pulumi.getter
    def projects(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The list of projects this token has access to. If the token has access to specific projects they will be listed here. If the token has access to all projects it will be represented as `[*]`.
        """
        return pulumi.get(self, "projects")

    @projects.setter
    def projects(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "projects", value)

    @_builtins.property
    @pulumi.getter
    def secret(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Secret token value.
        """
        return pulumi.get(self, "secret")

    @secret.setter
    def secret(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "secret", value)

    @_builtins.property
    @pulumi.getter(name="tokenName")
    def token_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the token.
        """
        return pulumi.get(self, "token_name")

    @token_name.setter
    def token_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "token_name", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The type of the token.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "type", value)


@pulumi.type_token("unleash:index/apiToken:ApiToken")
class ApiToken(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 environment: pulumi.Input[Optional[_builtins.str]] = None,
                 expires_at: pulumi.Input[Optional[_builtins.str]] = None,
                 project: pulumi.Input[Optional[_builtins.str]] = None,
                 projects: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 token_name: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        ApiToken schema


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] environment: An environment the token has access to.
        :param pulumi.Input[_builtins.str] expires_at: When the token expires
        :param pulumi.Input[_builtins.str] project: A project the token belongs to.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] projects: The list of projects this token has access to. If the token has access to specific projects they will be listed here. If the token has access to all projects it will be represented as `[*]`.
        :param pulumi.Input[_builtins.str] token_name: The name of the token.
        :param pulumi.Input[_builtins.str] type: The type of the token.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ApiTokenArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        ApiToken schema


        :param str resource_name: The name of the resource.
        :param ApiTokenArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ApiTokenArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 environment: pulumi.Input[Optional[_builtins.str]] = None,
                 expires_at: pulumi.Input[Optional[_builtins.str]] = None,
                 project: pulumi.Input[Optional[_builtins.str]] = None,
                 projects: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 token_name: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ApiTokenArgs.__new__(ApiTokenArgs)

            __props__.__dict__["environment"] = environment
            __props__.__dict__["expires_at"] = expires_at
            __props__.__dict__["project"] = project
            __props__.__dict__["projects"] = projects
            __props__.__dict__["token_name"] = token_name
            __props__.__dict__["type"] = type
            __props__.__dict__["secret"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["secret"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ApiToken, __self__).__init__(
            'unleash:index/apiToken:ApiToken',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            environment: pulumi.Input[Optional[_builtins.str]] = None,
            expires_at: pulumi.Input[Optional[_builtins.str]] = None,
            project: pulumi.Input[Optional[_builtins.str]] = None,
            projects: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            secret: pulumi.Input[Optional[_builtins.str]] = None,
            token_name: pulumi.Input[Optional[_builtins.str]] = None,
            type: pulumi.Input[Optional[_builtins.str]] = None) -> 'ApiToken':
        """
        Get an existing ApiToken resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] environment: An environment the token has access to.
        :param pulumi.Input[_builtins.str] expires_at: When the token expires
        :param pulumi.Input[_builtins.str] project: A project the token belongs to.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] projects: The list of projects this token has access to. If the token has access to specific projects they will be listed here. If the token has access to all projects it will be represented as `[*]`.
        :param pulumi.Input[_builtins.str] secret: Secret token value.
        :param pulumi.Input[_builtins.str] token_name: The name of the token.
        :param pulumi.Input[_builtins.str] type: The type of the token.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ApiTokenState.__new__(_ApiTokenState)

        __props__.__dict__["environment"] = environment
        __props__.__dict__["expires_at"] = expires_at
        __props__.__dict__["project"] = project
        __props__.__dict__["projects"] = projects
        __props__.__dict__["secret"] = secret
        __props__.__dict__["token_name"] = token_name
        __props__.__dict__["type"] = type
        return ApiToken(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def environment(self) -> pulumi.Output[_builtins.str]:
        """
        An environment the token has access to.
        """
        return pulumi.get(self, "environment")

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        When the token expires
        """
        return pulumi.get(self, "expires_at")

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Don't use. Use projects instead. This attribute will not work against Unleash v7""")
    def project(self) -> pulumi.Output[_builtins.str]:
        """
        A project the token belongs to.
        """
        return pulumi.get(self, "project")

    @_builtins.property
    @pulumi.getter
    def projects(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        The list of projects this token has access to. If the token has access to specific projects they will be listed here. If the token has access to all projects it will be represented as `[*]`.
        """
        return pulumi.get(self, "projects")

    @_builtins.property
    @pulumi.getter
    def secret(self) -> pulumi.Output[_builtins.str]:
        """
        Secret token value.
        """
        return pulumi.get(self, "secret")

    @_builtins.property
    @pulumi.getter(name="tokenName")
    def token_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The name of the token.
        """
        return pulumi.get(self, "token_name")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The type of the token.
        """
        return pulumi.get(self, "type")

