# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetContextFieldResult',
    'AwaitableGetContextFieldResult',
    'get_context_field',
    'get_context_field_output',
]

@pulumi.output_type
class GetContextFieldResult:
    """
    A collection of values returned by getContextField.
    """
    def __init__(__self__, description=None, legal_values=None, name=None, stickiness=None):
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if legal_values and not isinstance(legal_values, list):
            raise TypeError("Expected argument 'legal_values' to be a list")
        pulumi.set(__self__, "legal_values", legal_values)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if stickiness and not isinstance(stickiness, bool):
            raise TypeError("Expected argument 'stickiness' to be a bool")
        pulumi.set(__self__, "stickiness", stickiness)

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        A description of the context field.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="legalValues")
    def legal_values(self) -> Sequence['outputs.GetContextFieldLegalValueResult']:
        """
        Legal values for this context field. If not set, then any value is available for this context field.
        """
        return pulumi.get(self, "legal_values")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the context field.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def stickiness(self) -> _builtins.bool:
        """
        Whether this field is available for custom stickiness
        """
        return pulumi.get(self, "stickiness")


class AwaitableGetContextFieldResult(GetContextFieldResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetContextFieldResult(
            description=self.description,
            legal_values=self.legal_values,
            name=self.name,
            stickiness=self.stickiness)


def get_context_field(description: Optional[_builtins.str] = None,
                      legal_values: Optional[Sequence[Union['GetContextFieldLegalValueArgs', 'GetContextFieldLegalValueArgsDict']]] = None,
                      name: Optional[_builtins.str] = None,
                      stickiness: Optional[_builtins.bool] = None,
                      opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetContextFieldResult:
    """
    Fetch a context field.


    :param _builtins.str description: A description of the context field.
    :param Sequence[Union['GetContextFieldLegalValueArgs', 'GetContextFieldLegalValueArgsDict']] legal_values: Legal values for this context field. If not set, then any value is available for this context field.
    :param _builtins.str name: The name of the context field.
    :param _builtins.bool stickiness: Whether this field is available for custom stickiness
    """
    __args__ = dict()
    __args__['description'] = description
    __args__['legalValues'] = legal_values
    __args__['name'] = name
    __args__['stickiness'] = stickiness
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('unleash:index/getContextField:getContextField', __args__, opts=opts, typ=GetContextFieldResult).value

    return AwaitableGetContextFieldResult(
        description=pulumi.get(__ret__, 'description'),
        legal_values=pulumi.get(__ret__, 'legal_values'),
        name=pulumi.get(__ret__, 'name'),
        stickiness=pulumi.get(__ret__, 'stickiness'))
def get_context_field_output(description: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                             legal_values: pulumi.Input[Optional[Optional[Sequence[Union['GetContextFieldLegalValueArgs', 'GetContextFieldLegalValueArgsDict']]]]] = None,
                             name: pulumi.Input[Optional[_builtins.str]] = None,
                             stickiness: pulumi.Input[Optional[Optional[_builtins.bool]]] = None,
                             opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetContextFieldResult]:
    """
    Fetch a context field.


    :param _builtins.str description: A description of the context field.
    :param Sequence[Union['GetContextFieldLegalValueArgs', 'GetContextFieldLegalValueArgsDict']] legal_values: Legal values for this context field. If not set, then any value is available for this context field.
    :param _builtins.str name: The name of the context field.
    :param _builtins.bool stickiness: Whether this field is available for custom stickiness
    """
    __args__ = dict()
    __args__['description'] = description
    __args__['legalValues'] = legal_values
    __args__['name'] = name
    __args__['stickiness'] = stickiness
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('unleash:index/getContextField:getContextField', __args__, opts=opts, typ=GetContextFieldResult)
    return __ret__.apply(lambda __response__: GetContextFieldResult(
        description=pulumi.get(__response__, 'description'),
        legal_values=pulumi.get(__response__, 'legal_values'),
        name=pulumi.get(__response__, 'name'),
        stickiness=pulumi.get(__response__, 'stickiness')))
