# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ProjectAccessArgs', 'ProjectAccess']

@pulumi.input_type
class ProjectAccessArgs:
    def __init__(__self__, *,
                 project: pulumi.Input[_builtins.str],
                 roles: pulumi.Input[Sequence[pulumi.Input['ProjectAccessRoleArgs']]]):
        """
        The set of arguments for constructing a ProjectAccess resource.

        :param pulumi.Input[_builtins.str] project: Project identifier.
        :param pulumi.Input[Sequence[pulumi.Input['ProjectAccessRoleArgs']]] roles: Roles available in this project with their members.
        """
        pulumi.set(__self__, "project", project)
        pulumi.set(__self__, "roles", roles)

    @_builtins.property
    @pulumi.getter
    def project(self) -> pulumi.Input[_builtins.str]:
        """
        Project identifier.
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project", value)

    @_builtins.property
    @pulumi.getter
    def roles(self) -> pulumi.Input[Sequence[pulumi.Input['ProjectAccessRoleArgs']]]:
        """
        Roles available in this project with their members.
        """
        return pulumi.get(self, "roles")

    @roles.setter
    def roles(self, value: pulumi.Input[Sequence[pulumi.Input['ProjectAccessRoleArgs']]]):
        pulumi.set(self, "roles", value)


@pulumi.input_type
class _ProjectAccessState:
    def __init__(__self__, *,
                 project: pulumi.Input[Optional[_builtins.str]] = None,
                 roles: pulumi.Input[Optional[Sequence[pulumi.Input['ProjectAccessRoleArgs']]]] = None):
        """
        Input properties used for looking up and filtering ProjectAccess resources.

        :param pulumi.Input[_builtins.str] project: Project identifier.
        :param pulumi.Input[Sequence[pulumi.Input['ProjectAccessRoleArgs']]] roles: Roles available in this project with their members.
        """
        if project is not None:
            pulumi.set(__self__, "project", project)
        if roles is not None:
            pulumi.set(__self__, "roles", roles)

    @_builtins.property
    @pulumi.getter
    def project(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Project identifier.
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project", value)

    @_builtins.property
    @pulumi.getter
    def roles(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['ProjectAccessRoleArgs']]]]:
        """
        Roles available in this project with their members.
        """
        return pulumi.get(self, "roles")

    @roles.setter
    def roles(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['ProjectAccessRoleArgs']]]]):
        pulumi.set(self, "roles", value)


@pulumi.type_token("unleash:index/projectAccess:ProjectAccess")
class ProjectAccess(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 project: pulumi.Input[Optional[_builtins.str]] = None,
                 roles: pulumi.Input[Optional[Sequence[pulumi.Input[Union['ProjectAccessRoleArgs', 'ProjectAccessRoleArgsDict']]]]] = None,
                 __props__=None):
        """
        ProjectAccess schema


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] project: Project identifier.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ProjectAccessRoleArgs', 'ProjectAccessRoleArgsDict']]]] roles: Roles available in this project with their members.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ProjectAccessArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        ProjectAccess schema


        :param str resource_name: The name of the resource.
        :param ProjectAccessArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProjectAccessArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 project: pulumi.Input[Optional[_builtins.str]] = None,
                 roles: pulumi.Input[Optional[Sequence[pulumi.Input[Union['ProjectAccessRoleArgs', 'ProjectAccessRoleArgsDict']]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProjectAccessArgs.__new__(ProjectAccessArgs)

            if project is None and not opts.urn:
                raise TypeError("Missing required property 'project'")
            __props__.__dict__["project"] = project
            if roles is None and not opts.urn:
                raise TypeError("Missing required property 'roles'")
            __props__.__dict__["roles"] = roles
        super(ProjectAccess, __self__).__init__(
            'unleash:index/projectAccess:ProjectAccess',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            project: pulumi.Input[Optional[_builtins.str]] = None,
            roles: pulumi.Input[Optional[Sequence[pulumi.Input[Union['ProjectAccessRoleArgs', 'ProjectAccessRoleArgsDict']]]]] = None) -> 'ProjectAccess':
        """
        Get an existing ProjectAccess resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] project: Project identifier.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ProjectAccessRoleArgs', 'ProjectAccessRoleArgsDict']]]] roles: Roles available in this project with their members.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ProjectAccessState.__new__(_ProjectAccessState)

        __props__.__dict__["project"] = project
        __props__.__dict__["roles"] = roles
        return ProjectAccess(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def project(self) -> pulumi.Output[_builtins.str]:
        """
        Project identifier.
        """
        return pulumi.get(self, "project")

    @_builtins.property
    @pulumi.getter
    def roles(self) -> pulumi.Output[Sequence['outputs.ProjectAccessRole']]:
        """
        Roles available in this project with their members.
        """
        return pulumi.get(self, "roles")

