# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('unleash')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def authorization(self) -> Optional[str]:
        """
        Authorization token for Unleash API
        """
        return __config__.get('authorization') or _utilities.get_env('UNLEASH_AUTH_TOKEN')

    @_builtins.property
    def base_url(self) -> Optional[str]:
        """
        Unleash base URL (everything before `/api`)
        """
        return __config__.get('baseUrl') or _utilities.get_env('UNLEASH_URL')

    @_builtins.property
    def max_concurrent_requests(self) -> Optional[int]:
        """
        Maximum number of concurrent HTTP requests the provider sends to the Unleash API. Defaults to `2`, which is the recommended value for most Unleash deployments. Increasing this value can overload Unleash instances with small database connection pools and should only be done when the backend capacity is known to support it. Can also be set with `UNLEASH_MAX_CONCURRENT_REQUESTS`.
        """
        return __config__.get_int('maxConcurrentRequests') or _utilities.get_env_int('UNLEASH_MAX_CONCURRENT_REQUESTS')

