// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/hagaym1/pulumi-unleash/sdk/v3/go/unleash/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Authorization token for Unleash API
func GetAuthorization(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "unleash:authorization")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "UNLEASH_AUTH_TOKEN"); d != nil {
		value = d.(string)
	}
	return value
}

// Unleash base URL (everything before `/api`)
func GetBaseUrl(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "unleash:baseUrl")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "UNLEASH_URL"); d != nil {
		value = d.(string)
	}
	return value
}

// Maximum number of concurrent HTTP requests the provider sends to the Unleash API. Defaults to `2`, which is the recommended value for most Unleash deployments. Increasing this value can overload Unleash instances with small database connection pools and should only be done when the backend capacity is known to support it. Can also be set with `UNLEASH_MAX_CONCURRENT_REQUESTS`.
func GetMaxConcurrentRequests(ctx *pulumi.Context) int {
	v, err := config.TryInt(ctx, "unleash:maxConcurrentRequests")
	if err == nil {
		return v
	}
	var value int
	if d := internal.GetEnvOrDefault(nil, internal.ParseEnvInt, "UNLEASH_MAX_CONCURRENT_REQUESTS"); d != nil {
		value = d.(int)
	}
	return value
}
