// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ContextFieldLegalValue {
    /**
     * Description of the allowed value.
     */
    description?: string;
    /**
     * The allowed value.
     */
    value: string;
}

export interface GetContextFieldLegalValue {
    /**
     * Description of the allowed value.
     */
    description: string;
    /**
     * The allowed value.
     */
    value: string;
}

export interface ProjectAccessRole {
    /**
     * List of projects with this role assigned.
     */
    groups: number[];
    /**
     * The role identifier.
     */
    role: number;
    /**
     * List of users with this role assigned.
     */
    users: number[];
}

export interface ProjectFeatureNaming {
    /**
     * A human-readable description of the pattern.
     */
    description?: string;
    /**
     * An example feature name that matches the pattern.
     */
    example?: string;
    /**
     * A JavaScript regular expression pattern, without the start and end delimiters.
     */
    pattern: string;
}

export interface ProjectLinkTemplate {
    /**
     * Link title shown in the Unleash UI.
     */
    title?: string;
    /**
     * URL template that can contain {{project}} or {{feature}} placeholders.
     */
    urlTemplate: string;
}

export interface RolePermission {
    /**
     * For which environment this permission applies (note that only environment-type permissions can have an environment).
     */
    environment?: string;
    /**
     * The name of this permission.
     */
    name: string;
}

