// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package unleash

import (
	"context"
	"reflect"

	"github.com/hagaym1/pulumi-unleash/sdk/v3/go/unleash/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ApiToken schema
type ApiToken struct {
	pulumi.CustomResourceState

	// An environment the token has access to.
	Environment pulumi.StringOutput `pulumi:"environment"`
	// When the token expires
	ExpiresAt pulumi.StringPtrOutput `pulumi:"expiresAt"`
	// A project the token belongs to.
	//
	// Deprecated: Don't use. Use projects instead. This attribute will not work against Unleash v7
	Project pulumi.StringOutput `pulumi:"project"`
	// The list of projects this token has access to. If the token has access to specific projects they will be listed here. If the token has access to all projects it will be represented as `[*]`.
	Projects pulumi.StringArrayOutput `pulumi:"projects"`
	// Secret token value.
	Secret pulumi.StringOutput `pulumi:"secret"`
	// The name of the token.
	TokenName pulumi.StringPtrOutput `pulumi:"tokenName"`
	// The type of the token.
	Type pulumi.StringPtrOutput `pulumi:"type"`
}

// NewApiToken registers a new resource with the given unique name, arguments, and options.
func NewApiToken(ctx *pulumi.Context,
	name string, args *ApiTokenArgs, opts ...pulumi.ResourceOption) (*ApiToken, error) {
	if args == nil {
		args = &ApiTokenArgs{}
	}

	secrets := pulumi.AdditionalSecretOutputs([]string{
		"secret",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ApiToken
	err := ctx.RegisterResource("unleash:index/apiToken:ApiToken", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetApiToken gets an existing ApiToken resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetApiToken(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ApiTokenState, opts ...pulumi.ResourceOption) (*ApiToken, error) {
	var resource ApiToken
	err := ctx.ReadResource("unleash:index/apiToken:ApiToken", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ApiToken resources.
type apiTokenState struct {
	// An environment the token has access to.
	Environment *string `pulumi:"environment"`
	// When the token expires
	ExpiresAt *string `pulumi:"expiresAt"`
	// A project the token belongs to.
	//
	// Deprecated: Don't use. Use projects instead. This attribute will not work against Unleash v7
	Project *string `pulumi:"project"`
	// The list of projects this token has access to. If the token has access to specific projects they will be listed here. If the token has access to all projects it will be represented as `[*]`.
	Projects []string `pulumi:"projects"`
	// Secret token value.
	Secret *string `pulumi:"secret"`
	// The name of the token.
	TokenName *string `pulumi:"tokenName"`
	// The type of the token.
	Type *string `pulumi:"type"`
}

type ApiTokenState struct {
	// An environment the token has access to.
	Environment pulumi.StringPtrInput
	// When the token expires
	ExpiresAt pulumi.StringPtrInput
	// A project the token belongs to.
	//
	// Deprecated: Don't use. Use projects instead. This attribute will not work against Unleash v7
	Project pulumi.StringPtrInput
	// The list of projects this token has access to. If the token has access to specific projects they will be listed here. If the token has access to all projects it will be represented as `[*]`.
	Projects pulumi.StringArrayInput
	// Secret token value.
	Secret pulumi.StringPtrInput
	// The name of the token.
	TokenName pulumi.StringPtrInput
	// The type of the token.
	Type pulumi.StringPtrInput
}

func (ApiTokenState) ElementType() reflect.Type {
	return reflect.TypeOf((*apiTokenState)(nil)).Elem()
}

type apiTokenArgs struct {
	// An environment the token has access to.
	Environment *string `pulumi:"environment"`
	// When the token expires
	ExpiresAt *string `pulumi:"expiresAt"`
	// A project the token belongs to.
	//
	// Deprecated: Don't use. Use projects instead. This attribute will not work against Unleash v7
	Project *string `pulumi:"project"`
	// The list of projects this token has access to. If the token has access to specific projects they will be listed here. If the token has access to all projects it will be represented as `[*]`.
	Projects []string `pulumi:"projects"`
	// The name of the token.
	TokenName *string `pulumi:"tokenName"`
	// The type of the token.
	Type *string `pulumi:"type"`
}

// The set of arguments for constructing a ApiToken resource.
type ApiTokenArgs struct {
	// An environment the token has access to.
	Environment pulumi.StringPtrInput
	// When the token expires
	ExpiresAt pulumi.StringPtrInput
	// A project the token belongs to.
	//
	// Deprecated: Don't use. Use projects instead. This attribute will not work against Unleash v7
	Project pulumi.StringPtrInput
	// The list of projects this token has access to. If the token has access to specific projects they will be listed here. If the token has access to all projects it will be represented as `[*]`.
	Projects pulumi.StringArrayInput
	// The name of the token.
	TokenName pulumi.StringPtrInput
	// The type of the token.
	Type pulumi.StringPtrInput
}

func (ApiTokenArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*apiTokenArgs)(nil)).Elem()
}

type ApiTokenInput interface {
	pulumi.Input

	ToApiTokenOutput() ApiTokenOutput
	ToApiTokenOutputWithContext(ctx context.Context) ApiTokenOutput
}

func (*ApiToken) ElementType() reflect.Type {
	return reflect.TypeOf((**ApiToken)(nil)).Elem()
}

func (i *ApiToken) ToApiTokenOutput() ApiTokenOutput {
	return i.ToApiTokenOutputWithContext(context.Background())
}

func (i *ApiToken) ToApiTokenOutputWithContext(ctx context.Context) ApiTokenOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApiTokenOutput)
}

// ApiTokenArrayInput is an input type that accepts ApiTokenArray and ApiTokenArrayOutput values.
// You can construct a concrete instance of `ApiTokenArrayInput` via:
//
//	ApiTokenArray{ ApiTokenArgs{...} }
type ApiTokenArrayInput interface {
	pulumi.Input

	ToApiTokenArrayOutput() ApiTokenArrayOutput
	ToApiTokenArrayOutputWithContext(context.Context) ApiTokenArrayOutput
}

type ApiTokenArray []ApiTokenInput

func (ApiTokenArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ApiToken)(nil)).Elem()
}

func (i ApiTokenArray) ToApiTokenArrayOutput() ApiTokenArrayOutput {
	return i.ToApiTokenArrayOutputWithContext(context.Background())
}

func (i ApiTokenArray) ToApiTokenArrayOutputWithContext(ctx context.Context) ApiTokenArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApiTokenArrayOutput)
}

// ApiTokenMapInput is an input type that accepts ApiTokenMap and ApiTokenMapOutput values.
// You can construct a concrete instance of `ApiTokenMapInput` via:
//
//	ApiTokenMap{ "key": ApiTokenArgs{...} }
type ApiTokenMapInput interface {
	pulumi.Input

	ToApiTokenMapOutput() ApiTokenMapOutput
	ToApiTokenMapOutputWithContext(context.Context) ApiTokenMapOutput
}

type ApiTokenMap map[string]ApiTokenInput

func (ApiTokenMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ApiToken)(nil)).Elem()
}

func (i ApiTokenMap) ToApiTokenMapOutput() ApiTokenMapOutput {
	return i.ToApiTokenMapOutputWithContext(context.Background())
}

func (i ApiTokenMap) ToApiTokenMapOutputWithContext(ctx context.Context) ApiTokenMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApiTokenMapOutput)
}

type ApiTokenOutput struct{ *pulumi.OutputState }

func (ApiTokenOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ApiToken)(nil)).Elem()
}

func (o ApiTokenOutput) ToApiTokenOutput() ApiTokenOutput {
	return o
}

func (o ApiTokenOutput) ToApiTokenOutputWithContext(ctx context.Context) ApiTokenOutput {
	return o
}

// An environment the token has access to.
func (o ApiTokenOutput) Environment() pulumi.StringOutput {
	return o.ApplyT(func(v *ApiToken) pulumi.StringOutput { return v.Environment }).(pulumi.StringOutput)
}

// When the token expires
func (o ApiTokenOutput) ExpiresAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ApiToken) pulumi.StringPtrOutput { return v.ExpiresAt }).(pulumi.StringPtrOutput)
}

// A project the token belongs to.
//
// Deprecated: Don't use. Use projects instead. This attribute will not work against Unleash v7
func (o ApiTokenOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v *ApiToken) pulumi.StringOutput { return v.Project }).(pulumi.StringOutput)
}

// The list of projects this token has access to. If the token has access to specific projects they will be listed here. If the token has access to all projects it will be represented as `[*]`.
func (o ApiTokenOutput) Projects() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ApiToken) pulumi.StringArrayOutput { return v.Projects }).(pulumi.StringArrayOutput)
}

// Secret token value.
func (o ApiTokenOutput) Secret() pulumi.StringOutput {
	return o.ApplyT(func(v *ApiToken) pulumi.StringOutput { return v.Secret }).(pulumi.StringOutput)
}

// The name of the token.
func (o ApiTokenOutput) TokenName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ApiToken) pulumi.StringPtrOutput { return v.TokenName }).(pulumi.StringPtrOutput)
}

// The type of the token.
func (o ApiTokenOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ApiToken) pulumi.StringPtrOutput { return v.Type }).(pulumi.StringPtrOutput)
}

type ApiTokenArrayOutput struct{ *pulumi.OutputState }

func (ApiTokenArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ApiToken)(nil)).Elem()
}

func (o ApiTokenArrayOutput) ToApiTokenArrayOutput() ApiTokenArrayOutput {
	return o
}

func (o ApiTokenArrayOutput) ToApiTokenArrayOutputWithContext(ctx context.Context) ApiTokenArrayOutput {
	return o
}

func (o ApiTokenArrayOutput) Index(i pulumi.IntInput) ApiTokenOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ApiToken {
		return vs[0].([]*ApiToken)[vs[1].(int)]
	}).(ApiTokenOutput)
}

type ApiTokenMapOutput struct{ *pulumi.OutputState }

func (ApiTokenMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ApiToken)(nil)).Elem()
}

func (o ApiTokenMapOutput) ToApiTokenMapOutput() ApiTokenMapOutput {
	return o
}

func (o ApiTokenMapOutput) ToApiTokenMapOutputWithContext(ctx context.Context) ApiTokenMapOutput {
	return o
}

func (o ApiTokenMapOutput) MapIndex(k pulumi.StringInput) ApiTokenOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ApiToken {
		return vs[0].(map[string]*ApiToken)[vs[1].(string)]
	}).(ApiTokenOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ApiTokenInput)(nil)).Elem(), &ApiToken{})
	pulumi.RegisterInputType(reflect.TypeOf((*ApiTokenArrayInput)(nil)).Elem(), ApiTokenArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ApiTokenMapInput)(nil)).Elem(), ApiTokenMap{})
	pulumi.RegisterOutputType(ApiTokenOutput{})
	pulumi.RegisterOutputType(ApiTokenArrayOutput{})
	pulumi.RegisterOutputType(ApiTokenMapOutput{})
}
