// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package unleash

import (
	"context"
	"reflect"

	"github.com/hagaym1/pulumi-unleash/sdk/v3/go/unleash/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Fetch a context field.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/hagaym1/pulumi-unleash/sdk/v3/go/unleash"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := unleash.NewContextField(ctx, "ham_context_field", &unleash.ContextFieldArgs{
//				Name: pulumi.String("ham"),
//			})
//			if err != nil {
//				return err
//			}
//			_, err = unleash.NewContextField(ctx, "cheese_context_field", &unleash.ContextFieldArgs{
//				Name:        pulumi.String("cheese"),
//				Stickiness:  pulumi.Bool(true),
//				Description: pulumi.String("Type of cheese to constrain on"),
//				LegalValues: unleash.ContextFieldLegalValueArray{
//					&unleash.ContextFieldLegalValueArgs{
//						Value:       pulumi.String("brie"),
//						Description: pulumi.String("Gooey, delicious"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type ContextField struct {
	pulumi.CustomResourceState

	// A description of the context field.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Legal values for this context field. If not set, then any value is available for this context field.
	LegalValues ContextFieldLegalValueArrayOutput `pulumi:"legalValues"`
	// The name of the context field.
	Name pulumi.StringOutput `pulumi:"name"`
	// Whether this field is available for custom stickiness. Defaults to false if not set.
	Stickiness pulumi.BoolOutput `pulumi:"stickiness"`
}

// NewContextField registers a new resource with the given unique name, arguments, and options.
func NewContextField(ctx *pulumi.Context,
	name string, args *ContextFieldArgs, opts ...pulumi.ResourceOption) (*ContextField, error) {
	if args == nil {
		args = &ContextFieldArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ContextField
	err := ctx.RegisterResource("unleash:index/contextField:ContextField", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetContextField gets an existing ContextField resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetContextField(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ContextFieldState, opts ...pulumi.ResourceOption) (*ContextField, error) {
	var resource ContextField
	err := ctx.ReadResource("unleash:index/contextField:ContextField", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ContextField resources.
type contextFieldState struct {
	// A description of the context field.
	Description *string `pulumi:"description"`
	// Legal values for this context field. If not set, then any value is available for this context field.
	LegalValues []ContextFieldLegalValue `pulumi:"legalValues"`
	// The name of the context field.
	Name *string `pulumi:"name"`
	// Whether this field is available for custom stickiness. Defaults to false if not set.
	Stickiness *bool `pulumi:"stickiness"`
}

type ContextFieldState struct {
	// A description of the context field.
	Description pulumi.StringPtrInput
	// Legal values for this context field. If not set, then any value is available for this context field.
	LegalValues ContextFieldLegalValueArrayInput
	// The name of the context field.
	Name pulumi.StringPtrInput
	// Whether this field is available for custom stickiness. Defaults to false if not set.
	Stickiness pulumi.BoolPtrInput
}

func (ContextFieldState) ElementType() reflect.Type {
	return reflect.TypeOf((*contextFieldState)(nil)).Elem()
}

type contextFieldArgs struct {
	// A description of the context field.
	Description *string `pulumi:"description"`
	// Legal values for this context field. If not set, then any value is available for this context field.
	LegalValues []ContextFieldLegalValue `pulumi:"legalValues"`
	// The name of the context field.
	Name *string `pulumi:"name"`
	// Whether this field is available for custom stickiness. Defaults to false if not set.
	Stickiness *bool `pulumi:"stickiness"`
}

// The set of arguments for constructing a ContextField resource.
type ContextFieldArgs struct {
	// A description of the context field.
	Description pulumi.StringPtrInput
	// Legal values for this context field. If not set, then any value is available for this context field.
	LegalValues ContextFieldLegalValueArrayInput
	// The name of the context field.
	Name pulumi.StringPtrInput
	// Whether this field is available for custom stickiness. Defaults to false if not set.
	Stickiness pulumi.BoolPtrInput
}

func (ContextFieldArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*contextFieldArgs)(nil)).Elem()
}

type ContextFieldInput interface {
	pulumi.Input

	ToContextFieldOutput() ContextFieldOutput
	ToContextFieldOutputWithContext(ctx context.Context) ContextFieldOutput
}

func (*ContextField) ElementType() reflect.Type {
	return reflect.TypeOf((**ContextField)(nil)).Elem()
}

func (i *ContextField) ToContextFieldOutput() ContextFieldOutput {
	return i.ToContextFieldOutputWithContext(context.Background())
}

func (i *ContextField) ToContextFieldOutputWithContext(ctx context.Context) ContextFieldOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContextFieldOutput)
}

// ContextFieldArrayInput is an input type that accepts ContextFieldArray and ContextFieldArrayOutput values.
// You can construct a concrete instance of `ContextFieldArrayInput` via:
//
//	ContextFieldArray{ ContextFieldArgs{...} }
type ContextFieldArrayInput interface {
	pulumi.Input

	ToContextFieldArrayOutput() ContextFieldArrayOutput
	ToContextFieldArrayOutputWithContext(context.Context) ContextFieldArrayOutput
}

type ContextFieldArray []ContextFieldInput

func (ContextFieldArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ContextField)(nil)).Elem()
}

func (i ContextFieldArray) ToContextFieldArrayOutput() ContextFieldArrayOutput {
	return i.ToContextFieldArrayOutputWithContext(context.Background())
}

func (i ContextFieldArray) ToContextFieldArrayOutputWithContext(ctx context.Context) ContextFieldArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContextFieldArrayOutput)
}

// ContextFieldMapInput is an input type that accepts ContextFieldMap and ContextFieldMapOutput values.
// You can construct a concrete instance of `ContextFieldMapInput` via:
//
//	ContextFieldMap{ "key": ContextFieldArgs{...} }
type ContextFieldMapInput interface {
	pulumi.Input

	ToContextFieldMapOutput() ContextFieldMapOutput
	ToContextFieldMapOutputWithContext(context.Context) ContextFieldMapOutput
}

type ContextFieldMap map[string]ContextFieldInput

func (ContextFieldMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ContextField)(nil)).Elem()
}

func (i ContextFieldMap) ToContextFieldMapOutput() ContextFieldMapOutput {
	return i.ToContextFieldMapOutputWithContext(context.Background())
}

func (i ContextFieldMap) ToContextFieldMapOutputWithContext(ctx context.Context) ContextFieldMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContextFieldMapOutput)
}

type ContextFieldOutput struct{ *pulumi.OutputState }

func (ContextFieldOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ContextField)(nil)).Elem()
}

func (o ContextFieldOutput) ToContextFieldOutput() ContextFieldOutput {
	return o
}

func (o ContextFieldOutput) ToContextFieldOutputWithContext(ctx context.Context) ContextFieldOutput {
	return o
}

// A description of the context field.
func (o ContextFieldOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ContextField) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Legal values for this context field. If not set, then any value is available for this context field.
func (o ContextFieldOutput) LegalValues() ContextFieldLegalValueArrayOutput {
	return o.ApplyT(func(v *ContextField) ContextFieldLegalValueArrayOutput { return v.LegalValues }).(ContextFieldLegalValueArrayOutput)
}

// The name of the context field.
func (o ContextFieldOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ContextField) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Whether this field is available for custom stickiness. Defaults to false if not set.
func (o ContextFieldOutput) Stickiness() pulumi.BoolOutput {
	return o.ApplyT(func(v *ContextField) pulumi.BoolOutput { return v.Stickiness }).(pulumi.BoolOutput)
}

type ContextFieldArrayOutput struct{ *pulumi.OutputState }

func (ContextFieldArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ContextField)(nil)).Elem()
}

func (o ContextFieldArrayOutput) ToContextFieldArrayOutput() ContextFieldArrayOutput {
	return o
}

func (o ContextFieldArrayOutput) ToContextFieldArrayOutputWithContext(ctx context.Context) ContextFieldArrayOutput {
	return o
}

func (o ContextFieldArrayOutput) Index(i pulumi.IntInput) ContextFieldOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ContextField {
		return vs[0].([]*ContextField)[vs[1].(int)]
	}).(ContextFieldOutput)
}

type ContextFieldMapOutput struct{ *pulumi.OutputState }

func (ContextFieldMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ContextField)(nil)).Elem()
}

func (o ContextFieldMapOutput) ToContextFieldMapOutput() ContextFieldMapOutput {
	return o
}

func (o ContextFieldMapOutput) ToContextFieldMapOutputWithContext(ctx context.Context) ContextFieldMapOutput {
	return o
}

func (o ContextFieldMapOutput) MapIndex(k pulumi.StringInput) ContextFieldOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ContextField {
		return vs[0].(map[string]*ContextField)[vs[1].(string)]
	}).(ContextFieldOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ContextFieldInput)(nil)).Elem(), &ContextField{})
	pulumi.RegisterInputType(reflect.TypeOf((*ContextFieldArrayInput)(nil)).Elem(), ContextFieldArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ContextFieldMapInput)(nil)).Elem(), ContextFieldMap{})
	pulumi.RegisterOutputType(ContextFieldOutput{})
	pulumi.RegisterOutputType(ContextFieldArrayOutput{})
	pulumi.RegisterOutputType(ContextFieldMapOutput{})
}
