// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package unleash

import (
	"context"
	"reflect"

	"github.com/hagaym1/pulumi-unleash/sdk/v3/go/unleash/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Fetch a context field.
func LookupContextField(ctx *pulumi.Context, args *LookupContextFieldArgs, opts ...pulumi.InvokeOption) (*LookupContextFieldResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupContextFieldResult
	err := ctx.Invoke("unleash:index/getContextField:getContextField", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getContextField.
type LookupContextFieldArgs struct {
	// A description of the context field.
	Description *string `pulumi:"description"`
	// Legal values for this context field. If not set, then any value is available for this context field.
	LegalValues []GetContextFieldLegalValue `pulumi:"legalValues"`
	// The name of the context field.
	Name string `pulumi:"name"`
	// Whether this field is available for custom stickiness
	Stickiness *bool `pulumi:"stickiness"`
}

// A collection of values returned by getContextField.
type LookupContextFieldResult struct {
	// A description of the context field.
	Description string `pulumi:"description"`
	// Legal values for this context field. If not set, then any value is available for this context field.
	LegalValues []GetContextFieldLegalValue `pulumi:"legalValues"`
	// The name of the context field.
	Name string `pulumi:"name"`
	// Whether this field is available for custom stickiness
	Stickiness bool `pulumi:"stickiness"`
}

func LookupContextFieldOutput(ctx *pulumi.Context, args LookupContextFieldOutputArgs, opts ...pulumi.InvokeOption) LookupContextFieldResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupContextFieldResultOutput, error) {
			args := v.(LookupContextFieldArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("unleash:index/getContextField:getContextField", args, LookupContextFieldResultOutput{}, options).(LookupContextFieldResultOutput), nil
		}).(LookupContextFieldResultOutput)
}

// A collection of arguments for invoking getContextField.
type LookupContextFieldOutputArgs struct {
	// A description of the context field.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// Legal values for this context field. If not set, then any value is available for this context field.
	LegalValues GetContextFieldLegalValueArrayInput `pulumi:"legalValues"`
	// The name of the context field.
	Name pulumi.StringInput `pulumi:"name"`
	// Whether this field is available for custom stickiness
	Stickiness pulumi.BoolPtrInput `pulumi:"stickiness"`
}

func (LookupContextFieldOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupContextFieldArgs)(nil)).Elem()
}

// A collection of values returned by getContextField.
type LookupContextFieldResultOutput struct{ *pulumi.OutputState }

func (LookupContextFieldResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupContextFieldResult)(nil)).Elem()
}

func (o LookupContextFieldResultOutput) ToLookupContextFieldResultOutput() LookupContextFieldResultOutput {
	return o
}

func (o LookupContextFieldResultOutput) ToLookupContextFieldResultOutputWithContext(ctx context.Context) LookupContextFieldResultOutput {
	return o
}

// A description of the context field.
func (o LookupContextFieldResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContextFieldResult) string { return v.Description }).(pulumi.StringOutput)
}

// Legal values for this context field. If not set, then any value is available for this context field.
func (o LookupContextFieldResultOutput) LegalValues() GetContextFieldLegalValueArrayOutput {
	return o.ApplyT(func(v LookupContextFieldResult) []GetContextFieldLegalValue { return v.LegalValues }).(GetContextFieldLegalValueArrayOutput)
}

// The name of the context field.
func (o LookupContextFieldResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContextFieldResult) string { return v.Name }).(pulumi.StringOutput)
}

// Whether this field is available for custom stickiness
func (o LookupContextFieldResultOutput) Stickiness() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupContextFieldResult) bool { return v.Stickiness }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupContextFieldResultOutput{})
}
