// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package unleash

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-unleash/sdk/v3/go/unleash/internal"
)

// ProjectEnvironment schema
func LookupProjectEnvironment(ctx *pulumi.Context, args *LookupProjectEnvironmentArgs, opts ...pulumi.InvokeOption) (*LookupProjectEnvironmentResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupProjectEnvironmentResult
	err := ctx.Invoke("unleash:index/getProjectEnvironment:getProjectEnvironment", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getProjectEnvironment.
type LookupProjectEnvironmentArgs struct {
	// Environment identifier, equivalent to the environment name.
	EnvironmentName string `pulumi:"environmentName"`
	// Project identifier.
	ProjectId string `pulumi:"projectId"`
}

// A collection of values returned by getProjectEnvironment.
type LookupProjectEnvironmentResult struct {
	// If change requests are required for this environment, the environment must be enabled for this to have effect.
	ChangeRequestsEnabled bool `pulumi:"changeRequestsEnabled"`
	// If the environment is enabled for this project. This affects whether or not users will be able to enable flags for this environment on this project.
	Enabled bool `pulumi:"enabled"`
	// Environment identifier, equivalent to the environment name.
	EnvironmentName string `pulumi:"environmentName"`
	// Project identifier.
	ProjectId string `pulumi:"projectId"`
	// Number of approvals required for change requests.
	RequiredApprovals int `pulumi:"requiredApprovals"`
}

func LookupProjectEnvironmentOutput(ctx *pulumi.Context, args LookupProjectEnvironmentOutputArgs, opts ...pulumi.InvokeOption) LookupProjectEnvironmentResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupProjectEnvironmentResultOutput, error) {
			args := v.(LookupProjectEnvironmentArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("unleash:index/getProjectEnvironment:getProjectEnvironment", args, LookupProjectEnvironmentResultOutput{}, options).(LookupProjectEnvironmentResultOutput), nil
		}).(LookupProjectEnvironmentResultOutput)
}

// A collection of arguments for invoking getProjectEnvironment.
type LookupProjectEnvironmentOutputArgs struct {
	// Environment identifier, equivalent to the environment name.
	EnvironmentName pulumi.StringInput `pulumi:"environmentName"`
	// Project identifier.
	ProjectId pulumi.StringInput `pulumi:"projectId"`
}

func (LookupProjectEnvironmentOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupProjectEnvironmentArgs)(nil)).Elem()
}

// A collection of values returned by getProjectEnvironment.
type LookupProjectEnvironmentResultOutput struct{ *pulumi.OutputState }

func (LookupProjectEnvironmentResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupProjectEnvironmentResult)(nil)).Elem()
}

func (o LookupProjectEnvironmentResultOutput) ToLookupProjectEnvironmentResultOutput() LookupProjectEnvironmentResultOutput {
	return o
}

func (o LookupProjectEnvironmentResultOutput) ToLookupProjectEnvironmentResultOutputWithContext(ctx context.Context) LookupProjectEnvironmentResultOutput {
	return o
}

// If change requests are required for this environment, the environment must be enabled for this to have effect.
func (o LookupProjectEnvironmentResultOutput) ChangeRequestsEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupProjectEnvironmentResult) bool { return v.ChangeRequestsEnabled }).(pulumi.BoolOutput)
}

// If the environment is enabled for this project. This affects whether or not users will be able to enable flags for this environment on this project.
func (o LookupProjectEnvironmentResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupProjectEnvironmentResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// Environment identifier, equivalent to the environment name.
func (o LookupProjectEnvironmentResultOutput) EnvironmentName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProjectEnvironmentResult) string { return v.EnvironmentName }).(pulumi.StringOutput)
}

// Project identifier.
func (o LookupProjectEnvironmentResultOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProjectEnvironmentResult) string { return v.ProjectId }).(pulumi.StringOutput)
}

// Number of approvals required for change requests.
func (o LookupProjectEnvironmentResultOutput) RequiredApprovals() pulumi.IntOutput {
	return o.ApplyT(func(v LookupProjectEnvironmentResult) int { return v.RequiredApprovals }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupProjectEnvironmentResultOutput{})
}
