// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package unleash

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-unleash/sdk/v3/go/unleash/internal"
)

// Manages OIDC configuration.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-unleash/sdk/v3/go/unleash"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := unleash.NewOidc(ctx, "simple_oidc_config", &unleash.OidcArgs{
//				Enabled:         pulumi.Bool(true),
//				DiscoverUrl:     pulumi.String("http://mock-openid-server:9000/.well-known/openid-configuration"),
//				Secret:          pulumi.String("kinda-sorta-secret"),
//				ClientId:        pulumi.String("client-id"),
//				AutoCreate:      pulumi.Bool(true),
//				DefaultRootRole: pulumi.Int(1),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type Oidc struct {
	pulumi.CustomResourceState

	// Whether to auto create users when they login to Unleash for the first time.
	AutoCreate pulumi.BoolOutput `pulumi:"autoCreate"`
	// The OIDC public identifier.
	ClientId pulumi.StringOutput `pulumi:"clientId"`
	// The default root role give to a user when that user is created. Only used if autoCreate is set to true.
	DefaultRootRole pulumi.IntOutput `pulumi:"defaultRootRole"`
	// A URL pointing to the .well-known configuration of the OIDC provider.
	DiscoverUrl pulumi.StringOutput `pulumi:"discoverUrl"`
	// Whether or not OIDC is enabled.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// The OIDC secret.
	Secret pulumi.StringOutput `pulumi:"secret"`
}

// NewOidc registers a new resource with the given unique name, arguments, and options.
func NewOidc(ctx *pulumi.Context,
	name string, args *OidcArgs, opts ...pulumi.ResourceOption) (*Oidc, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClientId == nil {
		return nil, errors.New("invalid value for required argument 'ClientId'")
	}
	if args.DiscoverUrl == nil {
		return nil, errors.New("invalid value for required argument 'DiscoverUrl'")
	}
	if args.Enabled == nil {
		return nil, errors.New("invalid value for required argument 'Enabled'")
	}
	if args.Secret == nil {
		return nil, errors.New("invalid value for required argument 'Secret'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Oidc
	err := ctx.RegisterResource("unleash:index/oidc:Oidc", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOidc gets an existing Oidc resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOidc(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *OidcState, opts ...pulumi.ResourceOption) (*Oidc, error) {
	var resource Oidc
	err := ctx.ReadResource("unleash:index/oidc:Oidc", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Oidc resources.
type oidcState struct {
	// Whether to auto create users when they login to Unleash for the first time.
	AutoCreate *bool `pulumi:"autoCreate"`
	// The OIDC public identifier.
	ClientId *string `pulumi:"clientId"`
	// The default root role give to a user when that user is created. Only used if autoCreate is set to true.
	DefaultRootRole *int `pulumi:"defaultRootRole"`
	// A URL pointing to the .well-known configuration of the OIDC provider.
	DiscoverUrl *string `pulumi:"discoverUrl"`
	// Whether or not OIDC is enabled.
	Enabled *bool `pulumi:"enabled"`
	// The OIDC secret.
	Secret *string `pulumi:"secret"`
}

type OidcState struct {
	// Whether to auto create users when they login to Unleash for the first time.
	AutoCreate pulumi.BoolPtrInput
	// The OIDC public identifier.
	ClientId pulumi.StringPtrInput
	// The default root role give to a user when that user is created. Only used if autoCreate is set to true.
	DefaultRootRole pulumi.IntPtrInput
	// A URL pointing to the .well-known configuration of the OIDC provider.
	DiscoverUrl pulumi.StringPtrInput
	// Whether or not OIDC is enabled.
	Enabled pulumi.BoolPtrInput
	// The OIDC secret.
	Secret pulumi.StringPtrInput
}

func (OidcState) ElementType() reflect.Type {
	return reflect.TypeOf((*oidcState)(nil)).Elem()
}

type oidcArgs struct {
	// Whether to auto create users when they login to Unleash for the first time.
	AutoCreate *bool `pulumi:"autoCreate"`
	// The OIDC public identifier.
	ClientId string `pulumi:"clientId"`
	// The default root role give to a user when that user is created. Only used if autoCreate is set to true.
	DefaultRootRole *int `pulumi:"defaultRootRole"`
	// A URL pointing to the .well-known configuration of the OIDC provider.
	DiscoverUrl string `pulumi:"discoverUrl"`
	// Whether or not OIDC is enabled.
	Enabled bool `pulumi:"enabled"`
	// The OIDC secret.
	Secret string `pulumi:"secret"`
}

// The set of arguments for constructing a Oidc resource.
type OidcArgs struct {
	// Whether to auto create users when they login to Unleash for the first time.
	AutoCreate pulumi.BoolPtrInput
	// The OIDC public identifier.
	ClientId pulumi.StringInput
	// The default root role give to a user when that user is created. Only used if autoCreate is set to true.
	DefaultRootRole pulumi.IntPtrInput
	// A URL pointing to the .well-known configuration of the OIDC provider.
	DiscoverUrl pulumi.StringInput
	// Whether or not OIDC is enabled.
	Enabled pulumi.BoolInput
	// The OIDC secret.
	Secret pulumi.StringInput
}

func (OidcArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*oidcArgs)(nil)).Elem()
}

type OidcInput interface {
	pulumi.Input

	ToOidcOutput() OidcOutput
	ToOidcOutputWithContext(ctx context.Context) OidcOutput
}

func (*Oidc) ElementType() reflect.Type {
	return reflect.TypeOf((**Oidc)(nil)).Elem()
}

func (i *Oidc) ToOidcOutput() OidcOutput {
	return i.ToOidcOutputWithContext(context.Background())
}

func (i *Oidc) ToOidcOutputWithContext(ctx context.Context) OidcOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OidcOutput)
}

// OidcArrayInput is an input type that accepts OidcArray and OidcArrayOutput values.
// You can construct a concrete instance of `OidcArrayInput` via:
//
//	OidcArray{ OidcArgs{...} }
type OidcArrayInput interface {
	pulumi.Input

	ToOidcArrayOutput() OidcArrayOutput
	ToOidcArrayOutputWithContext(context.Context) OidcArrayOutput
}

type OidcArray []OidcInput

func (OidcArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Oidc)(nil)).Elem()
}

func (i OidcArray) ToOidcArrayOutput() OidcArrayOutput {
	return i.ToOidcArrayOutputWithContext(context.Background())
}

func (i OidcArray) ToOidcArrayOutputWithContext(ctx context.Context) OidcArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OidcArrayOutput)
}

// OidcMapInput is an input type that accepts OidcMap and OidcMapOutput values.
// You can construct a concrete instance of `OidcMapInput` via:
//
//	OidcMap{ "key": OidcArgs{...} }
type OidcMapInput interface {
	pulumi.Input

	ToOidcMapOutput() OidcMapOutput
	ToOidcMapOutputWithContext(context.Context) OidcMapOutput
}

type OidcMap map[string]OidcInput

func (OidcMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Oidc)(nil)).Elem()
}

func (i OidcMap) ToOidcMapOutput() OidcMapOutput {
	return i.ToOidcMapOutputWithContext(context.Background())
}

func (i OidcMap) ToOidcMapOutputWithContext(ctx context.Context) OidcMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OidcMapOutput)
}

type OidcOutput struct{ *pulumi.OutputState }

func (OidcOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Oidc)(nil)).Elem()
}

func (o OidcOutput) ToOidcOutput() OidcOutput {
	return o
}

func (o OidcOutput) ToOidcOutputWithContext(ctx context.Context) OidcOutput {
	return o
}

// Whether to auto create users when they login to Unleash for the first time.
func (o OidcOutput) AutoCreate() pulumi.BoolOutput {
	return o.ApplyT(func(v *Oidc) pulumi.BoolOutput { return v.AutoCreate }).(pulumi.BoolOutput)
}

// The OIDC public identifier.
func (o OidcOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *Oidc) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

// The default root role give to a user when that user is created. Only used if autoCreate is set to true.
func (o OidcOutput) DefaultRootRole() pulumi.IntOutput {
	return o.ApplyT(func(v *Oidc) pulumi.IntOutput { return v.DefaultRootRole }).(pulumi.IntOutput)
}

// A URL pointing to the .well-known configuration of the OIDC provider.
func (o OidcOutput) DiscoverUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *Oidc) pulumi.StringOutput { return v.DiscoverUrl }).(pulumi.StringOutput)
}

// Whether or not OIDC is enabled.
func (o OidcOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *Oidc) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// The OIDC secret.
func (o OidcOutput) Secret() pulumi.StringOutput {
	return o.ApplyT(func(v *Oidc) pulumi.StringOutput { return v.Secret }).(pulumi.StringOutput)
}

type OidcArrayOutput struct{ *pulumi.OutputState }

func (OidcArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Oidc)(nil)).Elem()
}

func (o OidcArrayOutput) ToOidcArrayOutput() OidcArrayOutput {
	return o
}

func (o OidcArrayOutput) ToOidcArrayOutputWithContext(ctx context.Context) OidcArrayOutput {
	return o
}

func (o OidcArrayOutput) Index(i pulumi.IntInput) OidcOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Oidc {
		return vs[0].([]*Oidc)[vs[1].(int)]
	}).(OidcOutput)
}

type OidcMapOutput struct{ *pulumi.OutputState }

func (OidcMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Oidc)(nil)).Elem()
}

func (o OidcMapOutput) ToOidcMapOutput() OidcMapOutput {
	return o
}

func (o OidcMapOutput) ToOidcMapOutputWithContext(ctx context.Context) OidcMapOutput {
	return o
}

func (o OidcMapOutput) MapIndex(k pulumi.StringInput) OidcOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Oidc {
		return vs[0].(map[string]*Oidc)[vs[1].(string)]
	}).(OidcOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OidcInput)(nil)).Elem(), &Oidc{})
	pulumi.RegisterInputType(reflect.TypeOf((*OidcArrayInput)(nil)).Elem(), OidcArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*OidcMapInput)(nil)).Elem(), OidcMap{})
	pulumi.RegisterOutputType(OidcOutput{})
	pulumi.RegisterOutputType(OidcArrayOutput{})
	pulumi.RegisterOutputType(OidcMapOutput{})
}
