// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package unleash

import (
	"context"
	"reflect"

	"errors"
	"github.com/hagaym1/pulumi-unleash/sdk/v3/go/unleash/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ProjectEnvironment schema
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/hagaym1/pulumi-unleash/sdk/v3/go/unleash"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			project1, err := unleash.NewProject(ctx, "project_1", &unleash.ProjectArgs{
//				ProjectId:   pulumi.String("one"),
//				Name:        pulumi.String("First project"),
//				Description: pulumi.String("My first project"),
//			})
//			if err != nil {
//				return err
//			}
//			space, err := unleash.NewEnvironment(ctx, "space", &unleash.EnvironmentArgs{
//				Name: pulumi.String("outerspace"),
//				Type: pulumi.String("vacuum"),
//			})
//			if err != nil {
//				return err
//			}
//			_, err = unleash.NewProjectEnvironment(ctx, "space_environment", &unleash.ProjectEnvironmentArgs{
//				ProjectId:             project1.ProjectId,
//				EnvironmentName:       space.Name,
//				ChangeRequestsEnabled: pulumi.Bool(true),
//				RequiredApprovals:     pulumi.Int(2),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type ProjectEnvironment struct {
	pulumi.CustomResourceState

	// If change requests are required for this environment, the environment must be enabled for this to have effect.
	ChangeRequestsEnabled pulumi.BoolOutput `pulumi:"changeRequestsEnabled"`
	// Environment identifier, equivalent to the environment name.
	EnvironmentName pulumi.StringOutput `pulumi:"environmentName"`
	// Project identifier.
	ProjectId pulumi.StringOutput `pulumi:"projectId"`
	// Number of approvals required for change requests.
	RequiredApprovals pulumi.IntOutput `pulumi:"requiredApprovals"`
}

// NewProjectEnvironment registers a new resource with the given unique name, arguments, and options.
func NewProjectEnvironment(ctx *pulumi.Context,
	name string, args *ProjectEnvironmentArgs, opts ...pulumi.ResourceOption) (*ProjectEnvironment, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.EnvironmentName == nil {
		return nil, errors.New("invalid value for required argument 'EnvironmentName'")
	}
	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ProjectEnvironment
	err := ctx.RegisterResource("unleash:index/projectEnvironment:ProjectEnvironment", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetProjectEnvironment gets an existing ProjectEnvironment resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetProjectEnvironment(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ProjectEnvironmentState, opts ...pulumi.ResourceOption) (*ProjectEnvironment, error) {
	var resource ProjectEnvironment
	err := ctx.ReadResource("unleash:index/projectEnvironment:ProjectEnvironment", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ProjectEnvironment resources.
type projectEnvironmentState struct {
	// If change requests are required for this environment, the environment must be enabled for this to have effect.
	ChangeRequestsEnabled *bool `pulumi:"changeRequestsEnabled"`
	// Environment identifier, equivalent to the environment name.
	EnvironmentName *string `pulumi:"environmentName"`
	// Project identifier.
	ProjectId *string `pulumi:"projectId"`
	// Number of approvals required for change requests.
	RequiredApprovals *int `pulumi:"requiredApprovals"`
}

type ProjectEnvironmentState struct {
	// If change requests are required for this environment, the environment must be enabled for this to have effect.
	ChangeRequestsEnabled pulumi.BoolPtrInput
	// Environment identifier, equivalent to the environment name.
	EnvironmentName pulumi.StringPtrInput
	// Project identifier.
	ProjectId pulumi.StringPtrInput
	// Number of approvals required for change requests.
	RequiredApprovals pulumi.IntPtrInput
}

func (ProjectEnvironmentState) ElementType() reflect.Type {
	return reflect.TypeOf((*projectEnvironmentState)(nil)).Elem()
}

type projectEnvironmentArgs struct {
	// If change requests are required for this environment, the environment must be enabled for this to have effect.
	ChangeRequestsEnabled *bool `pulumi:"changeRequestsEnabled"`
	// Environment identifier, equivalent to the environment name.
	EnvironmentName string `pulumi:"environmentName"`
	// Project identifier.
	ProjectId string `pulumi:"projectId"`
	// Number of approvals required for change requests.
	RequiredApprovals *int `pulumi:"requiredApprovals"`
}

// The set of arguments for constructing a ProjectEnvironment resource.
type ProjectEnvironmentArgs struct {
	// If change requests are required for this environment, the environment must be enabled for this to have effect.
	ChangeRequestsEnabled pulumi.BoolPtrInput
	// Environment identifier, equivalent to the environment name.
	EnvironmentName pulumi.StringInput
	// Project identifier.
	ProjectId pulumi.StringInput
	// Number of approvals required for change requests.
	RequiredApprovals pulumi.IntPtrInput
}

func (ProjectEnvironmentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*projectEnvironmentArgs)(nil)).Elem()
}

type ProjectEnvironmentInput interface {
	pulumi.Input

	ToProjectEnvironmentOutput() ProjectEnvironmentOutput
	ToProjectEnvironmentOutputWithContext(ctx context.Context) ProjectEnvironmentOutput
}

func (*ProjectEnvironment) ElementType() reflect.Type {
	return reflect.TypeOf((**ProjectEnvironment)(nil)).Elem()
}

func (i *ProjectEnvironment) ToProjectEnvironmentOutput() ProjectEnvironmentOutput {
	return i.ToProjectEnvironmentOutputWithContext(context.Background())
}

func (i *ProjectEnvironment) ToProjectEnvironmentOutputWithContext(ctx context.Context) ProjectEnvironmentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectEnvironmentOutput)
}

// ProjectEnvironmentArrayInput is an input type that accepts ProjectEnvironmentArray and ProjectEnvironmentArrayOutput values.
// You can construct a concrete instance of `ProjectEnvironmentArrayInput` via:
//
//	ProjectEnvironmentArray{ ProjectEnvironmentArgs{...} }
type ProjectEnvironmentArrayInput interface {
	pulumi.Input

	ToProjectEnvironmentArrayOutput() ProjectEnvironmentArrayOutput
	ToProjectEnvironmentArrayOutputWithContext(context.Context) ProjectEnvironmentArrayOutput
}

type ProjectEnvironmentArray []ProjectEnvironmentInput

func (ProjectEnvironmentArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ProjectEnvironment)(nil)).Elem()
}

func (i ProjectEnvironmentArray) ToProjectEnvironmentArrayOutput() ProjectEnvironmentArrayOutput {
	return i.ToProjectEnvironmentArrayOutputWithContext(context.Background())
}

func (i ProjectEnvironmentArray) ToProjectEnvironmentArrayOutputWithContext(ctx context.Context) ProjectEnvironmentArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectEnvironmentArrayOutput)
}

// ProjectEnvironmentMapInput is an input type that accepts ProjectEnvironmentMap and ProjectEnvironmentMapOutput values.
// You can construct a concrete instance of `ProjectEnvironmentMapInput` via:
//
//	ProjectEnvironmentMap{ "key": ProjectEnvironmentArgs{...} }
type ProjectEnvironmentMapInput interface {
	pulumi.Input

	ToProjectEnvironmentMapOutput() ProjectEnvironmentMapOutput
	ToProjectEnvironmentMapOutputWithContext(context.Context) ProjectEnvironmentMapOutput
}

type ProjectEnvironmentMap map[string]ProjectEnvironmentInput

func (ProjectEnvironmentMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ProjectEnvironment)(nil)).Elem()
}

func (i ProjectEnvironmentMap) ToProjectEnvironmentMapOutput() ProjectEnvironmentMapOutput {
	return i.ToProjectEnvironmentMapOutputWithContext(context.Background())
}

func (i ProjectEnvironmentMap) ToProjectEnvironmentMapOutputWithContext(ctx context.Context) ProjectEnvironmentMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectEnvironmentMapOutput)
}

type ProjectEnvironmentOutput struct{ *pulumi.OutputState }

func (ProjectEnvironmentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ProjectEnvironment)(nil)).Elem()
}

func (o ProjectEnvironmentOutput) ToProjectEnvironmentOutput() ProjectEnvironmentOutput {
	return o
}

func (o ProjectEnvironmentOutput) ToProjectEnvironmentOutputWithContext(ctx context.Context) ProjectEnvironmentOutput {
	return o
}

// If change requests are required for this environment, the environment must be enabled for this to have effect.
func (o ProjectEnvironmentOutput) ChangeRequestsEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ProjectEnvironment) pulumi.BoolOutput { return v.ChangeRequestsEnabled }).(pulumi.BoolOutput)
}

// Environment identifier, equivalent to the environment name.
func (o ProjectEnvironmentOutput) EnvironmentName() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectEnvironment) pulumi.StringOutput { return v.EnvironmentName }).(pulumi.StringOutput)
}

// Project identifier.
func (o ProjectEnvironmentOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectEnvironment) pulumi.StringOutput { return v.ProjectId }).(pulumi.StringOutput)
}

// Number of approvals required for change requests.
func (o ProjectEnvironmentOutput) RequiredApprovals() pulumi.IntOutput {
	return o.ApplyT(func(v *ProjectEnvironment) pulumi.IntOutput { return v.RequiredApprovals }).(pulumi.IntOutput)
}

type ProjectEnvironmentArrayOutput struct{ *pulumi.OutputState }

func (ProjectEnvironmentArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ProjectEnvironment)(nil)).Elem()
}

func (o ProjectEnvironmentArrayOutput) ToProjectEnvironmentArrayOutput() ProjectEnvironmentArrayOutput {
	return o
}

func (o ProjectEnvironmentArrayOutput) ToProjectEnvironmentArrayOutputWithContext(ctx context.Context) ProjectEnvironmentArrayOutput {
	return o
}

func (o ProjectEnvironmentArrayOutput) Index(i pulumi.IntInput) ProjectEnvironmentOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ProjectEnvironment {
		return vs[0].([]*ProjectEnvironment)[vs[1].(int)]
	}).(ProjectEnvironmentOutput)
}

type ProjectEnvironmentMapOutput struct{ *pulumi.OutputState }

func (ProjectEnvironmentMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ProjectEnvironment)(nil)).Elem()
}

func (o ProjectEnvironmentMapOutput) ToProjectEnvironmentMapOutput() ProjectEnvironmentMapOutput {
	return o
}

func (o ProjectEnvironmentMapOutput) ToProjectEnvironmentMapOutputWithContext(ctx context.Context) ProjectEnvironmentMapOutput {
	return o
}

func (o ProjectEnvironmentMapOutput) MapIndex(k pulumi.StringInput) ProjectEnvironmentOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ProjectEnvironment {
		return vs[0].(map[string]*ProjectEnvironment)[vs[1].(string)]
	}).(ProjectEnvironmentOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectEnvironmentInput)(nil)).Elem(), &ProjectEnvironment{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectEnvironmentArrayInput)(nil)).Elem(), ProjectEnvironmentArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectEnvironmentMapInput)(nil)).Elem(), ProjectEnvironmentMap{})
	pulumi.RegisterOutputType(ProjectEnvironmentOutput{})
	pulumi.RegisterOutputType(ProjectEnvironmentArrayOutput{})
	pulumi.RegisterOutputType(ProjectEnvironmentMapOutput{})
}
