// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package unleash

import (
	"context"
	"reflect"

	"github.com/hagaym1/pulumi-unleash/sdk/v3/go/unleash/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type ContextFieldLegalValue struct {
	// Description of the allowed value.
	Description *string `pulumi:"description"`
	// The allowed value.
	Value string `pulumi:"value"`
}

// ContextFieldLegalValueInput is an input type that accepts ContextFieldLegalValueArgs and ContextFieldLegalValueOutput values.
// You can construct a concrete instance of `ContextFieldLegalValueInput` via:
//
//	ContextFieldLegalValueArgs{...}
type ContextFieldLegalValueInput interface {
	pulumi.Input

	ToContextFieldLegalValueOutput() ContextFieldLegalValueOutput
	ToContextFieldLegalValueOutputWithContext(context.Context) ContextFieldLegalValueOutput
}

type ContextFieldLegalValueArgs struct {
	// Description of the allowed value.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The allowed value.
	Value pulumi.StringInput `pulumi:"value"`
}

func (ContextFieldLegalValueArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ContextFieldLegalValue)(nil)).Elem()
}

func (i ContextFieldLegalValueArgs) ToContextFieldLegalValueOutput() ContextFieldLegalValueOutput {
	return i.ToContextFieldLegalValueOutputWithContext(context.Background())
}

func (i ContextFieldLegalValueArgs) ToContextFieldLegalValueOutputWithContext(ctx context.Context) ContextFieldLegalValueOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContextFieldLegalValueOutput)
}

// ContextFieldLegalValueArrayInput is an input type that accepts ContextFieldLegalValueArray and ContextFieldLegalValueArrayOutput values.
// You can construct a concrete instance of `ContextFieldLegalValueArrayInput` via:
//
//	ContextFieldLegalValueArray{ ContextFieldLegalValueArgs{...} }
type ContextFieldLegalValueArrayInput interface {
	pulumi.Input

	ToContextFieldLegalValueArrayOutput() ContextFieldLegalValueArrayOutput
	ToContextFieldLegalValueArrayOutputWithContext(context.Context) ContextFieldLegalValueArrayOutput
}

type ContextFieldLegalValueArray []ContextFieldLegalValueInput

func (ContextFieldLegalValueArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ContextFieldLegalValue)(nil)).Elem()
}

func (i ContextFieldLegalValueArray) ToContextFieldLegalValueArrayOutput() ContextFieldLegalValueArrayOutput {
	return i.ToContextFieldLegalValueArrayOutputWithContext(context.Background())
}

func (i ContextFieldLegalValueArray) ToContextFieldLegalValueArrayOutputWithContext(ctx context.Context) ContextFieldLegalValueArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContextFieldLegalValueArrayOutput)
}

type ContextFieldLegalValueOutput struct{ *pulumi.OutputState }

func (ContextFieldLegalValueOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ContextFieldLegalValue)(nil)).Elem()
}

func (o ContextFieldLegalValueOutput) ToContextFieldLegalValueOutput() ContextFieldLegalValueOutput {
	return o
}

func (o ContextFieldLegalValueOutput) ToContextFieldLegalValueOutputWithContext(ctx context.Context) ContextFieldLegalValueOutput {
	return o
}

// Description of the allowed value.
func (o ContextFieldLegalValueOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ContextFieldLegalValue) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The allowed value.
func (o ContextFieldLegalValueOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v ContextFieldLegalValue) string { return v.Value }).(pulumi.StringOutput)
}

type ContextFieldLegalValueArrayOutput struct{ *pulumi.OutputState }

func (ContextFieldLegalValueArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ContextFieldLegalValue)(nil)).Elem()
}

func (o ContextFieldLegalValueArrayOutput) ToContextFieldLegalValueArrayOutput() ContextFieldLegalValueArrayOutput {
	return o
}

func (o ContextFieldLegalValueArrayOutput) ToContextFieldLegalValueArrayOutputWithContext(ctx context.Context) ContextFieldLegalValueArrayOutput {
	return o
}

func (o ContextFieldLegalValueArrayOutput) Index(i pulumi.IntInput) ContextFieldLegalValueOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ContextFieldLegalValue {
		return vs[0].([]ContextFieldLegalValue)[vs[1].(int)]
	}).(ContextFieldLegalValueOutput)
}

type ProjectAccessRole struct {
	// List of projects with this role assigned.
	Groups []int `pulumi:"groups"`
	// The role identifier.
	Role int `pulumi:"role"`
	// List of users with this role assigned.
	Users []int `pulumi:"users"`
}

// ProjectAccessRoleInput is an input type that accepts ProjectAccessRoleArgs and ProjectAccessRoleOutput values.
// You can construct a concrete instance of `ProjectAccessRoleInput` via:
//
//	ProjectAccessRoleArgs{...}
type ProjectAccessRoleInput interface {
	pulumi.Input

	ToProjectAccessRoleOutput() ProjectAccessRoleOutput
	ToProjectAccessRoleOutputWithContext(context.Context) ProjectAccessRoleOutput
}

type ProjectAccessRoleArgs struct {
	// List of projects with this role assigned.
	Groups pulumi.IntArrayInput `pulumi:"groups"`
	// The role identifier.
	Role pulumi.IntInput `pulumi:"role"`
	// List of users with this role assigned.
	Users pulumi.IntArrayInput `pulumi:"users"`
}

func (ProjectAccessRoleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ProjectAccessRole)(nil)).Elem()
}

func (i ProjectAccessRoleArgs) ToProjectAccessRoleOutput() ProjectAccessRoleOutput {
	return i.ToProjectAccessRoleOutputWithContext(context.Background())
}

func (i ProjectAccessRoleArgs) ToProjectAccessRoleOutputWithContext(ctx context.Context) ProjectAccessRoleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectAccessRoleOutput)
}

// ProjectAccessRoleArrayInput is an input type that accepts ProjectAccessRoleArray and ProjectAccessRoleArrayOutput values.
// You can construct a concrete instance of `ProjectAccessRoleArrayInput` via:
//
//	ProjectAccessRoleArray{ ProjectAccessRoleArgs{...} }
type ProjectAccessRoleArrayInput interface {
	pulumi.Input

	ToProjectAccessRoleArrayOutput() ProjectAccessRoleArrayOutput
	ToProjectAccessRoleArrayOutputWithContext(context.Context) ProjectAccessRoleArrayOutput
}

type ProjectAccessRoleArray []ProjectAccessRoleInput

func (ProjectAccessRoleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ProjectAccessRole)(nil)).Elem()
}

func (i ProjectAccessRoleArray) ToProjectAccessRoleArrayOutput() ProjectAccessRoleArrayOutput {
	return i.ToProjectAccessRoleArrayOutputWithContext(context.Background())
}

func (i ProjectAccessRoleArray) ToProjectAccessRoleArrayOutputWithContext(ctx context.Context) ProjectAccessRoleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectAccessRoleArrayOutput)
}

type ProjectAccessRoleOutput struct{ *pulumi.OutputState }

func (ProjectAccessRoleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ProjectAccessRole)(nil)).Elem()
}

func (o ProjectAccessRoleOutput) ToProjectAccessRoleOutput() ProjectAccessRoleOutput {
	return o
}

func (o ProjectAccessRoleOutput) ToProjectAccessRoleOutputWithContext(ctx context.Context) ProjectAccessRoleOutput {
	return o
}

// List of projects with this role assigned.
func (o ProjectAccessRoleOutput) Groups() pulumi.IntArrayOutput {
	return o.ApplyT(func(v ProjectAccessRole) []int { return v.Groups }).(pulumi.IntArrayOutput)
}

// The role identifier.
func (o ProjectAccessRoleOutput) Role() pulumi.IntOutput {
	return o.ApplyT(func(v ProjectAccessRole) int { return v.Role }).(pulumi.IntOutput)
}

// List of users with this role assigned.
func (o ProjectAccessRoleOutput) Users() pulumi.IntArrayOutput {
	return o.ApplyT(func(v ProjectAccessRole) []int { return v.Users }).(pulumi.IntArrayOutput)
}

type ProjectAccessRoleArrayOutput struct{ *pulumi.OutputState }

func (ProjectAccessRoleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ProjectAccessRole)(nil)).Elem()
}

func (o ProjectAccessRoleArrayOutput) ToProjectAccessRoleArrayOutput() ProjectAccessRoleArrayOutput {
	return o
}

func (o ProjectAccessRoleArrayOutput) ToProjectAccessRoleArrayOutputWithContext(ctx context.Context) ProjectAccessRoleArrayOutput {
	return o
}

func (o ProjectAccessRoleArrayOutput) Index(i pulumi.IntInput) ProjectAccessRoleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ProjectAccessRole {
		return vs[0].([]ProjectAccessRole)[vs[1].(int)]
	}).(ProjectAccessRoleOutput)
}

type ProjectFeatureNaming struct {
	// A human-readable description of the pattern.
	Description *string `pulumi:"description"`
	// An example feature name that matches the pattern.
	Example *string `pulumi:"example"`
	// A JavaScript regular expression pattern, without the start and end delimiters.
	Pattern string `pulumi:"pattern"`
}

// ProjectFeatureNamingInput is an input type that accepts ProjectFeatureNamingArgs and ProjectFeatureNamingOutput values.
// You can construct a concrete instance of `ProjectFeatureNamingInput` via:
//
//	ProjectFeatureNamingArgs{...}
type ProjectFeatureNamingInput interface {
	pulumi.Input

	ToProjectFeatureNamingOutput() ProjectFeatureNamingOutput
	ToProjectFeatureNamingOutputWithContext(context.Context) ProjectFeatureNamingOutput
}

type ProjectFeatureNamingArgs struct {
	// A human-readable description of the pattern.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// An example feature name that matches the pattern.
	Example pulumi.StringPtrInput `pulumi:"example"`
	// A JavaScript regular expression pattern, without the start and end delimiters.
	Pattern pulumi.StringInput `pulumi:"pattern"`
}

func (ProjectFeatureNamingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ProjectFeatureNaming)(nil)).Elem()
}

func (i ProjectFeatureNamingArgs) ToProjectFeatureNamingOutput() ProjectFeatureNamingOutput {
	return i.ToProjectFeatureNamingOutputWithContext(context.Background())
}

func (i ProjectFeatureNamingArgs) ToProjectFeatureNamingOutputWithContext(ctx context.Context) ProjectFeatureNamingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectFeatureNamingOutput)
}

func (i ProjectFeatureNamingArgs) ToProjectFeatureNamingPtrOutput() ProjectFeatureNamingPtrOutput {
	return i.ToProjectFeatureNamingPtrOutputWithContext(context.Background())
}

func (i ProjectFeatureNamingArgs) ToProjectFeatureNamingPtrOutputWithContext(ctx context.Context) ProjectFeatureNamingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectFeatureNamingOutput).ToProjectFeatureNamingPtrOutputWithContext(ctx)
}

// ProjectFeatureNamingPtrInput is an input type that accepts ProjectFeatureNamingArgs, ProjectFeatureNamingPtr and ProjectFeatureNamingPtrOutput values.
// You can construct a concrete instance of `ProjectFeatureNamingPtrInput` via:
//
//	        ProjectFeatureNamingArgs{...}
//
//	or:
//
//	        nil
type ProjectFeatureNamingPtrInput interface {
	pulumi.Input

	ToProjectFeatureNamingPtrOutput() ProjectFeatureNamingPtrOutput
	ToProjectFeatureNamingPtrOutputWithContext(context.Context) ProjectFeatureNamingPtrOutput
}

type projectFeatureNamingPtrType ProjectFeatureNamingArgs

func ProjectFeatureNamingPtr(v *ProjectFeatureNamingArgs) ProjectFeatureNamingPtrInput {
	return (*projectFeatureNamingPtrType)(v)
}

func (*projectFeatureNamingPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ProjectFeatureNaming)(nil)).Elem()
}

func (i *projectFeatureNamingPtrType) ToProjectFeatureNamingPtrOutput() ProjectFeatureNamingPtrOutput {
	return i.ToProjectFeatureNamingPtrOutputWithContext(context.Background())
}

func (i *projectFeatureNamingPtrType) ToProjectFeatureNamingPtrOutputWithContext(ctx context.Context) ProjectFeatureNamingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectFeatureNamingPtrOutput)
}

type ProjectFeatureNamingOutput struct{ *pulumi.OutputState }

func (ProjectFeatureNamingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ProjectFeatureNaming)(nil)).Elem()
}

func (o ProjectFeatureNamingOutput) ToProjectFeatureNamingOutput() ProjectFeatureNamingOutput {
	return o
}

func (o ProjectFeatureNamingOutput) ToProjectFeatureNamingOutputWithContext(ctx context.Context) ProjectFeatureNamingOutput {
	return o
}

func (o ProjectFeatureNamingOutput) ToProjectFeatureNamingPtrOutput() ProjectFeatureNamingPtrOutput {
	return o.ToProjectFeatureNamingPtrOutputWithContext(context.Background())
}

func (o ProjectFeatureNamingOutput) ToProjectFeatureNamingPtrOutputWithContext(ctx context.Context) ProjectFeatureNamingPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ProjectFeatureNaming) *ProjectFeatureNaming {
		return &v
	}).(ProjectFeatureNamingPtrOutput)
}

// A human-readable description of the pattern.
func (o ProjectFeatureNamingOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ProjectFeatureNaming) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// An example feature name that matches the pattern.
func (o ProjectFeatureNamingOutput) Example() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ProjectFeatureNaming) *string { return v.Example }).(pulumi.StringPtrOutput)
}

// A JavaScript regular expression pattern, without the start and end delimiters.
func (o ProjectFeatureNamingOutput) Pattern() pulumi.StringOutput {
	return o.ApplyT(func(v ProjectFeatureNaming) string { return v.Pattern }).(pulumi.StringOutput)
}

type ProjectFeatureNamingPtrOutput struct{ *pulumi.OutputState }

func (ProjectFeatureNamingPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ProjectFeatureNaming)(nil)).Elem()
}

func (o ProjectFeatureNamingPtrOutput) ToProjectFeatureNamingPtrOutput() ProjectFeatureNamingPtrOutput {
	return o
}

func (o ProjectFeatureNamingPtrOutput) ToProjectFeatureNamingPtrOutputWithContext(ctx context.Context) ProjectFeatureNamingPtrOutput {
	return o
}

func (o ProjectFeatureNamingPtrOutput) Elem() ProjectFeatureNamingOutput {
	return o.ApplyT(func(v *ProjectFeatureNaming) ProjectFeatureNaming {
		if v != nil {
			return *v
		}
		var ret ProjectFeatureNaming
		return ret
	}).(ProjectFeatureNamingOutput)
}

// A human-readable description of the pattern.
func (o ProjectFeatureNamingPtrOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProjectFeatureNaming) *string {
		if v == nil {
			return nil
		}
		return v.Description
	}).(pulumi.StringPtrOutput)
}

// An example feature name that matches the pattern.
func (o ProjectFeatureNamingPtrOutput) Example() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProjectFeatureNaming) *string {
		if v == nil {
			return nil
		}
		return v.Example
	}).(pulumi.StringPtrOutput)
}

// A JavaScript regular expression pattern, without the start and end delimiters.
func (o ProjectFeatureNamingPtrOutput) Pattern() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProjectFeatureNaming) *string {
		if v == nil {
			return nil
		}
		return &v.Pattern
	}).(pulumi.StringPtrOutput)
}

type ProjectLinkTemplate struct {
	// Link title shown in the Unleash UI.
	Title *string `pulumi:"title"`
	// URL template that can contain {{project}} or {{feature}} placeholders.
	UrlTemplate string `pulumi:"urlTemplate"`
}

// ProjectLinkTemplateInput is an input type that accepts ProjectLinkTemplateArgs and ProjectLinkTemplateOutput values.
// You can construct a concrete instance of `ProjectLinkTemplateInput` via:
//
//	ProjectLinkTemplateArgs{...}
type ProjectLinkTemplateInput interface {
	pulumi.Input

	ToProjectLinkTemplateOutput() ProjectLinkTemplateOutput
	ToProjectLinkTemplateOutputWithContext(context.Context) ProjectLinkTemplateOutput
}

type ProjectLinkTemplateArgs struct {
	// Link title shown in the Unleash UI.
	Title pulumi.StringPtrInput `pulumi:"title"`
	// URL template that can contain {{project}} or {{feature}} placeholders.
	UrlTemplate pulumi.StringInput `pulumi:"urlTemplate"`
}

func (ProjectLinkTemplateArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ProjectLinkTemplate)(nil)).Elem()
}

func (i ProjectLinkTemplateArgs) ToProjectLinkTemplateOutput() ProjectLinkTemplateOutput {
	return i.ToProjectLinkTemplateOutputWithContext(context.Background())
}

func (i ProjectLinkTemplateArgs) ToProjectLinkTemplateOutputWithContext(ctx context.Context) ProjectLinkTemplateOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectLinkTemplateOutput)
}

// ProjectLinkTemplateArrayInput is an input type that accepts ProjectLinkTemplateArray and ProjectLinkTemplateArrayOutput values.
// You can construct a concrete instance of `ProjectLinkTemplateArrayInput` via:
//
//	ProjectLinkTemplateArray{ ProjectLinkTemplateArgs{...} }
type ProjectLinkTemplateArrayInput interface {
	pulumi.Input

	ToProjectLinkTemplateArrayOutput() ProjectLinkTemplateArrayOutput
	ToProjectLinkTemplateArrayOutputWithContext(context.Context) ProjectLinkTemplateArrayOutput
}

type ProjectLinkTemplateArray []ProjectLinkTemplateInput

func (ProjectLinkTemplateArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ProjectLinkTemplate)(nil)).Elem()
}

func (i ProjectLinkTemplateArray) ToProjectLinkTemplateArrayOutput() ProjectLinkTemplateArrayOutput {
	return i.ToProjectLinkTemplateArrayOutputWithContext(context.Background())
}

func (i ProjectLinkTemplateArray) ToProjectLinkTemplateArrayOutputWithContext(ctx context.Context) ProjectLinkTemplateArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectLinkTemplateArrayOutput)
}

type ProjectLinkTemplateOutput struct{ *pulumi.OutputState }

func (ProjectLinkTemplateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ProjectLinkTemplate)(nil)).Elem()
}

func (o ProjectLinkTemplateOutput) ToProjectLinkTemplateOutput() ProjectLinkTemplateOutput {
	return o
}

func (o ProjectLinkTemplateOutput) ToProjectLinkTemplateOutputWithContext(ctx context.Context) ProjectLinkTemplateOutput {
	return o
}

// Link title shown in the Unleash UI.
func (o ProjectLinkTemplateOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ProjectLinkTemplate) *string { return v.Title }).(pulumi.StringPtrOutput)
}

// URL template that can contain {{project}} or {{feature}} placeholders.
func (o ProjectLinkTemplateOutput) UrlTemplate() pulumi.StringOutput {
	return o.ApplyT(func(v ProjectLinkTemplate) string { return v.UrlTemplate }).(pulumi.StringOutput)
}

type ProjectLinkTemplateArrayOutput struct{ *pulumi.OutputState }

func (ProjectLinkTemplateArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ProjectLinkTemplate)(nil)).Elem()
}

func (o ProjectLinkTemplateArrayOutput) ToProjectLinkTemplateArrayOutput() ProjectLinkTemplateArrayOutput {
	return o
}

func (o ProjectLinkTemplateArrayOutput) ToProjectLinkTemplateArrayOutputWithContext(ctx context.Context) ProjectLinkTemplateArrayOutput {
	return o
}

func (o ProjectLinkTemplateArrayOutput) Index(i pulumi.IntInput) ProjectLinkTemplateOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ProjectLinkTemplate {
		return vs[0].([]ProjectLinkTemplate)[vs[1].(int)]
	}).(ProjectLinkTemplateOutput)
}

type RolePermission struct {
	// For which environment this permission applies (note that only environment-type permissions can have an environment).
	Environment *string `pulumi:"environment"`
	// The name of this permission.
	Name string `pulumi:"name"`
}

// RolePermissionInput is an input type that accepts RolePermissionArgs and RolePermissionOutput values.
// You can construct a concrete instance of `RolePermissionInput` via:
//
//	RolePermissionArgs{...}
type RolePermissionInput interface {
	pulumi.Input

	ToRolePermissionOutput() RolePermissionOutput
	ToRolePermissionOutputWithContext(context.Context) RolePermissionOutput
}

type RolePermissionArgs struct {
	// For which environment this permission applies (note that only environment-type permissions can have an environment).
	Environment pulumi.StringPtrInput `pulumi:"environment"`
	// The name of this permission.
	Name pulumi.StringInput `pulumi:"name"`
}

func (RolePermissionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*RolePermission)(nil)).Elem()
}

func (i RolePermissionArgs) ToRolePermissionOutput() RolePermissionOutput {
	return i.ToRolePermissionOutputWithContext(context.Background())
}

func (i RolePermissionArgs) ToRolePermissionOutputWithContext(ctx context.Context) RolePermissionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RolePermissionOutput)
}

// RolePermissionArrayInput is an input type that accepts RolePermissionArray and RolePermissionArrayOutput values.
// You can construct a concrete instance of `RolePermissionArrayInput` via:
//
//	RolePermissionArray{ RolePermissionArgs{...} }
type RolePermissionArrayInput interface {
	pulumi.Input

	ToRolePermissionArrayOutput() RolePermissionArrayOutput
	ToRolePermissionArrayOutputWithContext(context.Context) RolePermissionArrayOutput
}

type RolePermissionArray []RolePermissionInput

func (RolePermissionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]RolePermission)(nil)).Elem()
}

func (i RolePermissionArray) ToRolePermissionArrayOutput() RolePermissionArrayOutput {
	return i.ToRolePermissionArrayOutputWithContext(context.Background())
}

func (i RolePermissionArray) ToRolePermissionArrayOutputWithContext(ctx context.Context) RolePermissionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RolePermissionArrayOutput)
}

type RolePermissionOutput struct{ *pulumi.OutputState }

func (RolePermissionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RolePermission)(nil)).Elem()
}

func (o RolePermissionOutput) ToRolePermissionOutput() RolePermissionOutput {
	return o
}

func (o RolePermissionOutput) ToRolePermissionOutputWithContext(ctx context.Context) RolePermissionOutput {
	return o
}

// For which environment this permission applies (note that only environment-type permissions can have an environment).
func (o RolePermissionOutput) Environment() pulumi.StringPtrOutput {
	return o.ApplyT(func(v RolePermission) *string { return v.Environment }).(pulumi.StringPtrOutput)
}

// The name of this permission.
func (o RolePermissionOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v RolePermission) string { return v.Name }).(pulumi.StringOutput)
}

type RolePermissionArrayOutput struct{ *pulumi.OutputState }

func (RolePermissionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]RolePermission)(nil)).Elem()
}

func (o RolePermissionArrayOutput) ToRolePermissionArrayOutput() RolePermissionArrayOutput {
	return o
}

func (o RolePermissionArrayOutput) ToRolePermissionArrayOutputWithContext(ctx context.Context) RolePermissionArrayOutput {
	return o
}

func (o RolePermissionArrayOutput) Index(i pulumi.IntInput) RolePermissionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) RolePermission {
		return vs[0].([]RolePermission)[vs[1].(int)]
	}).(RolePermissionOutput)
}

type GetContextFieldLegalValue struct {
	// Description of the allowed value.
	Description string `pulumi:"description"`
	// The allowed value.
	Value string `pulumi:"value"`
}

// GetContextFieldLegalValueInput is an input type that accepts GetContextFieldLegalValueArgs and GetContextFieldLegalValueOutput values.
// You can construct a concrete instance of `GetContextFieldLegalValueInput` via:
//
//	GetContextFieldLegalValueArgs{...}
type GetContextFieldLegalValueInput interface {
	pulumi.Input

	ToGetContextFieldLegalValueOutput() GetContextFieldLegalValueOutput
	ToGetContextFieldLegalValueOutputWithContext(context.Context) GetContextFieldLegalValueOutput
}

type GetContextFieldLegalValueArgs struct {
	// Description of the allowed value.
	Description pulumi.StringInput `pulumi:"description"`
	// The allowed value.
	Value pulumi.StringInput `pulumi:"value"`
}

func (GetContextFieldLegalValueArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetContextFieldLegalValue)(nil)).Elem()
}

func (i GetContextFieldLegalValueArgs) ToGetContextFieldLegalValueOutput() GetContextFieldLegalValueOutput {
	return i.ToGetContextFieldLegalValueOutputWithContext(context.Background())
}

func (i GetContextFieldLegalValueArgs) ToGetContextFieldLegalValueOutputWithContext(ctx context.Context) GetContextFieldLegalValueOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetContextFieldLegalValueOutput)
}

// GetContextFieldLegalValueArrayInput is an input type that accepts GetContextFieldLegalValueArray and GetContextFieldLegalValueArrayOutput values.
// You can construct a concrete instance of `GetContextFieldLegalValueArrayInput` via:
//
//	GetContextFieldLegalValueArray{ GetContextFieldLegalValueArgs{...} }
type GetContextFieldLegalValueArrayInput interface {
	pulumi.Input

	ToGetContextFieldLegalValueArrayOutput() GetContextFieldLegalValueArrayOutput
	ToGetContextFieldLegalValueArrayOutputWithContext(context.Context) GetContextFieldLegalValueArrayOutput
}

type GetContextFieldLegalValueArray []GetContextFieldLegalValueInput

func (GetContextFieldLegalValueArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetContextFieldLegalValue)(nil)).Elem()
}

func (i GetContextFieldLegalValueArray) ToGetContextFieldLegalValueArrayOutput() GetContextFieldLegalValueArrayOutput {
	return i.ToGetContextFieldLegalValueArrayOutputWithContext(context.Background())
}

func (i GetContextFieldLegalValueArray) ToGetContextFieldLegalValueArrayOutputWithContext(ctx context.Context) GetContextFieldLegalValueArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetContextFieldLegalValueArrayOutput)
}

type GetContextFieldLegalValueOutput struct{ *pulumi.OutputState }

func (GetContextFieldLegalValueOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetContextFieldLegalValue)(nil)).Elem()
}

func (o GetContextFieldLegalValueOutput) ToGetContextFieldLegalValueOutput() GetContextFieldLegalValueOutput {
	return o
}

func (o GetContextFieldLegalValueOutput) ToGetContextFieldLegalValueOutputWithContext(ctx context.Context) GetContextFieldLegalValueOutput {
	return o
}

// Description of the allowed value.
func (o GetContextFieldLegalValueOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetContextFieldLegalValue) string { return v.Description }).(pulumi.StringOutput)
}

// The allowed value.
func (o GetContextFieldLegalValueOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v GetContextFieldLegalValue) string { return v.Value }).(pulumi.StringOutput)
}

type GetContextFieldLegalValueArrayOutput struct{ *pulumi.OutputState }

func (GetContextFieldLegalValueArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetContextFieldLegalValue)(nil)).Elem()
}

func (o GetContextFieldLegalValueArrayOutput) ToGetContextFieldLegalValueArrayOutput() GetContextFieldLegalValueArrayOutput {
	return o
}

func (o GetContextFieldLegalValueArrayOutput) ToGetContextFieldLegalValueArrayOutputWithContext(ctx context.Context) GetContextFieldLegalValueArrayOutput {
	return o
}

func (o GetContextFieldLegalValueArrayOutput) Index(i pulumi.IntInput) GetContextFieldLegalValueOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetContextFieldLegalValue {
		return vs[0].([]GetContextFieldLegalValue)[vs[1].(int)]
	}).(GetContextFieldLegalValueOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ContextFieldLegalValueInput)(nil)).Elem(), ContextFieldLegalValueArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ContextFieldLegalValueArrayInput)(nil)).Elem(), ContextFieldLegalValueArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectAccessRoleInput)(nil)).Elem(), ProjectAccessRoleArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectAccessRoleArrayInput)(nil)).Elem(), ProjectAccessRoleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectFeatureNamingInput)(nil)).Elem(), ProjectFeatureNamingArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectFeatureNamingPtrInput)(nil)).Elem(), ProjectFeatureNamingArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectLinkTemplateInput)(nil)).Elem(), ProjectLinkTemplateArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectLinkTemplateArrayInput)(nil)).Elem(), ProjectLinkTemplateArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RolePermissionInput)(nil)).Elem(), RolePermissionArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*RolePermissionArrayInput)(nil)).Elem(), RolePermissionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetContextFieldLegalValueInput)(nil)).Elem(), GetContextFieldLegalValueArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetContextFieldLegalValueArrayInput)(nil)).Elem(), GetContextFieldLegalValueArray{})
	pulumi.RegisterOutputType(ContextFieldLegalValueOutput{})
	pulumi.RegisterOutputType(ContextFieldLegalValueArrayOutput{})
	pulumi.RegisterOutputType(ProjectAccessRoleOutput{})
	pulumi.RegisterOutputType(ProjectAccessRoleArrayOutput{})
	pulumi.RegisterOutputType(ProjectFeatureNamingOutput{})
	pulumi.RegisterOutputType(ProjectFeatureNamingPtrOutput{})
	pulumi.RegisterOutputType(ProjectLinkTemplateOutput{})
	pulumi.RegisterOutputType(ProjectLinkTemplateArrayOutput{})
	pulumi.RegisterOutputType(RolePermissionOutput{})
	pulumi.RegisterOutputType(RolePermissionArrayOutput{})
	pulumi.RegisterOutputType(GetContextFieldLegalValueOutput{})
	pulumi.RegisterOutputType(GetContextFieldLegalValueArrayOutput{})
}
