// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package unleash

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-unleash/sdk/v3/go/unleash/internal"
)

// Role schema
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-unleash/sdk/v3/go/unleash"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := unleash.NewRole(ctx, "custom_root_role", &unleash.RoleArgs{
//				Name:        pulumi.String("A custom role"),
//				Type:        pulumi.String("root-custom"),
//				Description: pulumi.String("A custom test root role"),
//				Permissions: unleash.RolePermissionArray{
//					&unleash.RolePermissionArgs{
//						Name: pulumi.String("CREATE_PROJECT"),
//					},
//					&unleash.RolePermissionArgs{
//						Name: pulumi.String("UPDATE_PROJECT"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			_, err = unleash.NewRole(ctx, "renamed_custom_root_role", &unleash.RoleArgs{
//				Name:        pulumi.String("Renamed custom role"),
//				Type:        pulumi.String("root-custom"),
//				Description: pulumi.String("A custom test root role"),
//				Permissions: unleash.RolePermissionArray{
//					&unleash.RolePermissionArgs{
//						Name: pulumi.String("CREATE_SEGMENT"),
//					},
//					&unleash.RolePermissionArgs{
//						Name: pulumi.String("UPDATE_SEGMENT"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			_, err = unleash.NewRole(ctx, "project_role", &unleash.RoleArgs{
//				Name:        pulumi.String("Custom project role"),
//				Description: pulumi.String("A custom test project role"),
//				Type:        pulumi.String("custom"),
//				Permissions: unleash.RolePermissionArray{
//					&unleash.RolePermissionArgs{
//						Name: pulumi.String("CREATE_FEATURE"),
//					},
//					&unleash.RolePermissionArgs{
//						Name: pulumi.String("DELETE_FEATURE"),
//					},
//					&unleash.RolePermissionArgs{
//						Name:        pulumi.String("UPDATE_FEATURE_ENVIRONMENT"),
//						Environment: pulumi.String("development"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type Role struct {
	pulumi.CustomResourceState

	// A more detailed description of the role and what use it's intended for.
	Description pulumi.StringOutput `pulumi:"description"`
	// The name of this role.
	Name pulumi.StringOutput `pulumi:"name"`
	// A more detailed description of the role and what use it's intended for.
	Permissions RolePermissionArrayOutput `pulumi:"permissions"`
	// A role can either be a global root role (applies to all roles) or a role role.
	Type pulumi.StringOutput `pulumi:"type"`
}

// NewRole registers a new resource with the given unique name, arguments, and options.
func NewRole(ctx *pulumi.Context,
	name string, args *RoleArgs, opts ...pulumi.ResourceOption) (*Role, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Description == nil {
		return nil, errors.New("invalid value for required argument 'Description'")
	}
	if args.Permissions == nil {
		return nil, errors.New("invalid value for required argument 'Permissions'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Role
	err := ctx.RegisterResource("unleash:index/role:Role", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRole gets an existing Role resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRole(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RoleState, opts ...pulumi.ResourceOption) (*Role, error) {
	var resource Role
	err := ctx.ReadResource("unleash:index/role:Role", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Role resources.
type roleState struct {
	// A more detailed description of the role and what use it's intended for.
	Description *string `pulumi:"description"`
	// The name of this role.
	Name *string `pulumi:"name"`
	// A more detailed description of the role and what use it's intended for.
	Permissions []RolePermission `pulumi:"permissions"`
	// A role can either be a global root role (applies to all roles) or a role role.
	Type *string `pulumi:"type"`
}

type RoleState struct {
	// A more detailed description of the role and what use it's intended for.
	Description pulumi.StringPtrInput
	// The name of this role.
	Name pulumi.StringPtrInput
	// A more detailed description of the role and what use it's intended for.
	Permissions RolePermissionArrayInput
	// A role can either be a global root role (applies to all roles) or a role role.
	Type pulumi.StringPtrInput
}

func (RoleState) ElementType() reflect.Type {
	return reflect.TypeOf((*roleState)(nil)).Elem()
}

type roleArgs struct {
	// A more detailed description of the role and what use it's intended for.
	Description string `pulumi:"description"`
	// The name of this role.
	Name *string `pulumi:"name"`
	// A more detailed description of the role and what use it's intended for.
	Permissions []RolePermission `pulumi:"permissions"`
	// A role can either be a global root role (applies to all roles) or a role role.
	Type string `pulumi:"type"`
}

// The set of arguments for constructing a Role resource.
type RoleArgs struct {
	// A more detailed description of the role and what use it's intended for.
	Description pulumi.StringInput
	// The name of this role.
	Name pulumi.StringPtrInput
	// A more detailed description of the role and what use it's intended for.
	Permissions RolePermissionArrayInput
	// A role can either be a global root role (applies to all roles) or a role role.
	Type pulumi.StringInput
}

func (RoleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*roleArgs)(nil)).Elem()
}

type RoleInput interface {
	pulumi.Input

	ToRoleOutput() RoleOutput
	ToRoleOutputWithContext(ctx context.Context) RoleOutput
}

func (*Role) ElementType() reflect.Type {
	return reflect.TypeOf((**Role)(nil)).Elem()
}

func (i *Role) ToRoleOutput() RoleOutput {
	return i.ToRoleOutputWithContext(context.Background())
}

func (i *Role) ToRoleOutputWithContext(ctx context.Context) RoleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RoleOutput)
}

// RoleArrayInput is an input type that accepts RoleArray and RoleArrayOutput values.
// You can construct a concrete instance of `RoleArrayInput` via:
//
//	RoleArray{ RoleArgs{...} }
type RoleArrayInput interface {
	pulumi.Input

	ToRoleArrayOutput() RoleArrayOutput
	ToRoleArrayOutputWithContext(context.Context) RoleArrayOutput
}

type RoleArray []RoleInput

func (RoleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Role)(nil)).Elem()
}

func (i RoleArray) ToRoleArrayOutput() RoleArrayOutput {
	return i.ToRoleArrayOutputWithContext(context.Background())
}

func (i RoleArray) ToRoleArrayOutputWithContext(ctx context.Context) RoleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RoleArrayOutput)
}

// RoleMapInput is an input type that accepts RoleMap and RoleMapOutput values.
// You can construct a concrete instance of `RoleMapInput` via:
//
//	RoleMap{ "key": RoleArgs{...} }
type RoleMapInput interface {
	pulumi.Input

	ToRoleMapOutput() RoleMapOutput
	ToRoleMapOutputWithContext(context.Context) RoleMapOutput
}

type RoleMap map[string]RoleInput

func (RoleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Role)(nil)).Elem()
}

func (i RoleMap) ToRoleMapOutput() RoleMapOutput {
	return i.ToRoleMapOutputWithContext(context.Background())
}

func (i RoleMap) ToRoleMapOutputWithContext(ctx context.Context) RoleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RoleMapOutput)
}

type RoleOutput struct{ *pulumi.OutputState }

func (RoleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Role)(nil)).Elem()
}

func (o RoleOutput) ToRoleOutput() RoleOutput {
	return o
}

func (o RoleOutput) ToRoleOutputWithContext(ctx context.Context) RoleOutput {
	return o
}

// A more detailed description of the role and what use it's intended for.
func (o RoleOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *Role) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// The name of this role.
func (o RoleOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Role) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// A more detailed description of the role and what use it's intended for.
func (o RoleOutput) Permissions() RolePermissionArrayOutput {
	return o.ApplyT(func(v *Role) RolePermissionArrayOutput { return v.Permissions }).(RolePermissionArrayOutput)
}

// A role can either be a global root role (applies to all roles) or a role role.
func (o RoleOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *Role) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

type RoleArrayOutput struct{ *pulumi.OutputState }

func (RoleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Role)(nil)).Elem()
}

func (o RoleArrayOutput) ToRoleArrayOutput() RoleArrayOutput {
	return o
}

func (o RoleArrayOutput) ToRoleArrayOutputWithContext(ctx context.Context) RoleArrayOutput {
	return o
}

func (o RoleArrayOutput) Index(i pulumi.IntInput) RoleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Role {
		return vs[0].([]*Role)[vs[1].(int)]
	}).(RoleOutput)
}

type RoleMapOutput struct{ *pulumi.OutputState }

func (RoleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Role)(nil)).Elem()
}

func (o RoleMapOutput) ToRoleMapOutput() RoleMapOutput {
	return o
}

func (o RoleMapOutput) ToRoleMapOutputWithContext(ctx context.Context) RoleMapOutput {
	return o
}

func (o RoleMapOutput) MapIndex(k pulumi.StringInput) RoleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Role {
		return vs[0].(map[string]*Role)[vs[1].(string)]
	}).(RoleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RoleInput)(nil)).Elem(), &Role{})
	pulumi.RegisterInputType(reflect.TypeOf((*RoleArrayInput)(nil)).Elem(), RoleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RoleMapInput)(nil)).Elem(), RoleMap{})
	pulumi.RegisterOutputType(RoleOutput{})
	pulumi.RegisterOutputType(RoleArrayOutput{})
	pulumi.RegisterOutputType(RoleMapOutput{})
}
