// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package unleash

import (
	"context"
	"reflect"

	"errors"
	"github.com/hagaym1/pulumi-unleash/sdk/v3/go/unleash/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages SAML configuration.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/hagaym1/pulumi-unleash/sdk/v3/go/unleash"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := unleash.NewSaml(ctx, "simple_saml_config", &unleash.SamlArgs{
//				Enabled:         pulumi.Bool(true),
//				Certificate:     pulumi.String("test-certificate"),
//				EntityId:        pulumi.String("some-entity-id"),
//				SignOnUrl:       pulumi.String("http://other-places.com"),
//				AutoCreate:      pulumi.Bool(true),
//				DefaultRootRole: pulumi.Int(1),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type Saml struct {
	pulumi.CustomResourceState

	// Whether to auto create users when they login to Unleash for the first time.
	AutoCreate pulumi.BoolOutput `pulumi:"autoCreate"`
	// The x509 certificate used by the SAML provider.
	Certificate pulumi.StringOutput `pulumi:"certificate"`
	// The default root role give to a user when that user is created. Only used if autoCreate is set to true.
	DefaultRootRole pulumi.IntOutput `pulumi:"defaultRootRole"`
	// Whether SAML is enabled.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// The SAML entity ID.
	EntityId pulumi.StringOutput `pulumi:"entityId"`
	// The SAML sign-on URL.
	SignOnUrl pulumi.StringOutput `pulumi:"signOnUrl"`
}

// NewSaml registers a new resource with the given unique name, arguments, and options.
func NewSaml(ctx *pulumi.Context,
	name string, args *SamlArgs, opts ...pulumi.ResourceOption) (*Saml, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Certificate == nil {
		return nil, errors.New("invalid value for required argument 'Certificate'")
	}
	if args.Enabled == nil {
		return nil, errors.New("invalid value for required argument 'Enabled'")
	}
	if args.EntityId == nil {
		return nil, errors.New("invalid value for required argument 'EntityId'")
	}
	if args.SignOnUrl == nil {
		return nil, errors.New("invalid value for required argument 'SignOnUrl'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Saml
	err := ctx.RegisterResource("unleash:index/saml:Saml", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSaml gets an existing Saml resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSaml(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SamlState, opts ...pulumi.ResourceOption) (*Saml, error) {
	var resource Saml
	err := ctx.ReadResource("unleash:index/saml:Saml", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Saml resources.
type samlState struct {
	// Whether to auto create users when they login to Unleash for the first time.
	AutoCreate *bool `pulumi:"autoCreate"`
	// The x509 certificate used by the SAML provider.
	Certificate *string `pulumi:"certificate"`
	// The default root role give to a user when that user is created. Only used if autoCreate is set to true.
	DefaultRootRole *int `pulumi:"defaultRootRole"`
	// Whether SAML is enabled.
	Enabled *bool `pulumi:"enabled"`
	// The SAML entity ID.
	EntityId *string `pulumi:"entityId"`
	// The SAML sign-on URL.
	SignOnUrl *string `pulumi:"signOnUrl"`
}

type SamlState struct {
	// Whether to auto create users when they login to Unleash for the first time.
	AutoCreate pulumi.BoolPtrInput
	// The x509 certificate used by the SAML provider.
	Certificate pulumi.StringPtrInput
	// The default root role give to a user when that user is created. Only used if autoCreate is set to true.
	DefaultRootRole pulumi.IntPtrInput
	// Whether SAML is enabled.
	Enabled pulumi.BoolPtrInput
	// The SAML entity ID.
	EntityId pulumi.StringPtrInput
	// The SAML sign-on URL.
	SignOnUrl pulumi.StringPtrInput
}

func (SamlState) ElementType() reflect.Type {
	return reflect.TypeOf((*samlState)(nil)).Elem()
}

type samlArgs struct {
	// Whether to auto create users when they login to Unleash for the first time.
	AutoCreate *bool `pulumi:"autoCreate"`
	// The x509 certificate used by the SAML provider.
	Certificate string `pulumi:"certificate"`
	// The default root role give to a user when that user is created. Only used if autoCreate is set to true.
	DefaultRootRole *int `pulumi:"defaultRootRole"`
	// Whether SAML is enabled.
	Enabled bool `pulumi:"enabled"`
	// The SAML entity ID.
	EntityId string `pulumi:"entityId"`
	// The SAML sign-on URL.
	SignOnUrl string `pulumi:"signOnUrl"`
}

// The set of arguments for constructing a Saml resource.
type SamlArgs struct {
	// Whether to auto create users when they login to Unleash for the first time.
	AutoCreate pulumi.BoolPtrInput
	// The x509 certificate used by the SAML provider.
	Certificate pulumi.StringInput
	// The default root role give to a user when that user is created. Only used if autoCreate is set to true.
	DefaultRootRole pulumi.IntPtrInput
	// Whether SAML is enabled.
	Enabled pulumi.BoolInput
	// The SAML entity ID.
	EntityId pulumi.StringInput
	// The SAML sign-on URL.
	SignOnUrl pulumi.StringInput
}

func (SamlArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*samlArgs)(nil)).Elem()
}

type SamlInput interface {
	pulumi.Input

	ToSamlOutput() SamlOutput
	ToSamlOutputWithContext(ctx context.Context) SamlOutput
}

func (*Saml) ElementType() reflect.Type {
	return reflect.TypeOf((**Saml)(nil)).Elem()
}

func (i *Saml) ToSamlOutput() SamlOutput {
	return i.ToSamlOutputWithContext(context.Background())
}

func (i *Saml) ToSamlOutputWithContext(ctx context.Context) SamlOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SamlOutput)
}

// SamlArrayInput is an input type that accepts SamlArray and SamlArrayOutput values.
// You can construct a concrete instance of `SamlArrayInput` via:
//
//	SamlArray{ SamlArgs{...} }
type SamlArrayInput interface {
	pulumi.Input

	ToSamlArrayOutput() SamlArrayOutput
	ToSamlArrayOutputWithContext(context.Context) SamlArrayOutput
}

type SamlArray []SamlInput

func (SamlArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Saml)(nil)).Elem()
}

func (i SamlArray) ToSamlArrayOutput() SamlArrayOutput {
	return i.ToSamlArrayOutputWithContext(context.Background())
}

func (i SamlArray) ToSamlArrayOutputWithContext(ctx context.Context) SamlArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SamlArrayOutput)
}

// SamlMapInput is an input type that accepts SamlMap and SamlMapOutput values.
// You can construct a concrete instance of `SamlMapInput` via:
//
//	SamlMap{ "key": SamlArgs{...} }
type SamlMapInput interface {
	pulumi.Input

	ToSamlMapOutput() SamlMapOutput
	ToSamlMapOutputWithContext(context.Context) SamlMapOutput
}

type SamlMap map[string]SamlInput

func (SamlMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Saml)(nil)).Elem()
}

func (i SamlMap) ToSamlMapOutput() SamlMapOutput {
	return i.ToSamlMapOutputWithContext(context.Background())
}

func (i SamlMap) ToSamlMapOutputWithContext(ctx context.Context) SamlMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SamlMapOutput)
}

type SamlOutput struct{ *pulumi.OutputState }

func (SamlOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Saml)(nil)).Elem()
}

func (o SamlOutput) ToSamlOutput() SamlOutput {
	return o
}

func (o SamlOutput) ToSamlOutputWithContext(ctx context.Context) SamlOutput {
	return o
}

// Whether to auto create users when they login to Unleash for the first time.
func (o SamlOutput) AutoCreate() pulumi.BoolOutput {
	return o.ApplyT(func(v *Saml) pulumi.BoolOutput { return v.AutoCreate }).(pulumi.BoolOutput)
}

// The x509 certificate used by the SAML provider.
func (o SamlOutput) Certificate() pulumi.StringOutput {
	return o.ApplyT(func(v *Saml) pulumi.StringOutput { return v.Certificate }).(pulumi.StringOutput)
}

// The default root role give to a user when that user is created. Only used if autoCreate is set to true.
func (o SamlOutput) DefaultRootRole() pulumi.IntOutput {
	return o.ApplyT(func(v *Saml) pulumi.IntOutput { return v.DefaultRootRole }).(pulumi.IntOutput)
}

// Whether SAML is enabled.
func (o SamlOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *Saml) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// The SAML entity ID.
func (o SamlOutput) EntityId() pulumi.StringOutput {
	return o.ApplyT(func(v *Saml) pulumi.StringOutput { return v.EntityId }).(pulumi.StringOutput)
}

// The SAML sign-on URL.
func (o SamlOutput) SignOnUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *Saml) pulumi.StringOutput { return v.SignOnUrl }).(pulumi.StringOutput)
}

type SamlArrayOutput struct{ *pulumi.OutputState }

func (SamlArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Saml)(nil)).Elem()
}

func (o SamlArrayOutput) ToSamlArrayOutput() SamlArrayOutput {
	return o
}

func (o SamlArrayOutput) ToSamlArrayOutputWithContext(ctx context.Context) SamlArrayOutput {
	return o
}

func (o SamlArrayOutput) Index(i pulumi.IntInput) SamlOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Saml {
		return vs[0].([]*Saml)[vs[1].(int)]
	}).(SamlOutput)
}

type SamlMapOutput struct{ *pulumi.OutputState }

func (SamlMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Saml)(nil)).Elem()
}

func (o SamlMapOutput) ToSamlMapOutput() SamlMapOutput {
	return o
}

func (o SamlMapOutput) ToSamlMapOutputWithContext(ctx context.Context) SamlMapOutput {
	return o
}

func (o SamlMapOutput) MapIndex(k pulumi.StringInput) SamlOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Saml {
		return vs[0].(map[string]*Saml)[vs[1].(string)]
	}).(SamlOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SamlInput)(nil)).Elem(), &Saml{})
	pulumi.RegisterInputType(reflect.TypeOf((*SamlArrayInput)(nil)).Elem(), SamlArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SamlMapInput)(nil)).Elem(), SamlMap{})
	pulumi.RegisterOutputType(SamlOutput{})
	pulumi.RegisterOutputType(SamlArrayOutput{})
	pulumi.RegisterOutputType(SamlMapOutput{})
}
