// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Unleash.Inputs
{

    public sealed class ContextFieldLegalValueArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description of the allowed value.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The allowed value.
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public ContextFieldLegalValueArgs()
        {
        }
        public static new ContextFieldLegalValueArgs Empty => new ContextFieldLegalValueArgs();
    }
}
