// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Unleash.Inputs
{

    public sealed class GetContextFieldLegalValueInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description of the allowed value.
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        /// <summary>
        /// The allowed value.
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public GetContextFieldLegalValueInputArgs()
        {
        }
        public static new GetContextFieldLegalValueInputArgs Empty => new GetContextFieldLegalValueInputArgs();
    }
}
