// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Unleash.Inputs
{

    public sealed class GetContextFieldLegalValueArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Description of the allowed value.
        /// </summary>
        [Input("description", required: true)]
        public string Description { get; set; } = null!;

        /// <summary>
        /// The allowed value.
        /// </summary>
        [Input("value", required: true)]
        public string Value { get; set; } = null!;

        public GetContextFieldLegalValueArgs()
        {
        }
        public static new GetContextFieldLegalValueArgs Empty => new GetContextFieldLegalValueArgs();
    }
}
