// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Unleash.Inputs
{

    public sealed class ProjectAccessRoleArgs : global::Pulumi.ResourceArgs
    {
        [Input("groups", required: true)]
        private InputList<int>? _groups;

        /// <summary>
        /// List of projects with this role assigned.
        /// </summary>
        public InputList<int> Groups
        {
            get => _groups ?? (_groups = new InputList<int>());
            set => _groups = value;
        }

        /// <summary>
        /// The role identifier.
        /// </summary>
        [Input("role", required: true)]
        public Input<int> Role { get; set; } = null!;

        [Input("users", required: true)]
        private InputList<int>? _users;

        /// <summary>
        /// List of users with this role assigned.
        /// </summary>
        public InputList<int> Users
        {
            get => _users ?? (_users = new InputList<int>());
            set => _users = value;
        }

        public ProjectAccessRoleArgs()
        {
        }
        public static new ProjectAccessRoleArgs Empty => new ProjectAccessRoleArgs();
    }
}
