// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Unleash.Inputs
{

    public sealed class ProjectLinkTemplateGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Link title shown in the Unleash UI.
        /// </summary>
        [Input("title")]
        public Input<string>? Title { get; set; }

        /// <summary>
        /// URL template that can contain {{project}} or {{feature}} placeholders.
        /// </summary>
        [Input("urlTemplate", required: true)]
        public Input<string> UrlTemplate { get; set; } = null!;

        public ProjectLinkTemplateGetArgs()
        {
        }
        public static new ProjectLinkTemplateGetArgs Empty => new ProjectLinkTemplateGetArgs();
    }
}
