// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Fetch a context field.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as unleash from "@pulumiverse/unleash";
 *
 * const hamContextField = new unleash.ContextField("ham_context_field", {name: "ham"});
 * const cheeseContextField = new unleash.ContextField("cheese_context_field", {
 *     name: "cheese",
 *     stickiness: true,
 *     description: "Type of cheese to constrain on",
 *     legalValues: [{
 *         value: "brie",
 *         description: "Gooey, delicious",
 *     }],
 * });
 * ```
 */
export class ContextField extends pulumi.CustomResource {
    /**
     * Get an existing ContextField resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ContextFieldState, opts?: pulumi.CustomResourceOptions): ContextField {
        return new ContextField(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unleash:index/contextField:ContextField';

    /**
     * Returns true if the given object is an instance of ContextField.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ContextField {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ContextField.__pulumiType;
    }

    /**
     * A description of the context field.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Legal values for this context field. If not set, then any value is available for this context field.
     */
    declare public readonly legalValues: pulumi.Output<outputs.ContextFieldLegalValue[]>;
    /**
     * The name of the context field.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Whether this field is available for custom stickiness. Defaults to false if not set.
     */
    declare public readonly stickiness: pulumi.Output<boolean>;

    /**
     * Create a ContextField resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ContextFieldArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ContextFieldArgs | ContextFieldState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ContextFieldState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["legalValues"] = state?.legalValues;
            resourceInputs["name"] = state?.name;
            resourceInputs["stickiness"] = state?.stickiness;
        } else {
            const args = argsOrState as ContextFieldArgs | undefined;
            resourceInputs["description"] = args?.description;
            resourceInputs["legalValues"] = args?.legalValues;
            resourceInputs["name"] = args?.name;
            resourceInputs["stickiness"] = args?.stickiness;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ContextField.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ContextField resources.
 */
export interface ContextFieldState {
    /**
     * A description of the context field.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Legal values for this context field. If not set, then any value is available for this context field.
     */
    legalValues?: pulumi.Input<pulumi.Input<inputs.ContextFieldLegalValue>[] | undefined>;
    /**
     * The name of the context field.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Whether this field is available for custom stickiness. Defaults to false if not set.
     */
    stickiness?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a ContextField resource.
 */
export interface ContextFieldArgs {
    /**
     * A description of the context field.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Legal values for this context field. If not set, then any value is available for this context field.
     */
    legalValues?: pulumi.Input<pulumi.Input<inputs.ContextFieldLegalValue>[] | undefined>;
    /**
     * The name of the context field.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Whether this field is available for custom stickiness. Defaults to false if not set.
     */
    stickiness?: pulumi.Input<boolean | undefined>;
}
