// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ProjectEnvironment schema
 */
export function getProjectEnvironment(args: GetProjectEnvironmentArgs, opts?: pulumi.InvokeOptions): Promise<GetProjectEnvironmentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("unleash:index/getProjectEnvironment:getProjectEnvironment", {
        "environmentName": args.environmentName,
        "projectId": args.projectId,
    }, opts);
}

/**
 * A collection of arguments for invoking getProjectEnvironment.
 */
export interface GetProjectEnvironmentArgs {
    /**
     * Environment identifier, equivalent to the environment name.
     */
    environmentName: string;
    /**
     * Project identifier.
     */
    projectId: string;
}

/**
 * A collection of values returned by getProjectEnvironment.
 */
export interface GetProjectEnvironmentResult {
    /**
     * If change requests are required for this environment, the environment must be enabled for this to have effect.
     */
    readonly changeRequestsEnabled: boolean;
    /**
     * If the environment is enabled for this project. This affects whether or not users will be able to enable flags for this environment on this project.
     */
    readonly enabled: boolean;
    /**
     * Environment identifier, equivalent to the environment name.
     */
    readonly environmentName: string;
    /**
     * Project identifier.
     */
    readonly projectId: string;
    /**
     * Number of approvals required for change requests.
     */
    readonly requiredApprovals: number;
}
/**
 * ProjectEnvironment schema
 */
export function getProjectEnvironmentOutput(args: GetProjectEnvironmentOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetProjectEnvironmentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("unleash:index/getProjectEnvironment:getProjectEnvironment", {
        "environmentName": args.environmentName,
        "projectId": args.projectId,
    }, opts);
}

/**
 * A collection of arguments for invoking getProjectEnvironment.
 */
export interface GetProjectEnvironmentOutputArgs {
    /**
     * Environment identifier, equivalent to the environment name.
     */
    environmentName: pulumi.Input<string>;
    /**
     * Project identifier.
     */
    projectId: pulumi.Input<string>;
}
