// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Fetch a permission.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as unleash from "@pulumi/unleash";
 *
 * const createProject = unleash.getPermission({
 *     name: "CREATE_PROJECT",
 * });
 * const updateProject = unleash.getPermission({
 *     name: "UPDATE_PROJECT",
 * });
 * const createFeatureStrategy = unleash.getPermission({
 *     name: "CREATE_FEATURE_STRATEGY",
 *     environment: "development",
 * });
 * ```
 */
export function getPermission(args: GetPermissionArgs, opts?: pulumi.InvokeOptions): Promise<GetPermissionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("unleash:index/getPermission:getPermission", {
        "environment": args.environment,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getPermission.
 */
export interface GetPermissionArgs {
    /**
     * Which environment this permission applies to.
     */
    environment?: string;
    /**
     * The name of the permission.
     */
    name: string;
}

/**
 * A collection of values returned by getPermission.
 */
export interface GetPermissionResult {
    /**
     * The name to display in listings of permissions.
     */
    readonly displayName: string;
    /**
     * Which environment this permission applies to.
     */
    readonly environment?: string;
    /**
     * Identifier for this permission.
     */
    readonly id: number;
    /**
     * The name of the permission.
     */
    readonly name: string;
    /**
     * What level this permission applies to. Either root, project or the name of the environment it applies to.
     */
    readonly type: string;
}
/**
 * Fetch a permission.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as unleash from "@pulumi/unleash";
 *
 * const createProject = unleash.getPermission({
 *     name: "CREATE_PROJECT",
 * });
 * const updateProject = unleash.getPermission({
 *     name: "UPDATE_PROJECT",
 * });
 * const createFeatureStrategy = unleash.getPermission({
 *     name: "CREATE_FEATURE_STRATEGY",
 *     environment: "development",
 * });
 * ```
 */
export function getPermissionOutput(args: GetPermissionOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPermissionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("unleash:index/getPermission:getPermission", {
        "environment": args.environment,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getPermission.
 */
export interface GetPermissionOutputArgs {
    /**
     * Which environment this permission applies to.
     */
    environment?: pulumi.Input<string | undefined>;
    /**
     * The name of the permission.
     */
    name: pulumi.Input<string>;
}
