// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Fetch a role definition.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as unleash from "@pulumiverse/unleash";
 *
 * const adminRole = unleash.getRole({
 *     name: "Admin",
 * });
 * const editorRole = unleash.getRole({
 *     name: "Editor",
 * });
 * const projectMemberRole = unleash.getRole({
 *     name: "Member",
 * });
 * ```
 */
export function getRole(args: GetRoleArgs, opts?: pulumi.InvokeOptions): Promise<GetRoleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("unleash:index/getRole:getRole", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getRole.
 */
export interface GetRoleArgs {
    /**
     * The name of this role.
     */
    name: string;
}

/**
 * A collection of values returned by getRole.
 */
export interface GetRoleResult {
    /**
     * A more detailed description of the role and what use it's intended for.
     */
    readonly description: string;
    /**
     * The id of this role.
     */
    readonly id: number;
    /**
     * The name of this role.
     */
    readonly name: string;
    /**
     * A role can either be a global root role (applies to all roles) or a role role.
     */
    readonly type: string;
}
/**
 * Fetch a role definition.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as unleash from "@pulumiverse/unleash";
 *
 * const adminRole = unleash.getRole({
 *     name: "Admin",
 * });
 * const editorRole = unleash.getRole({
 *     name: "Editor",
 * });
 * const projectMemberRole = unleash.getRole({
 *     name: "Member",
 * });
 * ```
 */
export function getRoleOutput(args: GetRoleOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRoleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("unleash:index/getRole:getRole", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getRole.
 */
export interface GetRoleOutputArgs {
    /**
     * The name of this role.
     */
    name: pulumi.Input<string>;
}
