// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Fetch a user by id or email.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as unleash from "@pulumiverse/unleash";
 *
 * const admin = unleash.getUser({
 *     id: "1",
 * });
 * const searchByEmail = unleash.getUser({
 *     email: "byemail@example.com",
 * });
 * ```
 */
export function getUser(args?: GetUserArgs, opts?: pulumi.InvokeOptions): Promise<GetUserResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("unleash:index/getUser:getUser", {
        "email": args.email,
        "id": args.id,
        "name": args.name,
        "username": args.username,
    }, opts);
}

/**
 * A collection of arguments for invoking getUser.
 */
export interface GetUserArgs {
    /**
     * The email of the user.
     */
    email?: string;
    /**
     * Identifier for this user.
     */
    id?: string;
    /**
     * The name of the user.
     */
    name?: string;
    /**
     * The username of the user.
     */
    username?: string;
}

/**
 * A collection of values returned by getUser.
 */
export interface GetUserResult {
    /**
     * The email of the user.
     */
    readonly email: string;
    /**
     * Identifier for this user.
     */
    readonly id: string;
    /**
     * The name of the user.
     */
    readonly name: string;
    /**
     * The role id for the user.
     */
    readonly rootRole: number;
    /**
     * The username of the user.
     */
    readonly username: string;
}
/**
 * Fetch a user by id or email.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as unleash from "@pulumiverse/unleash";
 *
 * const admin = unleash.getUser({
 *     id: "1",
 * });
 * const searchByEmail = unleash.getUser({
 *     email: "byemail@example.com",
 * });
 * ```
 */
export function getUserOutput(args?: GetUserOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetUserResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("unleash:index/getUser:getUser", {
        "email": args.email,
        "id": args.id,
        "name": args.name,
        "username": args.username,
    }, opts);
}

/**
 * A collection of arguments for invoking getUser.
 */
export interface GetUserOutputArgs {
    /**
     * The email of the user.
     */
    email?: pulumi.Input<string | undefined>;
    /**
     * Identifier for this user.
     */
    id?: pulumi.Input<string | undefined>;
    /**
     * The name of the user.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The username of the user.
     */
    username?: pulumi.Input<string | undefined>;
}
