// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage an Unleash group. The mappingsSso attribute contains external SSO/IdP group names that should map users into this Unleash group.
 */
export class Group extends pulumi.CustomResource {
    /**
     * Get an existing Group resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GroupState, opts?: pulumi.CustomResourceOptions): Group {
        return new Group(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unleash:index/group:Group';

    /**
     * Returns true if the given object is an instance of Group.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Group {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Group.__pulumiType;
    }

    /**
     * A description of the group's purpose.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * External SSO/IdP group names that should map users into this Unleash group.
     */
    declare public readonly mappingsSsos: pulumi.Output<string[] | undefined>;
    /**
     * Name for this group
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The root role ID for this group.
     */
    declare public readonly rootRole: pulumi.Output<number | undefined>;
    /**
     * List of user IDs to add to this group
     */
    declare public readonly users: pulumi.Output<number[] | undefined>;

    /**
     * Create a Group resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: GroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GroupArgs | GroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GroupState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["mappingsSsos"] = state?.mappingsSsos;
            resourceInputs["name"] = state?.name;
            resourceInputs["rootRole"] = state?.rootRole;
            resourceInputs["users"] = state?.users;
        } else {
            const args = argsOrState as GroupArgs | undefined;
            resourceInputs["description"] = args?.description;
            resourceInputs["mappingsSsos"] = args?.mappingsSsos;
            resourceInputs["name"] = args?.name;
            resourceInputs["rootRole"] = args?.rootRole;
            resourceInputs["users"] = args?.users;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Group.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Group resources.
 */
export interface GroupState {
    /**
     * A description of the group's purpose.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * External SSO/IdP group names that should map users into this Unleash group.
     */
    mappingsSsos?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Name for this group
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The root role ID for this group.
     */
    rootRole?: pulumi.Input<number | undefined>;
    /**
     * List of user IDs to add to this group
     */
    users?: pulumi.Input<pulumi.Input<number>[] | undefined>;
}

/**
 * The set of arguments for constructing a Group resource.
 */
export interface GroupArgs {
    /**
     * A description of the group's purpose.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * External SSO/IdP group names that should map users into this Unleash group.
     */
    mappingsSsos?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Name for this group
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The root role ID for this group.
     */
    rootRole?: pulumi.Input<number | undefined>;
    /**
     * List of user IDs to add to this group
     */
    users?: pulumi.Input<pulumi.Input<number>[] | undefined>;
}
