// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages OIDC configuration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as unleash from "@pulumi/unleash";
 *
 * const simpleOidcConfig = new unleash.Oidc("simple_oidc_config", {
 *     enabled: true,
 *     discoverUrl: "http://mock-openid-server:9000/.well-known/openid-configuration",
 *     secret: "kinda-sorta-secret",
 *     clientId: "client-id",
 *     autoCreate: true,
 *     defaultRootRole: 1,
 * });
 * ```
 */
export class Oidc extends pulumi.CustomResource {
    /**
     * Get an existing Oidc resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OidcState, opts?: pulumi.CustomResourceOptions): Oidc {
        return new Oidc(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unleash:index/oidc:Oidc';

    /**
     * Returns true if the given object is an instance of Oidc.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Oidc {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Oidc.__pulumiType;
    }

    /**
     * Whether to auto create users when they login to Unleash for the first time.
     */
    declare public readonly autoCreate: pulumi.Output<boolean>;
    /**
     * The OIDC public identifier.
     */
    declare public readonly clientId: pulumi.Output<string>;
    /**
     * The default root role give to a user when that user is created. Only used if autoCreate is set to true.
     */
    declare public readonly defaultRootRole: pulumi.Output<number>;
    /**
     * A URL pointing to the .well-known configuration of the OIDC provider.
     */
    declare public readonly discoverUrl: pulumi.Output<string>;
    /**
     * Whether or not OIDC is enabled.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * The OIDC secret.
     */
    declare public readonly secret: pulumi.Output<string>;

    /**
     * Create a Oidc resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OidcArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OidcArgs | OidcState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OidcState | undefined;
            resourceInputs["autoCreate"] = state?.autoCreate;
            resourceInputs["clientId"] = state?.clientId;
            resourceInputs["defaultRootRole"] = state?.defaultRootRole;
            resourceInputs["discoverUrl"] = state?.discoverUrl;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["secret"] = state?.secret;
        } else {
            const args = argsOrState as OidcArgs | undefined;
            if (args?.clientId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientId'");
            }
            if (args?.discoverUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'discoverUrl'");
            }
            if (args?.enabled === undefined && !opts.urn) {
                throw new Error("Missing required property 'enabled'");
            }
            if (args?.secret === undefined && !opts.urn) {
                throw new Error("Missing required property 'secret'");
            }
            resourceInputs["autoCreate"] = args?.autoCreate;
            resourceInputs["clientId"] = args?.clientId;
            resourceInputs["defaultRootRole"] = args?.defaultRootRole;
            resourceInputs["discoverUrl"] = args?.discoverUrl;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["secret"] = args?.secret;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Oidc.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Oidc resources.
 */
export interface OidcState {
    /**
     * Whether to auto create users when they login to Unleash for the first time.
     */
    autoCreate?: pulumi.Input<boolean | undefined>;
    /**
     * The OIDC public identifier.
     */
    clientId?: pulumi.Input<string | undefined>;
    /**
     * The default root role give to a user when that user is created. Only used if autoCreate is set to true.
     */
    defaultRootRole?: pulumi.Input<number | undefined>;
    /**
     * A URL pointing to the .well-known configuration of the OIDC provider.
     */
    discoverUrl?: pulumi.Input<string | undefined>;
    /**
     * Whether or not OIDC is enabled.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * The OIDC secret.
     */
    secret?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Oidc resource.
 */
export interface OidcArgs {
    /**
     * Whether to auto create users when they login to Unleash for the first time.
     */
    autoCreate?: pulumi.Input<boolean | undefined>;
    /**
     * The OIDC public identifier.
     */
    clientId: pulumi.Input<string>;
    /**
     * The default root role give to a user when that user is created. Only used if autoCreate is set to true.
     */
    defaultRootRole?: pulumi.Input<number | undefined>;
    /**
     * A URL pointing to the .well-known configuration of the OIDC provider.
     */
    discoverUrl: pulumi.Input<string>;
    /**
     * Whether or not OIDC is enabled.
     */
    enabled: pulumi.Input<boolean>;
    /**
     * The OIDC secret.
     */
    secret: pulumi.Input<string>;
}
