// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Allows for managing the tokens bound to a service account. Note that service account tokens in Unleash
 * 		are both immutable and cannot be recovered once created. This means you must use them immediately when creating them via terraform.
 * 		Typically by piping them to an external secret manager or binding them to some other external terraform resource that requires Unleash tokens.
 *
 *         Because service account tokens are immutable, any changes to the terraform resource will trigger a deletion and recreation of those tokens,
 *         meaning that the secrets will be rotated out.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as _null from "@pulumi/null";
 * import * as command from "@pulumi/command";
 * import * as external from "@pulumi/external";
 * import * as unleash from "@pulumi/unleash";
 *
 * const accountForTokensTest = new unleash.ServiceAccount("account_for_tokens_test", {
 *     name: "the service account name",
 *     username: "some descriptive name",
 *     rootRole: 1,
 * });
 * const tokenForAccountTest = new unleash.ServiceAccountToken("token_for_account_test", {
 *     serviceAccountId: accountForTokensTest.id.apply(x =>Number(x)),
 *     description: "a token for the account",
 *     expiresAt: "2048-01-01T00:00:00Z",
 * });
 * //# This is a bare bones example to output the token to a file, this would be better off being sent to
 * //# a secret manager rather
 * const storeToken = new _null.index.Resource("store_token", {triggers: {
 *     tokenCreated: tokenForAccountTest.secret,
 * }});
 * const storeTokenProvisioner0 = new command.local.Command("storeTokenProvisioner0", {create: `      #!/bin/bash
 *       TOKEN_VALUE=\"${tokenForAccountTest.secret}\"
 *       echo \"Storing token: $TOKEN_VALUE\"
 *       echo \"$TOKEN_VALUE\" > /secure/location/service_account_token.txt
 * `}, {
 *     dependsOn: [storeToken],
 * });
 * //# Some external resource that requires an Unleash token for automation
 * const externalUnleashIntegration = new external.index.Resource("external_unleash_integration", {unleashApiKey: tokenForAccountTest.secret});
 * ```
 */
export class ServiceAccountToken extends pulumi.CustomResource {
    /**
     * Get an existing ServiceAccountToken resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServiceAccountTokenState, opts?: pulumi.CustomResourceOptions): ServiceAccountToken {
        return new ServiceAccountToken(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unleash:index/serviceAccountToken:ServiceAccountToken';

    /**
     * Returns true if the given object is an instance of ServiceAccountToken.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServiceAccountToken {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServiceAccountToken.__pulumiType;
    }

    /**
     * The description of the service account token.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * The expiration date of the service account token.
     */
    declare public readonly expiresAt: pulumi.Output<string>;
    /**
     * The secret of the service account token.
     */
    declare public /*out*/ readonly secret: pulumi.Output<string>;
    /**
     * The ID of the service account this token is bound to.
     */
    declare public readonly serviceAccountId: pulumi.Output<number>;

    /**
     * Create a ServiceAccountToken resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServiceAccountTokenArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServiceAccountTokenArgs | ServiceAccountTokenState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ServiceAccountTokenState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["expiresAt"] = state?.expiresAt;
            resourceInputs["secret"] = state?.secret;
            resourceInputs["serviceAccountId"] = state?.serviceAccountId;
        } else {
            const args = argsOrState as ServiceAccountTokenArgs | undefined;
            if (args?.description === undefined && !opts.urn) {
                throw new Error("Missing required property 'description'");
            }
            if (args?.expiresAt === undefined && !opts.urn) {
                throw new Error("Missing required property 'expiresAt'");
            }
            if (args?.serviceAccountId === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceAccountId'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["expiresAt"] = args?.expiresAt;
            resourceInputs["serviceAccountId"] = args?.serviceAccountId;
            resourceInputs["secret"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["secret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ServiceAccountToken.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ServiceAccountToken resources.
 */
export interface ServiceAccountTokenState {
    /**
     * The description of the service account token.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The expiration date of the service account token.
     */
    expiresAt?: pulumi.Input<string | undefined>;
    /**
     * The secret of the service account token.
     */
    secret?: pulumi.Input<string | undefined>;
    /**
     * The ID of the service account this token is bound to.
     */
    serviceAccountId?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a ServiceAccountToken resource.
 */
export interface ServiceAccountTokenArgs {
    /**
     * The description of the service account token.
     */
    description: pulumi.Input<string>;
    /**
     * The expiration date of the service account token.
     */
    expiresAt: pulumi.Input<string>;
    /**
     * The ID of the service account this token is bound to.
     */
    serviceAccountId: pulumi.Input<number>;
}
